### ISSUE TITLE
Not work out of a VM

### ISSUE THREAD

**Issue by ALebrunDev** [jazzband/django-debug-toolbar#1000]
Hello,
I try to use the debug tool bar.
I use an ubuntu Virtual Machine. When i use a web browser in the VM the toolbar work but not in my local computer.
![local](https://user-images.githubusercontent.com/17504922/31553252-24a28bac-b03a-11e7-9aa1-21052e509956.PNG)
![vm](https://user-images.githubusercontent.com/17504922/31553253-24cd92de-b03a-11e7-94dd-b10d377030e1.PNG)
Thank you

**Comment by matthiask** [comment]
This might be the reason? http://django-debug-toolbar.readthedocs.io/en/latest/installation.html#internal-ips

**Comment by ALebrunDev** [comment]
It's work now, thanks a lot
