### ISSUE TITLE
Intercept redirects will cause ContentNotRenderedError with django-debug-toolbar 1.9 

### ISSUE THREAD

**Issue by hirokiky** [jazzband/django-debug-toolbar#1009]
I tried newest django-debug-toolbar, 1.9.
And when I enabled Intercept Redirects and accessed a view returns 302, It returned `ContentNotRenderedError`:

```
ContentNotRenderedError at /admin/

The response content must be rendered before it can be accessed.

Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/admin/
Django Version: 	1.11.7
Exception Type: 	ContentNotRenderedError
Exception Value: 	

The response content must be rendered before it can be accessed.

Exception Location: 	/tmp/venv/lib/python3.6/site-packages/django/template/response.py in content, line 129
Python Executable: 	/tmp/venv/bin/python
Python Version: 	3.6.3
Python Path: 	

['/tmp/myproj',
 '/usr/lib/python36.zip',
 '/usr/lib/python3.6',
 '/usr/lib/python3.6/lib-dynload',
 '/tmp/venv/lib/python3.6/site-packages']

Server time: 	Wed, 15 Nov 2017 11:17:34 +0000

Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/admin/

Django Version: 1.11.7
Python Version: 3.6.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'debug_toolbar']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback:

File "/tmp/venv/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/tmp/venv/lib/python3.6/site-packages/django/utils/deprecation.py" in __call__
  142.             response = self.process_response(request, response)

File "/tmp/venv/lib/python3.6/site-packages/debug_toolbar/middleware.py" in process_response
  125.         content = force_text(response.content, encoding=response.charset)

File "/tmp/venv/lib/python3.6/site-packages/django/template/response.py" in content
  129.                 'The response content must be rendered before it can be accessed.'

Exception Type: ContentNotRenderedError at /admin/
Exception Value: The response content must be rendered before it can be accessed.
```

## Reason

This error caused by `content = force_text(response.content, encoding=response.charset)`, accessing `response.content`.

In this case the `response` was returned by `RedirectsPanel`.
https://github.com/jazzband/django-debug-toolbar/blob/master/debug_toolbar/panels/redirects.py#L9

The panel returns `SimpleTemplateResponse` object. this class will raise `ContentNotRenderedError` when `response.content` was accessed before calling `response.render()`.
like `content = force_text(response.content, ...)`.

This error wasn't on django-debug-toolbar 1.8.
And I think this change caused it
https://github.com/jazzband/django-debug-toolbar/commit/c369384945cfc5a4e65fa5f153e231a7ec06b11b

## Fix idea

Simply, we can avoid this error by adding `response.render()` in `RedirectsPanel`,
folloing here https://github.com/jazzband/django-debug-toolbar/blob/master/debug_toolbar/panels/redirects.py#L27

like this.

```python
                # Using SimpleTemplateResponse avoids running global context processors.
                response = SimpleTemplateResponse('debug_toolbar/redirect.html', context)
                response.cookies = cookies
                response.render()
```

Or any other nice plan? (or this issue was not correct?)
I don't know well about codes of django-debug-toolbar, so I didn't create PR yet.
Please ask and tell me anything.

**Comment by matthiask** [comment]
I don't have the time right now to think about the best way to fix this, but maybe @jdufresne has an idea? If not I'll get back to this in the next few days.

This is a regression introduced by 64ef4a3bbb4d9d5d38933ebb8b3bdea38ccee4dd, and unfortunately there was no test to detect this :-/

**Comment by jdufresne** [comment]
> Simply, we can avoid this error by adding response.render() in RedirectsPanel

I believe this would still be a problem for `DebugToolbarMiddleware` for handling any other `SimpleTemplateResponse`/`TemplateResponse`. These types of responses could be returned by any view or middleware, not just django-debug-toolbar. It looks like `DebugToolbarMiddleware` never had support for delayed rendering. I'll add this with tests. I _think_ the correct approach is to render the content just before manipulating it:

```py
        # If the response supports deferred rendering and hasn't been rendered
        # yet, then ensure that it does get rendered before proceeding further.
        if hasattr(response, 'render') and callable(response.render):
            response.render()
        # Insert the toolbar in the response.
        content = force_text(response.content, encoding=response.charset)
```

**Comment by jdufresne** [comment]
After further analyzing the issue, I think @hirokiky original suggested fix is the best one. I think it is incorrect for `Panel.process_resposne()` to return a non-rendered response. Unlike Django middleware, panels do not have the (`process-template-response`)[https://docs.djangoproject.com/en/1.11/topics/http/middleware/#process-template-response] method to ensure that the response is eventually rendered. As I don't see a use case for panels returning non-rendered response, I don't think there is a need ot add one.

**Comment by hirokiky** [comment]
Thank you for your reply and fix @jdufresne and @matthiask .
I understood about the middleware.

**Comment by hirokiky** [comment]
It means third party panels which returns response from process_response method should call `.render()` method too.
But I think there's not so much panels like intercept redirects, It won't be so big issue.
