### ISSUE TITLE
Unexpected argument force in url()

### ISSUE THREAD

**Issue by manojkataria31** [jazzband/django-debug-toolbar#1016]
https://github.com/jazzband/django-debug-toolbar/blob/36d3c039ea8bb6b989e9136b623fee0ad770caff/debug_toolbar/panels/staticfiles.py#L69

I think url() function should have input argument force as it is there in the django-contrib-staticfiles library

https://github.com/django/django/blob/fc22a0a2142c3416d7113dec95c4026bd846a851/django/contrib/staticfiles/storage.py#L151

Because this is missing I am getting `unexpected argument force` error.

**Comment by jdufresne** [comment]
That makes sense to me. Would you like to contribute a PR that includes a test?

**Comment by tim-schilling** [comment]
Confirmed this is still an issue.

**Comment by tim-schilling** [comment]
I don't believe this is an issue. When the system uses the manifest storage class, the toolbar's class inherits from it. If this is still an issue, please provide some setup information.
