### ISSUE TITLE
No such file or directory: '/static/sass'

### ISSUE THREAD

**Issue by typistX** [jazzband/django-debug-toolbar#1021]
Upon installing by following the docs, my project is loading with this error:

> FileNotFoundError: [Errno 2] No such file or directory: '/static/sass'

I have my static folder set up in the PROJECT root like so:

```
-static
--main_app_name
---sass
----folders and files
```

My settings.py relevant snippets:

```
STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "/static/sass/"),
)

STATICFILES_FINDERS =  [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]
```

Not sure what's wrong..

**Comment by matthiask** [comment]
```
>>> os.path.abspath('.')
'/home/ubuntu'
>>> os.path.join('/home/ubuntu', '/static/sass')
'/static/sass'
>>> 
```

You're using `os.path.join` incorrectly. You should use `os.path.join(BASE_DIR, 'static', 'sass')` instead. (Starting the second argument with a slash means that it already is an absolute path, and the first argument is thrown away)
