### ISSUE TITLE
ValueError on profiling panel when expecting a file path and getting a module path

### ISSUE THREAD

**Issue by omritoptix** [jazzband/django-debug-toolbar#1023]
In the function `func_std_string` the profiler expects a **file name containing a '/' separator**, but sometimes it gets a **module path instead**, and a ValueError is raised.

In the following lines:
`file_path, file_name = file_name.rsplit(os.sep, 1)`

I get back file_name = `<frozen importlib._bootstrap>` when using `pickle.loads` as part of my function, which causes ValueError and the panel not to render.

**Comment by yanjost** [comment]
I fixed this in pull request #1056

**Comment by tim-schilling** [comment]
Closed in #1056
