### ISSUE TITLE
SuspiciousFileOperation at / The joined path (/jquery-1.11.1.min.js) is located outside of the base path component (path_to_project/env/lib/python3.5/site-packages/django/contrib/admin/static)

### ISSUE THREAD

**Issue by resgef** [jazzband/django-debug-toolbar#1025]
![screenshot-localhost-8000-2018-01-09-16-04-14-033](https://user-images.githubusercontent.com/6162810/34715543-3bd71f42-f557-11e7-9482-028751e1ef79.png)

**Comment by matthiask** [comment]
Where does the initial slash in `/jquery-...` come from? It does not look correct and is very probably the reason for this problem.

**Comment by ajostergaard** [comment]
Same error as @RoelantStegmann but with the django error included (in case it triggers somebody...):

> ERROR django.security.SuspiciousFileOperation The joined path (/images/placeholder255x255.png) is located outside of the base path component (/usr/local/lib/python3.5/dist-packages/versatileimagefield/static) [PID:23041:MainThread]

**Comment by matthiask** [comment]
I'm also using versatileimagefield and placeholders in a few projects, and haven't seen this error once.

Can someone post their versatileimagefield configuration and field instantiation?

**Comment by ajostergaard** [comment]
Just copying code from Saleor:

```
VERSATILEIMAGEFIELD_RENDITION_KEY_SETS = {
    'products': [
        ('product_gallery', 'crop__540x540'),
        ('product_gallery_2x', 'crop__1080x1080'),
        ('product_small', 'crop__60x60'),
        ('product_small_2x', 'crop__120x120'),
        ('product_list', 'crop__255x255'),
        ('product_list_2x', 'crop__510x510')]}

VERSATILEIMAGEFIELD_SETTINGS = {
    # Images should be pre-generated on Production environment
    'create_images_on_demand': get_bool_from_env(
        'CREATE_IMAGES_ON_DEMAND', DEBUG),
}

PLACEHOLDER_IMAGES = {
    60: 'images/placeholder60x60.png',
    120: 'images/placeholder120x120.png',
    255: 'images/placeholder255x255.png',
    540: 'images/placeholder540x540.png',
    1080: 'images/placeholder1080x1080.png'}

DEFAULT_PLACEHOLDER = 'images/placeholder255x255.png'
```

And [an example](https://github.com/mirumee/saleor/blob/master/saleor/dashboard/product/widgets.py)  of it being used.

Sorry, not really sure what to look for. :-/

**Comment by matthiask** [comment]
@resgef Did you find a solution for the problem? Please share it, so that everyone may profit.

**Comment by ajostergaard** [comment]
@matthiask for me the fix was: https://github.com/mirumee/saleor/pull/2534

**Comment by matthiask** [comment]
Nice, that's exactly what I thought. I'm a bit surprised it worked for saleor before though.

**Comment by ajostergaard** [comment]
@matthiask there's no guarantee that it did. :)

**Comment by Idriss687** [comment]
Hi how can i fix this ?
SuspiciousFileOperation at / The joined path (/jquery-1.11.1.min.js , js)
