### ISSUE TITLE
Toolbar is not visible in admin panel

### ISSUE THREAD

**Issue by Arlington1985** [jazzband/django-debug-toolbar#1027]
How can I make toolbar to be visible in admin panel?

**Comment by jdufresne** [comment]
This works for me using the shipped example application. I can't reproduce the issue as stated. Do you have more details about how to reproduce or a minimal example project?

**Comment by Arlington1985** [comment]
This issue can be closed, this was my fault

**Comment by AshrafYounis95** [comment]
Can you post the solution? I am having a similar problem where the toolbar is showing up on the site but not in the admin pages.

**Comment by joncasdam** [comment]
+1 on 
> Can you post the solution?

**Comment by bugov** [comment]
@joncasdam 

```
INTERNAL_IPS = ('127.0.0.1')
DEBUG = True
```

```
INSTALLED_APPS += [
    'debug_toolbar',
]

MIDDLEWARE += [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]
```
