### ISSUE TITLE
Missing SQL queries

### ISSUE THREAD

**Issue by marfire** [jazzband/django-debug-toolbar#1041]
While recently trying to diagnose a slow admin page, I noticed that certain queries were missing from the SQL panel. By looking at the `django.db.backends` log I can see that the missing queries are exactly those that are using named cursors (`DECLARE ... NO SCROLL CURSOR WITH HOLD FOR SELECT `) instead of regular `SELECT` statements. I believe that these are server-side cursors used with PostgreSQL for code that uses `queryset.iterator()` (such as [`ModelChoiceField`](https://github.com/django/django/blob/a38ae914d89809aed6d79337b74a8b31b6d3849a/django/forms/models.py#L1136)).

So my guess is that DJDT is not recording queries that use these cursors, but I'm not sure.

I'm using DJDT version 1.9.1 and Django 2.0.1.

**Comment by cmackenziek** [comment]
I'm also seeing this behaviour, big queries that use queryset.iterator() that I'd like to analyze are missing.

**Comment by shangzhikeji** [comment]
I also met this problem.How to fix it?
