### ISSUE TITLE
Documentation Enhancement Request : Installation Instructions

### ISSUE THREAD

**Issue by Lcstyle** [jazzband/django-debug-toolbar#1046]
Requesting that the install instructions add the following information: 

# running `python manage.py collectstatic` is necessary for the toolbar to appear properly.

### Additional Enhancements:

- "limiting access to the toolbar by IP"
```
http://dancarroll.org/blog/2011/01/debugging-django-dev-server/
if DEBUG:

from fnmatch import fnmatch
class glob_list(list):
def __contains__(self, key):
for elt in self:
if fnmatch(key, elt): return True
return False

INTERNAL_IPS = glob_list(['127.0.0.1', '192.168.*.*'])

```
- "Limiting access to the toolbar by specific User"

```
https://stackoverflow.com/questions/6548947/how-can-django-debug-toolbar-be-set-to-work-for-just-some-users?rq=1
def show_toolbar(request):
return request.user and request.user.username == "yourusername"

DEBUG_TOOLBAR_CONFIG = {
'SHOW_TOOLBAR_CALLBACK': 'projectname.settings.show_toolbar',
# Rest of config}
```

**Comment by jdufresne** [comment]
Improving the docs to help users getting started would be welcome, but I'd like see the proposal in more concrete terms first. Would you like to create a PR with you suggested changes? Then we could see what the improvements would look like.

**Comment by Abhijrathod** [comment]
can i do this

**Comment by matthiask** [comment]
I'm going to close this issue with the same reasoning as provided here: https://github.com/jazzband/django-debug-toolbar/issues/1591#issuecomment-1062618510

Feel free to reopen if you disagree, or contribute in a different area. Thank you!

**Comment by tim-schilling** [comment]
@Abhijrathod if you want to make an attempt at improving our documentation, please feel free to do so.
