### ISSUE TITLE
Extremely slow when generic relationships

### ISSUE THREAD

**Issue by LeonardoGentile** [jazzband/django-debug-toolbar#1048]
Hello
I have a view showing the result of a model having generic relationships.
This template produces a 544 sql  queries (surely I will fix this) but the toolbar says that it 'only' 
 took 400ms. 

Nonetheless the time to load the page varies from 30sec to 1minute.

Disabling the SQL panel seems to fix the problem.

Django 1.11
Django-debug-toolbar 1.8 and 1.9.1 (tried both)

**Comment by tim-schilling** [comment]
Closing in favor of #1402
