### ISSUE TITLE
Django contrib apps excluded from SQL stacktrace

### ISSUE THREAD

**Issue by cjwright83** [jazzband/django-debug-toolbar#1049]
Despite behaviour documented [here](https://github.com/jazzband/django-debug-toolbar/blob/master/debug_toolbar/utils.py#L55-L61), the Django contrib apps are being excluded from SQL stacktraces on my application. The code itself doesn't seem to be retaining Django contrib apps in the stacktrace; it looks like everything within the Django module would be getting excluded.

Django==2.0.2
django-debug-toolbar==1.9.1

**Comment by matthiask** [comment]
Probably fixed by https://github.com/jazzband/django-debug-toolbar/pull/1073 (not released yet, but hopefully soon)
