### ISSUE TITLE
raise ImproperlyConfigured(msg.format(name=self.urlconf_name))django.core.exceptions.ImproperlyConfigured:

### ISSUE THREAD

**Issue by Deepaksinghmadan** [jazzband/django-debug-toolbar#1067]
raise ImproperlyConfigured(msg.format(name=self.urlconf_name))django.core.exceptions.ImproperlyConfigured:
'<function ______ at _________location>'does not appear to have any patterns in it

**Comment by tim-schilling** [comment]
@Deepaksinghmadan Can you provide some additional information on how to reproduce this?

**Comment by jdufresne** [comment]
Closing due to lack of response.
