### ISSUE TITLE
Multiple queries in viewset with raw query and view sql

### ISSUE THREAD

**Issue by mapeveri** [jazzband/django-debug-toolbar#1082]
Hi, I'm using django rest framework and django debug toolbar with a viewset that uses a raw sql because it loads a view. Like this:

```
sql = "select * " \
         " from sprintsview_task_bygroup " \
         " where project_id = %s"

self.queryset = list(Task.objects.raw(sql, params))
```

The problem that when I install django debug toolbar, executes multiple queries of more, it does not happen if I do not have django debug toolbar installed. 

![image](https://user-images.githubusercontent.com/6276555/44910260-eba31300-acf8-11e8-96d5-c648866505c0.png)

They are only 20 records

Any idea?

Thanks!

**Comment by tim-schilling** [comment]
Is this still an active issue for you @mapeveri?

**Comment by tim-schilling** [comment]
Closing due to lack of response.
