### ISSUE TITLE
ImproperlyConfigured error in Django 1.9

### ISSUE THREAD

**Issue by arielpontes** [jazzband/django-debug-toolbar#1087]
I'm running Django 1.9.13, Python 2.7.15, django-debug-toolbar 1.9.1, and when I try to add `'debug_toolbar'` to `INSTALLED_APPS` I get:

    django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: debug_toolbar

**Comment by matthiask** [comment]
Sounds like for some reason you added `debug_toolbar` twice?
