### ISSUE TITLE
Logging not being captured on Django Admin Page

### ISSUE THREAD

**Issue by ramezkabbani** [jazzband/django-debug-toolbar#1099]
It seems that the logging panel isn't capturing log records when I'm on the Admin panel.
I can get it to work everywhere but on Django Admin pages.

**Steps to reproduce**
1- Override save() method of a model to 
```
import logging
logger = logging.getLogger(__name__)
...
class Foo(models.Model):
    def save(self,*args,**kwargs):
        super().save(*args, **kwargs)
        logger.error("log message")
        print("If this shows up in console we now that method is being called")
```
Logging settings in settings.py
```
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'incremental': True,
    'root': {
        'level': 'DEBUG',
    },
}
```
2- Go to Django admin and update a model instance to trigger save(). Notice lack of logging message in DDT logging panel, but "If this shows up in console we now that method is being called" showing up in console.
3- Remove DDT from Django project
4- Go to Django Admin and trigger save()
5- Notice log message show up in console

**Comment by tim-schilling** [comment]
Please try enabling "Intercept Redirects". I believe that's the issue you're encountering.
