### ISSUE TITLE
toolbar.js ReferenceError 1.10.1

### ISSUE THREAD

**Issue by daneb5** [jazzband/django-debug-toolbar#1101]
Hello,

with the Django Version 1.11.15 and django-debug-toolbar 1.10.1 I get a ReferenceError in Chrome:

![error](https://user-images.githubusercontent.com/25485984/45404970-5b9e8b00-b661-11e8-9e1c-bc6c2a88f75d.PNG)

With 1.9.1 everything works fine.

**Comment by matthiask** [comment]
That's a surprising error. Line 306 of toolbar.js does not contain any mention of `djdt` in 1.10.1:
https://github.com/jazzband/django-debug-toolbar/blob/27f8a70953aebbd4949dc34ef552ce441d463a40/debug_toolbar/static/debug_toolbar/js/toolbar.js#L306

Sure enough, in 1.9.1. it does:
https://github.com/jazzband/django-debug-toolbar/blob/c8345d2e1c04e784dc8d38681a0037b1e0849066/debug_toolbar/static/debug_toolbar/js/toolbar.js#L306

Are you sure that you run collectstatic? Or that the installation isn't broken in some other way?

**Comment by daneb5** [comment]
It was a chrome caching problem ... Delete cookies etc. . It works now.
Thanks!
