### ISSUE TITLE
Should SQL queries be counted when they are generated by a logger at 'DEBUG' level?

### ISSUE THREAD

**Issue by chrisconlan** [jazzband/django-debug-toolbar#1122]
I was baffled for a few hours trying to figure out where a bunch of unnecessary queries were coming from on my app. I used `django-debug-toolbar`, which was a big help, but it also threw me a significant red herring.

If your logging setup looks anything like this ...
```
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'info_to_file': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'django.log'),
        },
    },
    'loggers': {
        'django': {
            'handlers': ['info_to_file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
```

... then you are logging every SQL query made to the database when `DEBUG == True`. I do this during development sometimes, because it is a built-in way to solve the same problems `django-debug-toolbar` addresses.

#### The problem
When I had my logger at `'level': 'DEBUG'` and `django-debug-toolbar` running, my page was generating queries at `O(n)` for `n` objects on the page, because every time this exception is raised, `django.template.base.VariableDoesNotExist: Failed lookup for key [some_template_variable] in ...`, the Django logger prints the **entire** template context.

When the Django logger prints the template context, `__repr__()` and `__str__()` are called on every object in the context. This is a huge problem when you have foreign keys in your `__str__()` methods, and quickly balloons your queries to `O(n)`. 

So, I solved my ballooning query problem by switching the debug level to `'INFO'` during development. Immediately, queries were `O(1)` again. I was a little frustrated, because I just spent a lot of time debugging extra queries caused by my debugger. And I was just generally frustrated that the logger was even capable of running database queries.

#### Solving the problem
Can we make a special distinction for for queries generated by the Django logger?

**Comment by matthiask** [comment]
We have removed the logging panel in January 2023, I think this issue can be closed.
