### ISSUE TITLE
django-debug-toolbar 

### ISSUE THREAD

**Issue by piscvau** [jazzband/django-debug-toolbar#1123]
Django-debug-toolbar causes FileNotFoundError at /admin/ and prevents Django form finding static. 
The error disappears if INTERNAL_IPS is commented but the toolbar does not appear.
Folling are settings.py and urls.py renamed in .txt
[urls.txt](https://github.com/jazzband/django-debug-toolbar/files/2683119/urls.txt)

[settings.txt](https://github.com/jazzband/django-debug-toolbar/files/2683118/settings.txt)

**Comment by matthiask** [comment]
Which files cannot be found?

It's quite probable that the reason for this is a misconfiguration or a missing deployment step. But additional details and a full traceback would help greatly debugging this issue.

**Comment by piscvau** [comment]
I am in development phase and so there is no deployment.  here is the traceback
 http://dpaste.com/16CJDAT
Is this the appropriate way to give you full traceback?

**Comment by tim-schilling** [comment]
@piscvau Is this still an issue or can this be closed?

**Comment by tim-schilling** [comment]
Closing due to lack of response.
