### ISSUE TITLE
Django Toolbar SQL queries are shown as none

### ISSUE THREAD

**Issue by gosrinin** [jazzband/django-debug-toolbar#1124]
![image](https://user-images.githubusercontent.com/46101043/50393465-6c8c8b80-077c-11e9-9575-98bef9ec87bb.png)

Sql queries are not shown the queries timer is shown where as the queries are shown as none.

Below is the version used.
OS:Windows10
Django |   | 2.1.4
Python |   | 3.7.1
debug_toolbar | Debug Toolbar | 1.11
rest_framework | Django REST framework | 3.9.0

**Comment by leehinde** [comment]
(in my case, I'm using Django 1.11.18

**Comment by anthonywittig** [comment]
We noticed that upgrading from Django 2.1.4 -> 2.1.5 fixed it for us.

OS: Mac
Python: 3.7
Debug Toolbar: 1.11

**Comment by kiruh** [comment]
I had same issue with django debug toolbar. Seems like mysqlclient was the problem.

I downgraded [mysqlclient](https://stackoverflow.com/a/54111858/6870734) from version 1.3.14 to 1.3.13 and it's working now.

**Comment by leehinde** [comment]
I played with various mysql client versions and was still seeing none. I'm also getting 'none' as the output from runserver_plus (from django extensions) with the optional --print-sql. Just more data points, but it does suggest this is an issue outside DDT.

Fwiw, I can get the queries when debugging with PyCharm. So, I can combine the timing data from DDT and get the query from PyCharm.

**Comment by zzelman** [comment]
@kiruh your recommendation to downgrade mysqlclient worked for me

OS: arch linux
Python: 3.7.1

Django==2.0.5
mysqlclient==1.3.14 --> 1.3.13
django-debug-toolbar==1.11

**Comment by mbargiel** [comment]
FWIW, I just ran into the same issue. Django 1.11.6, mysqlclient 1.3.14. Choosing a different mysqlclient version  fixed it for me. I tried downgrading to 1.3.12 and upgrading to 1.4.4, both worked for me.

**Comment by tim-schilling** [comment]
Is this failing for newer versions of DDT? Seems like every reproduction was using 1.11.

**Comment by tim-schilling** [comment]
The latest version of Django 2.1 and solve this problem. This is still a problem for Django 1.11. [As per this thread](https://github.com/django/django/pull/10726#issuecomment-444887383), Django 1.11 won't fix this. Closing this issue.

**Comment by jcaes** [comment]
I have the same problem, in my case with python 3.6 and django 1.11, downgrade mysqlclient fix it

Django==1.11.29
django-debug-toolbar==2.2
mysqlclient==2.0.1 --> 2.0.0
