### ISSUE TITLE
SQL panel doesn't track UPDATE's.

### ISSUE THREAD

**Issue by hmpf** [jazzband/django-debug-toolbar#1134]
The SQL panel only ever shows SELECT's, never UPDATE's. Is this intentional?

**Comment by matthiask** [comment]
Is it possible that you don't see UPDATEs because you're getting redirected after the POST request to a page which only runs GET requests again?

**Comment by matthiask** [comment]
Try the "intercept redirects" checkbox then! You only see the queries of the current request, not queries from previous requests.

**Comment by hmpf** [comment]
That fixed it. How long has that checkbox been there though :) Never noticed it before, maybe because it is at the bottom and I rarely use tall browser windows.

**Comment by tim-schilling** [comment]
Closing as the suggestion worked for the author.
