### ISSUE TITLE
Incoporate Python-Hunter?

### ISSUE THREAD

**Issue by guettli** [jazzband/django-debug-toolbar#1146]
Some days ago I came across a cool tracing tool for python:

https://python-hunter.readthedocs.io/en/latest/

It would be very cool if I could trace django requests via django debug toolbar.

But maybe there is already a way to trace via DDT.

My use case:  show all lines of the module name "foo" which get executed during the request.

In most cases I don't want to see lines from stdlib or django. Bugs are usually in my code :-)

What do you think?

**Comment by tim-schilling** [comment]
Did you try enabling the [ProfilingPanel](https://django-debug-toolbar.readthedocs.io/en/latest/panels.html#profiling)? I believe a third party panel would have to be created that would integrate python-hunter into DDT.

**Comment by guettli** [comment]
Sounds good. I hope some young and talented dev has time to implement this.

**Comment by tim-schilling** [comment]
Opening back up for a third party request idea.

**Comment by tim-schilling** [comment]
Closing in favor of #1460
