### ISSUE TITLE
Attribute Error with Request Panel

### ISSUE THREAD

**Issue by MiStErLu** [jazzband/django-debug-toolbar#1150]
Hi,

    I found a bug with the Request Panel :
    If i use a "Paginator" object and if i click on the next link i got this error

    If i disable Request Panel, it work.
    I use : django-debug-toolbar==1.11
> Environment:
> 
> 
> Request Method: GET
> Request URL: http://127.0.0.1:8000/search/sets?page=2
> 
> Django Version: 2.1.7
> Python Version: 3.6.5
> Installed Applications:
> ('django.contrib.auth',
>  'django.contrib.contenttypes',
>  'django.contrib.sessions',
>  'django.contrib.sites',
>  'django.contrib.messages',
>  'django.contrib.staticfiles',
>  'django.contrib.admin',
>  'hijack',
>  'compat',
>  'ajax_select',
>  'ckeditor',
>  'ckeditor_uploader',
>  'mathfilters',
>  'captcha',
>  'django_crontab',
>  'monapp',
>  'monapp.apps.search',
>  'monapp.apps.manage',
>  'monapp.apps.buy',
>  'hijack_admin',
>  'coverage',
>  'debug_toolbar')
> Installed Middleware:
> ['django.middleware.security.SecurityMiddleware',
>  'django.contrib.sessions.middleware.SessionMiddleware',
>  'django.middleware.common.CommonMiddleware',
>  'django.middleware.csrf.CsrfViewMiddleware',
>  'django.contrib.auth.middleware.AuthenticationMiddleware',
>  'django.contrib.messages.middleware.MessageMiddleware',
>  'django.middleware.clickjacking.XFrameOptionsMiddleware',
>  'debug_toolbar.middleware.DebugToolbarMiddleware']
> 
> 
> 
> Traceback:
> 
> File "/home/xxxxxx/.virtualenvs/monapp/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
>   34.             response = get_response(request)
> 
> File "/home/xxxxxx/.virtualenvs/monapp/lib/python3.6/site-packages/django/utils/deprecation.py" in __call__
>   93.             response = self.process_response(request, response)
> 
> File "/home/xxxxxx/.virtualenvs/monapp/lib/python3.6/site-packages/debug_toolbar/middleware.py" in process_response
>   133.                 panel.generate_stats(request, response)
> 
> File "/home/xxxxxx/.virtualenvs/monapp/lib/python3.6/site-packages/debug_toolbar/panels/request.py" in generate_stats
>   33.                 "post": [(k, request.POST.getlist(k)) for k in sorted(request.POST)],
> 
> File "/home/xxxxxx/.virtualenvs/monapp/lib/python3.6/site-packages/debug_toolbar/panels/request.py" in <listcomp>
>   33.                 "post": [(k, request.POST.getlist(k)) for k in sorted(request.POST)],
> 
> Exception Type: AttributeError at /search/sets
> Exception Value: 'dict' object has no attribute 'getlist'
>

**Comment by matthiask** [comment]
Someone or something is replacing the `request.POST` `QueryDict` with a `dict`. Do you have any idea what might be replacing `request.POST` with an incompatible data type?

**Comment by MiStErLu** [comment]
It probably came from this code :

> @login_required
> def search_sets(request):
>     if not request.method == 'POST' and 'page' in request.GET:
>         if 'search-sets-post' in request.session:
>             request.POST = request.session['search-sets-post']
>             request.method = 'POST'
> 
>     if request.method == 'POST':
>         # create a form instance and populate it with data from the request:
>         form = SetSearch(request.POST)
>         request.session['search-sets-post'] = request.POST

**Comment by matthiask** [comment]
Yes, that doesn't look right.

**Comment by tim-schilling** [comment]
@MiStErLu Did changing that method fix your problem?

**Comment by MiStErLu** [comment]
@tim-schilling I don't change my method, for testing this functionality i disable django-debug-toolbar. In production, it's not enable

**Comment by tim-schilling** [comment]
Correct, but you shouldn't be doing `request.POST = request.session['search-sets-post']`. `request.POST`, `request.GET` and `request.FILES` should only be read from in the views, not assigned to.

**Comment by jdufresne** [comment]
I agree. This is a incorrect use of the Django request API and not the fault of Debug Toolbar. I think the view above should be considered to have a bug and fixed. I'm closing, but if you can demonstrate a bug in Debug Toolbar, please provide more detail.

**Comment by mark-mishyn** [comment]
Hi guys. 

I have the same issue.

Eventually I could not find the place where request.POST is set to regular dict.

I came up with the following hack/fix in _debug_toolbar/panel/request.py_

```def generate_stats(self, request, response):
    from django.http import QueryDict
        
    if isinstance(request.POST, dict):
        query_dict = QueryDict('', mutable=True)
        query_dict.update(request.POST)
        request.POST = query_dict
        ...
```
