### ISSUE TITLE
404 error  on django 2.2

### ISSUE THREAD

**Issue by find456789** [jazzband/django-debug-toolbar#1152]
in django 2.1 it's work

but in django 2.2 ,  i got 404 error 

![image](https://user-images.githubusercontent.com/6580897/55684960-ae37ef80-5983-11e9-83d9-3833e90ebd2e.png)

![image](https://user-images.githubusercontent.com/6580897/55684966-b728c100-5983-11e9-8c1c-8de39fd0c072.png)

![image](https://user-images.githubusercontent.com/6580897/55684970-c445b000-5983-11e9-90d9-b8c5290695b5.png)

**Comment by find456789** [comment]
when i remove  django-debug-toolbar  code  in urls.py and in settings.py,  it's work ok

 
![image](https://user-images.githubusercontent.com/6580897/55685016-3ae2ad80-5984-11e9-935e-d3fdc884ea93.png)

**Comment by kwist-sgr** [comment]
In Django 2.2 I use such code:
```python
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
```

**Comment by find456789** [comment]
thank you @kwist-sgr 

but it's not work,   
i used django 2.2
python 3.7.3

**Comment by ryanjkoehler** [comment]
I have the exact same issue. I'm not sure why it was closed.

**Comment by symonsoft** [comment]
Same issue

**Comment by m3brown** [comment]
To offer some potential closure on this issue, the problem may be that an earlier pattern is claiming the __debug__/ path. For example, a catch-all pattern like this: `url(r"", include(app_urls)),`

In this case, the workaround is to put the debug toolbar path earlier in the list. For example:

```
if settings.DEBUG:
    import debug_toolbar
    urlpatterns.insert(0, path('__debug__/', include(debug_toolbar.urls)))
```
