### ISSUE TITLE
Static file "djdt_vertical.png" problem.

### ISSUE THREAD

**Issue by bukowa** [jazzband/django-debug-toolbar#1153]
As you can see below a request to ````/img/djdt_vertical.png```` is made, but the static file is already loaded from the correct path ````debug_toolbar/img/djdt_vertical.png````

Chrome dev tools says the indicator is toolbar.js:244
https://github.com/jazzband/django-debug-toolbar/blob/master/debug_toolbar/static/debug_toolbar/js/toolbar.js#L244

````
hide_toolbar	@	toolbar.js:244
init	@	toolbar.js:217
````
![chrome_A5QoNDQJyC](https://user-images.githubusercontent.com/38087302/56055015-bf547800-5d58-11e9-9ac8-3846d0049045.png)

**Comment by tim-schilling** [comment]
Is it possible that you're loading the `toolbar.css` resource multiple times, but in different locations? It would need to be loaded at `http://localhost:4445/toolbar.css` and `http://localhost:4445/static/debug_toolbar/toolbar.css` in order to produce the effect you're seeing.

**Comment by bukowa** [comment]
Sorry it was some time ago i cannot reproduce it now. Thanks for your input!
