### ISSUE TITLE
Allow impersonation of user accounts

### ISSUE THREAD

**Issue by ilar** [jazzband/django-debug-toolbar#1154]
A lot of times, what a user sees, or even what different users see, can be vastly different. And while there's value in ensuring that your log-in/log-out functionality works when swapping users in your dev environment, it seems like it could be a useful feature for DDT to allow for a 'quick-swapper' between existing users, so you can quickly swap through the current page and make sure it behaves as expected for your users as you're creating it.

Thoughts?

**Comment by Sult** [comment]
Do not know how well it works, but you might be able to use something like: https://django-hijack.readthedocs.io/en/stable/ next to DDT.

**Comment by schinckel** [comment]
The other one I've used is https://pypi.org/project/django-impersonate/.

I'd argue that functionality like that belongs in a totally different app, not DDT.

**Comment by tim-schilling** [comment]
Closing as this is outside the bounds for DDT.
