### ISSUE TITLE
Error in the toolbar.js 

### ISSUE THREAD

**Issue by agultekin** [jazzband/django-debug-toolbar#1158]
Hi,

I am using Django 2.1.2.
I try to show information with djdt (sql, parameters or static files) but I have the following error:

`
Uncaught TypeError: fetch is not a function
    at ajax (toolbar.js:45)
    at HTMLAnchorElement.<anonymous> (toolbar.js:88)
    at HTMLUListElement.<anonymous> (toolbar.js:7)
`

In information page (gray, yellow), the spinner continue to run (acts like fetching data).

**Comment by matthiask** [comment]
You

**Comment by agultekin** [comment]
I am using Chrome Version 73.0.3683.103 (Build officiel) (64 bits)
This is the latest version.
I have the same problem on Safari.
On Ubuntu 18.04 with Chrome & Firefox the problem is the same

**Comment by matthiask** [comment]
That's very surprising. I'm running similar versions without problems. Could it be you're setting `window.fetch` to some variable in your code somewhere, e.g. `fetch = "bla"` without `var`? What is the value of `fetch` when you enter it in the console?

`fetch` should be available for years now (https://caniuse.com/#search=fetch)

**Comment by agultekin** [comment]
You've right 
I am using django notification module and in the template I write fetch=12 to get the 12 notifications.
This is why the fetch doesn't work.
Thank you for your answer, I close the issue.
