### ISSUE TITLE
STATIC_ROOT and STATICFILES_DIRS

### ISSUE THREAD

**Issue by HelloGit100** [jazzband/django-debug-toolbar#1166]
Django: 2.2
Python: 3.7.3

some code from base.html
```
{% load i18n static %}
<img src="{% static 'images/logo/logo.png' %}">
```

- 1，
When I add the following code to settings.py:

```
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
```

Django-debug-toolbar is working. But the website image is not displayed, http://127.0.0.1/static/images/logo/logo.png return 404.

- 2，
When I add the following code to settings.py:

```
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    '/static/',
]
```
Display the following information:
[Errno 2] No such file or directory: '/static'

- 3，
When I add the following code to settings.py:

```
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    '/static/',
]

STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
```
Display the following information:
ERRORS:
?: (staticfiles.E002) The STATICFILES_DIRS setting should not contain the STATIC_ROOT setting.

I want to make it django-debug-toolbar work, and display the website image.

**Comment by HelloGit100** [comment]
I found the reason, I should put the picture under ../venv/app_a/static/images/ instead of ../venv/static/images/.

**Comment by jokaypeday95** [comment]
use code import os in your file
