### ISSUE TITLE
Read the docs outdated

### ISSUE THREAD

**Issue by browniebroke** [jazzband/django-debug-toolbar#1177]
I was looking for changes in the recent 2.0 release and found a changelog in the documentation. However, it's missing the recent updates. Looking at the build history, RTD hasn't received webhooks in the past 6 months:

https://readthedocs.org/projects/django-debug-toolbar/builds/

I've had the same problem on other projects of mine and it's most likely due to a recent deprecations in their webhook:

https://blog.readthedocs.com/webhook-deprecations/

The fix is to get the new Webhook URL in the RTD [admin panel for integrations](https://readthedocs.org/dashboard/django-debug-toolbar/integrations/) and then add it in the [webhook section on Github](https://github.com/jazzband/django-debug-toolbar/settings/hooks).

**Comment by matthiask** [comment]
Thanks for the report. I have opened an issue here to track this: https://github.com/jazzband/roadies/issues/149

Unfortunately I cannot do this myself since I do not have the permission to edit repository settings here.

**Comment by matthiask** [comment]
I remembered that I can trigger a build manually :-)  while we're waiting for the webhook to be added.

https://django-debug-toolbar.readthedocs.io/en/latest/

**Comment by jezdez** [comment]
This should be fixed, I think RTD changed something with the GitHub integration, it basically doesn't work automatically since GitHub services have been deprecated in favor of GitHub apps.

**Comment by jezdez** [comment]
Ah, yeah, you linked to the blog post, sorry for misreading the ticket 😬
