### ISSUE TITLE
README says latest release is 1.11?

### ISSUE THREAD

**Issue by johnthagen** [jazzband/django-debug-toolbar#1182]
> The current stable version of the Debug Toolbar is 1.11. It works on Django ≥ 1.11.

Version 2.0 has been released onto PyPI. Is it stable? Does the README just need updated?

https://pypi.org/project/django-debug-toolbar/

A side effect is that the 2.0 PyPI page also has this text on it.

**Comment by matthiask** [comment]
Oh right, I forgot updating the README

**Comment by auvipy** [comment]
fixed
