### ISSUE TITLE
Missing 2x highres graphics

### ISSUE THREAD

**Issue by codingjoe** [jazzband/django-debug-toolbar#1184]
I noticed that the icons are 72dpi PNGs. I'd like to switch them to SVGs, to support all pixel densities.

@idan after some digging, it seems that you originally provided the graphics. Do you happen have any vector graphics, or should I just recreate them (as good as I can)?

**Comment by jdufresne** [comment]
All icons except for `./debug_toolbar/static/debug_toolbar/img/ajax-loader.gif` have been removed in favor of CSS.

Would you still like to change the loader to an SVG? I think a patch for that would be welcome.

**Comment by codingjoe** [comment]
@jdufresne why not, I opened a PR to remove the last relic.
