### ISSUE TITLE
Django 1.11 support should be removed from the docs

### ISSUE THREAD

**Issue by chescales** [jazzband/django-debug-toolbar#1186]
I've been trying this for a while now, as when upgrading the toolbar to the latest version (currently 2.0) starts giving `Not found` errors (see image below).

After reviewing that both the README and setup.py state that it's supporting Django 1.11, then I found that after toolbar 1.10 support for Django 1.11 was dropped: https://django-debug-toolbar.readthedocs.io/en/latest/changes.html#id4

Downgrading to `django-debug-toolbar<1.10` fixes the toolbar for Django 1.11 as expected.

Please amend the README and setup.py to reflect the actual Django versions supported.

Thanks!

![not-found](https://user-images.githubusercontent.com/3706329/60967420-8786ad80-a312-11e9-9654-05f75793d128.png)

**Comment by goblinJoel** [comment]
The changelog says, "Removed support for Django < 1.11." I think that would mean it still does support 1.11. I'm not sure why you're getting 404s though. Have you (or others) been loading pages between the time you load and the time you try to view a panel? (See RESULTS_CACHE_SIZE.) You could also check and make sure the new toolbar version's static assets are loading properly, though I think that would cause different problems.

**Comment by chescales** [comment]
Thanks @goblinJoel for the answer, you're right, my bad with the strict comparison :wink: I'll check what's going on then, and see if it effectively is a matter of dj1.11 being supported or not by the current code. If somebody is using dj1.11 with the latest version of the toolbar successfully it'd be great to know as well.

**Comment by goblinJoel** [comment]
@chescales For what it's worth, I'm in the process of upgrading Django from 1.11 to 2.2, and I updated debug toolbar to 2.0 first. The toolbar disappeared at first, but once I put its static assets where they need to be for my environment, it started working again. However, I didn't test very extensively before updating Django itself.

**Comment by chidg** [comment]
I'm on Django 1.11.6, and have used DDTB 1.9 and 2.0
Both work fine although can be very slow

**Comment by chescales** [comment]
Hi guys, thanks for your comments. I wonder what is the case then. I'll explain in more detail what's happening, as something's wrong but can't really figure out what it is.

I have tried many versions of DDTB, 1.9.1, 1.10 and 2.0. Still with version `<=1.9.1` it works well, with versions `>=1.10` it doesn't. The error is still the same, every menu button in the toolbar returns a 404. I'll provide more info on my installation below.

Here you can see the 404s, and the urls the toolbar is trying to access. I maybe doing something basic very wrong, but the point is that it works in 1.9.1 but not above that. I also checked the documentation to see what can be the problem, but failed to see it.

![Screen Shot 2019-10-09 at 14 58 39](https://user-images.githubusercontent.com/3706329/66489268-3ae47700-eaa7-11e9-8d7b-590dbd0e7c2a.png)

If I click on the right arrow (back arrow), it changes to the following, and stays loading forever:

![Screen Shot 2019-10-09 at 14 58 53](https://user-images.githubusercontent.com/3706329/66489309-4c2d8380-eaa7-11e9-8e64-298bb14968d5.png)

Going back to 1.9.1:

![Screen Shot 2019-10-09 at 15 07 38](https://user-images.githubusercontent.com/3706329/66489371-649d9e00-eaa7-11e9-86db-9736f91148cd.png)

Here is my installation. I tried reordering middleware position to no avail.

```python
# settings.py
if DEBUG:
    INSTALLED_APPS += [
        'debug_toolbar',
    ]
    MIDDLEWARE = [
        'debug_toolbar.middleware.DebugToolbarMiddleware',
    ] + MIDDLEWARE
    DEBUG_TOOLBAR_CONFIG = {
        'SHOW_TOOLBAR_CALLBACK': (
            'homewings.settings.core._show_debug_toolbar_callback'
        ),
    }

def _show_debug_toolbar_callback(request):
    """Append `?debug` to the URL to show Django debug toolbar."""
    return request.is_ajax() or 'debug' in request.GET


# urls.py
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = (
        [
            url(r'^__debug__/', include(debug_toolbar.urls)),
            url(r'^api-auth/', include('rest_framework.urls')),
        ]
        + urlpatterns
    )
```
