### ISSUE TITLE
Not getting the static files

### ISSUE THREAD

**Issue by sr6033** [jazzband/django-debug-toolbar#1193]
I did all the necessary changes required in settings.py and urls.py and I use `'django.contrib.staticfiles'` with `runserver`.
I don't have `STATIC_ROOT` but I have:
```
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]
```

Still, I don't get the debug tool properly shown.

![image](https://user-images.githubusercontent.com/15799589/62763728-e1150000-baa9-11e9-9caf-55024d39094a.png)
![image](https://user-images.githubusercontent.com/15799589/62763759-f1c57600-baa9-11e9-96d1-9dc352675cf9.png)

**Comment by GonzaloTunez** [comment]
try this

https://stackoverflow.com/questions/54135531/debug-toolbar-django-not-executing

worked for me

**Comment by tim-schilling** [comment]
@sr6033 Is this a still a problem and did you try the SO solution?

**Comment by sr6033** [comment]
@tim-schilling This issue still exists. I had to remove debug toolbar as I was not able to get any data.

**Comment by tim-schilling** [comment]
@sr6033 Did you run `python manage.py collectstatic`? Are the files actually where they should be on the server?

**Comment by sr6033** [comment]
@tim-schilling Yes the files are in there correct places.

**Comment by WayneLambert** [comment]
Just in case someone else lands on this page with a similar issue from searching, I had this problem. I had `whitenoise` as a project dependency (I use `pipenv`) without the middleware item being included.

What resolved it for me was putting the whitenoise middleware item within the `MIDDLEWARE` list setting within `settings.py` as shown below.

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    `'whitenoise.middleware.WhiteNoiseMiddleware', ` # Insert here
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

**Comment by matthiask** [comment]
I'm going to close this issue with the same reasoning as provided here: https://github.com/jazzband/django-debug-toolbar/issues/1591#issuecomment-1062618510

Feel free to reopen if you disagree. Thank you!
