### ISSUE TITLE
Incompatibility of django-toolbar 1.8 and django-extensions 2.2.1 caused by get_version method

### ISSUE THREAD

**Issue by Atala** [jazzband/django-debug-toolbar#1195]
Django-toolbar version : 1.8
Django-extensions version : 2.2.1

When using this 2 apps in conjunction, it breaks with message : `TypeError at / get_version() missing 1 required positional argument: 'version'`

Indeed django-toolbar uses the `get_version` attribute of django-extensions ([ref code](https://github.com/jazzband/django-debug-toolbar/blob/1.8/debug_toolbar/panels/versions.py#L43)) but this function expects an positional argument ([ref code](https://github.com/django-extensions/django-extensions/blob/4dcf2a9a2c2c03182c957aa5a56fca1cc8d9ec1f/django_extensions/__init__.py#L5))

A potential fix could be to wrap the call to `app.get_version` in a try..catch block but I am not sure it is the nicest way to go.

Many thanks for the great work on djtoolbar,

**Comment by liavkoren** [comment]
By randomly trying various combos, I found that debug toolbar v1.6 and dj extensions 2.0.8 work together.

**Comment by matthiask** [comment]
It's not my itch to scratch but I'd certainly review (& merge) a pull request fixing this.

**Comment by Atala** [comment]
Actually it is fixed in djangodebug-toolbar 2.0 ([ref](https://github.com/jazzband/django-debug-toolbar/blob/2.0/debug_toolbar/panels/versions.py#L52-L58)), so not a problem anymore !

Closing, feel free to reopen if needed.
