### ISSUE TITLE
Ability to run in production environment via url param/cookie

### ISSUE THREAD

**Issue by brianmoran** [jazzband/django-debug-toolbar#1200]
I apologize in advance if this has already been requested.

Troubleshooting an issue in production (especially SQL) could be made easier if there was a way to pass in a url param and/or cookie to display the debug toolbar. This would be more of an override flag to the `DEBUG` flag in `settings.py`.

**Comment by matthiask** [comment]
You should set `SHOW_TOOLBAR_CALLBACK` to a custom function of yours which implements the behavior you're describing if the default behavior isn't what you need (https://github.com/jazzband/django-debug-toolbar/blob/ce8034cd9001712f6d548db0356ce1c71a33176c/debug_toolbar/middleware.py#L17-L24)

https://django-debug-toolbar.readthedocs.io/en/latest/configuration.html#toolbar-options

**Comment by brianmoran** [comment]
Thanks so much!
