### ISSUE TITLE
No SQL trace for swagger requests

### ISSUE THREAD

**Issue by winmasta** [jazzband/django-debug-toolbar#1204]
We use django as swagger API and have djangorestframework, django-rest-swagger and drf-yasg installed. In the debug panel we can see only django SQL queries like ```SELECT * FROM django_session``` or ```SEECT * FROM user``` but there is no any queries when we try to GET or POST our endpoints which exactly makes SQL query. Where can be the problem or how can we debug it ?

**Comment by matthiask** [comment]
DDT only shows an SQL trace for the current request. Calls to DRF APIs are separate requests which would need some capturing of their own.

Maybe logging SQL queries to the console is an option for you?
https://avilpage.com/2018/05/django-tips-tricks-log-sql-queries-to-console.html

**Comment by winmasta** [comment]
Ok got it thanks for link.

**Comment by Elyasomer** [comment]
`DEBUG_TOOLBAR_CONFIG = {
    "UPDATE_ON_FETCH": True
}`

This helped me
