### ISSUE TITLE
The panel API is not included in the rendered documentation

### ISSUE THREAD

**Issue by living180** [jazzband/django-debug-toolbar#1205]
The source for the `panels.html` documentation page includes a section for the `Panel` API (https://github.com/jazzband/django-debug-toolbar/blame/5299cf826284b6e082c5f18050e4f706faa81c39/docs/panels.rst#L307).  I remember referencing this API in a previous version of the documentation, but in the current version of the documentation at Read the Docs it is blank:  https://django-debug-toolbar.readthedocs.io/en/stable/panels.html#api-for-third-party-panels.

Looking at the logs for the latest document build on Read the Docs (https://readthedocs.org/projects/django-debug-toolbar/builds/9803859/), I noticed the following warning:

```
WARNING: autodoc: failed to import class u'panels.Panel' from module u'debug_toolbar'; the following exception was raised:
cannot import name lru_cache
```

From looking elsewhere in the logs, it appears that Read the Docs is using Python 2.7 to build the docs, while `lru_cache` was added in Python 3.2.  The fix is probably just to update Read the Docs to use Python 3, but as there is no `readthedocs.yml` file in the repo, I think this change will have to be made using the Read the Docs admin panel.

**Comment by matthiask** [comment]
I just changed the settings. A build is running now.

**Comment by living180** [comment]
Fixed now, thanks!
