### ISSUE TITLE
Missing toolbar when using DRF PATCH form

### ISSUE THREAD

**Issue by thomas-riccardi** [jazzband/django-debug-toolbar#1207]
DRF auto html views + debug-toolbar is a great combo to debug sql performance for GET requests.
However, when doing PATCH requests (using the same DRF auto html view: raw form) the toolbar disappears, and I cannot analyze sql queries.

It would be great to be able to analyze sql queries with DRF PATCH forms too.

**Comment by tim-schilling** [comment]
The toolbar currently doesn't support ajax requests out of the box. You'll need to use a third party panel to get that view. I tested it with https://github.com/djsutho/django-debug-toolbar-request-history and verified that the put and patch requests are indeed logged by it.

**Comment by tim-schilling** [comment]
Closing this issue in favor of #1066
