### ISSUE TITLE
Current 2.1 version doesn't support Django 1.11 

### ISSUE THREAD

**Issue by mohammadrabetian** [jazzband/django-debug-toolbar#1213]
In the docs it's been said "The current stable version of the Debug Toolbar is 2.1. It works on Django ≥ 1.11." which means it should support 1.11 but it doesn't. simply because the MIDDLEWARE in settings file is written like MIDDLEWARE_CLASSES by the old style. in the debug_toolbar/apps.py line 25 the codes it's using MIDDLEWARE 

` for i, middleware in enumerate(settings.MIDDLEWARE):`

**Comment by mohammadrabetian** [comment]
I looked at the 1.11 version which works. 

`   setting = getattr(settings, "MIDDLEWARE", None)
    setting_name = "MIDDLEWARE"
    if setting is None:
        setting = settings.MIDDLEWARE_CLASSES
        setting_name = "MIDDLEWARE_CLASSES"`

**Comment by mohammadrabetian** [comment]
I would like to help and fix this issue if you allow me.

**Comment by tim-schilling** [comment]
@mohammadrabetian This was disabled as a part of #1140. I don't think we will want to add support for that deprecated setting, especially when Django's end of support for 1.11 is in April. I think having a warning about the incompatible setting would be a nice addition. A PR would be appreciated.
