### ISSUE TITLE
SQL panel: timing for each query not being displayed

### ISSUE THREAD

**Issue by kpagcha** [jazzband/django-debug-toolbar#1227]
I'm using version 1.3 with Django 1.8. Query timings used to be display for each one of them, but now it only displays the sum of all.

**Comment by matthiask** [comment]
Both Django 1.8 and django-debug-toolbar 1.3 are unsupported. I'm afraid you're on your own here.

**Comment by tim-schilling** [comment]
Closing as this is a support request for unsupported versions.
