### ISSUE TITLE
The toolbar isn’t displaying when using gzip.

### ISSUE THREAD

**Issue by sezgineray** [jazzband/django-debug-toolbar#1228]
We had to look hard to find why the toolbar was showing on some views but not on others. After a lot of effort we realized it was becouse of gzip. In the documentation's Tips part you can add this to reasons why toolbar wouldn't show up. It can make it a lot easier for some people.

**Comment by tim-schilling** [comment]
This is mentioned in the middleware section on the Installation docs. https://github.com/jazzband/django-debug-toolbar/blob/master/docs/installation.rst#enabling-middleware

**Comment by tim-schilling** [comment]
I'm closing this as the tips section already mentions the middleware as potential gotcha.
