### ISSUE TITLE
debugsqlshell no longer showing sql after upgrade

### ISSUE THREAD

**Issue by dee0** [jazzband/django-debug-toolbar#1231]
[requirements-django-3.0.txt](https://github.com/jazzband/django-debug-toolbar/files/4055733/requirements-django-3.0.txt)
[requirements-before-django-3.0.txt](https://github.com/jazzband/django-debug-toolbar/files/4055734/requirements-before-django-3.0.txt)

We are using postgres 12 and python 3.8.   

A couple of days ago we updated to Django 3.0 from 2.2.6 and we just noticed that the debugsqlshell is no longer showing us the SQL used for db queries.

The attached files show the before and after of the library upgrade we performed.

Note that
- We aren't seeing any error messages in the shell.   It is just the case that the SQL isn't displaying
- The debug toolbar _does_ show the SQL for db queries
- If we switch from postgres to sqlite, debugsqlshell _does_ show the SQL
   ( This isn't something we can rely on because a significant amount of our code relies on postgres specific features )
- I have attempted to just downgrade psycopg2 however it seems there is some sort of psycopg2 bug that prevents the downgrade from succeeding.

Any help would be appreciated.

**Comment by tim-schilling** [comment]
This will be fixed with #1226

**Comment by dee0** [comment]
Thanks!

**Comment by tim-schilling** [comment]
DDT 2.2 now supports this.
