### ISSUE TITLE
400 bad request with nginx / gunicorn

### ISSUE THREAD

**Issue by travis-st** [jazzband/django-debug-toolbar#1235]
I've looked through the old issues and everything I can find on Stackoverflow. I've made the changes that seem to work for everyone to nginx configuration. 

I can't isolate where the 400 error is being thrown - it's not from template_source(). The toolbar works fine in runserver mode, but doesn't work in gunicorn. 

Django version 1.11.3
Nginx 1.16.1
Gunicorn 19.7.1

Nginx settings:

```
    location @proxy_to_app {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header Host $host;
      proxy_buffering off;
      proxy_redirect off;
      proxy_read_timeout 200;
      proxy_pass http://localhost:8000;
    }
```
Any suggestions?

**Comment by tim-schilling** [comment]
Can you give us more details on what your test scenario? What action is resulting in a 400?

**Comment by travis-st** [comment]
All page loads that should show the toolbar result in 400. 

```
DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': 'shippingtree.settings.show_toolbar',
}

```

Anytime show_toolbar returns True - a 400 status is returned. 

Is there anything I can to do provide more info? Am happy to help debug this from my end. 

I've tried reordering the placement of `debug_toolbar.middleware.DebugToolbarMiddleware` in the middleware array as well, no luck.

**Comment by tim-schilling** [comment]
Which version of DDT are you using? Did you correctly configure the urls, INTERNAL_IPS, and middleware according to the [docs](https://django-debug-toolbar.readthedocs.io/en/latest/installation.html)? Also, please include the request headers and body as well as the responses? Filter out any sensitive information.

**Comment by travis-st** [comment]
Yep -I configured the URLs and INTERNAL_IPS. Middleware is configured. What is DDT? Googled it - I didn't see anything relevant. Data Driven Tests?

Everything works when I run Django from: `./manage.py runserver`, but when I launch the project from Gunicorn, the 400 error happens when `show_toolbar` returns `True`.

Request headers:

```
GET /warehouse/dashboard?toolbar=1 HTTP/1.1
Host: ####
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Sec-Fetch-User: ?1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: ######
```

Response headers:

```
HTTP/1.1 400 Bad Request
Server: nginx/1.16.1
Date: Tue, 04 Feb 2020 17:11:16 GMT
Content-Type: text/html
Content-Length: 26
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
Vary: Cookie
Set-Cookie: csrftoken=#####
```

Response body: 

`<h1>Bad Request (400)</h1>`


It might be worth noting that when we load a URL without "?toolbar=1" so the toolbar isn't requested, it takes less than a second to generate the page. With "?toolbar=1" it takes nearly 9 seconds but ultimately returns the 400 response. So something is going on. :)

**Comment by tim-schilling** [comment]
Heh, sorry. DDT == Django Debug Toolbar.

**Comment by tim-schilling** [comment]
Please include your middleware settings.

**Comment by travis-st** [comment]
Lol! My bad. 

`django-debug-toolbar==2.2`

```
MIDDLEWARE = [
    'dogslow.WatchdogMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'request_logging.middleware.LoggingMiddleware',
    'crequest.middleware.CrequestMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware'
]

```

Unless debug_tool bar is the very last item in the list, I get:
```
WARNINGS:
?: (debug_toolbar.W001) debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
	HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.
```

**Comment by tim-schilling** [comment]
Is `DEBUG` set to True? If not, can you clone your project to another production-like environment and set it to True to see if that gives you more information?

**Comment by travis-st** [comment]
Ok!

I got an error, that I don't really understand. 

```
SuspiciousFileOperation at /warehouse/dashboard
The joined path (/img/header-logo-2x.png) is located outside of the base path component (/home/ec2-user/our-project/project/static/assets)
```

I switched the HTML from:

```
<img src="{% static '/img/header-logo-2x.png' %}" style="width:138px;"/>
```

to

```
<img src="/static/img/header-logo-2x.png" style="width:138px;"/>
```

and it fixed the problem. The toolbar works now even with `DEBUG = True`.

debug_toolbar/panels/staticfiles.html was throwing the error:

```
<dd><samp>{{ staticfile.real_path }}</samp></dd>
```

The SuspiciousFileOperation problem is outside the scope of this issue of course. I will have to look into that, I don't understand what problem it's referring to. 

Thanks!

**Comment by tim-schilling** [comment]
Seems like there may be a configuration issue for your static files on your production site. I'm going to go ahead and close this since it doesn't seem to be a toolbar issue.

**Comment by travis-st** [comment]
Awesome, thanks for the help. This issue may help someone else with the same problem in the future.

**Comment by matthiask** [comment]
The argument to {% static %} should generally be a relative path, but a path starting with a slash. "img/...", not "/img/...". Maybe that's part of the problem here?
