### ISSUE TITLE
Provide a way to uncheck all checkboxes at once

### ISSUE THREAD

**Issue by Flimm** [jazzband/django-debug-toolbar#1238]
The Django side-bar provides a list of checkboxes, most of which are ticked by default:

- Versions
- Time
- Settings
- Headers
- Request
- SQL
- Static files
- Templates
- Cache
- Signals
- Logging
- Intercept redirects
- Profiling

Some of these things can slow down the time it takes for the response to return. For this reason, I often find myself wanting to untick all the checkboxes. This is a laborious process.

Every time I restore the database from backup, I need to re-do this process again.

**Comment by leandrodesouzadev** [comment]
@Flimm  Wouldn't the [`DISABLE_PANELS`](https://django-debug-toolbar.readthedocs.io/en/latest/configuration.html#toolbar-options) configuration do the job for you?

**Comment by Flimm** [comment]
> @Flimm Wouldn't the [`DISABLE_PANELS`](https://django-debug-toolbar.readthedocs.io/en/latest/configuration.html#toolbar-options) configuration do the job for you?

That does seem to work, thank you! Here is the configuration that I used:

```python
DEBUG_TOOLBAR_CONFIG = {
    'DISABLE_PANELS': {
        'debug_toolbar.panels.history.HistoryPanel',
        'debug_toolbar.panels.versions.VersionsPanel',
        'debug_toolbar.panels.timer.TimerPanel',
        'debug_toolbar.panels.settings.SettingsPanel',
        'debug_toolbar.panels.headers.HeadersPanel',
        'debug_toolbar.panels.request.RequestPanel',
        'debug_toolbar.panels.sql.SQLPanel',
        'debug_toolbar.panels.staticfiles.StaticFilesPanel',
        'debug_toolbar.panels.templates.TemplatesPanel',
        'debug_toolbar.panels.cache.CachePanel',
        'debug_toolbar.panels.signals.SignalsPanel',
        'debug_toolbar.panels.logging.LoggingPanel',
        'debug_toolbar.panels.redirects.RedirectsPanel',
        'debug_toolbar.panels.profiling.ProfilingPanel',
    },
}
```

I found the list of panels here: https://django-debug-toolbar.readthedocs.io/en/latest/panels.html

**Comment by tim-schilling** [comment]
@Flimm what's the purpose behind this? Please don't install the toolbar in a production environment even if all the panels are disabled. As a reminder, the toolbar does some monkey patching that gets applied regardless if it's imported (logging panel).

**Comment by Flimm** [comment]
The debug toolbar significantly slows down the response on my developer machine, especially when there are many database queries. That's why I wanted to disable the slow panels.

You say that django-debug-toolbar in a production environment should not even be installed. Do you mean even just doing `pip install django-debug-toolbar` can cause security vulnerabilities, even if it is not included in `INSTALLED_APPS` ? How does it do monkey-patching without even being imported? If what you are saying is true, I think [the installation instructions](https://django-debug-toolbar.readthedocs.io/en/latest/installation.html) should mention that.

**Comment by tim-schilling** [comment]
> Do you mean even just doing pip install django-debug-toolbar can cause security vulnerabilities, even if it is not included in INSTALLED_APPS?

No, the code needs to be imported into your project. So if it's added in the INSTALLED_APPS, MIDDLEWARE, urls.py.

**Comment by Flimm** [comment]
Thanks. Either way, [the installation instructions](https://django-debug-toolbar.readthedocs.io/en/latest/installation.html) do not make it clear. They do not say that `debug_toolbar` should not be installed in `INSTALLED_APPS` in production. According to your advice, the instructions should actually recommend code like this:

```python
if os.environ.get('IN_PRODUCTION'):
    INSTALLED_APPS.append('debug_toolbar')
    MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")
```

and in `urls.py`:

```python
if os.environ.get('IN_PRODUCTION'):
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
```

**Comment by tim-schilling** [comment]
You're right. We should get that changed as a part of #1435.
