### ISSUE TITLE
Regression: Broken inline styles with CSP

### ISSUE THREAD

**Issue by xi** [jazzband/django-debug-toolbar#1248]
The `applyStyle()` function that was removed as "unnecessary" in #1220 had actueally been added in #704 to fix issues with CSP. I suggest to revert #1220.

**Comment by matthiask** [comment]
Oh, that was unintentional. Maybe there's a way to avoid the need for inline styles with more CSS classes?

**Comment by xi** [comment]
Unfortunately it's not that simple. The inline styles are used mostly for cases where there are many potential values, e.g. the width and offset of bar charts.

See #1249 for a partial solution. I still think a proper fix involved reverting #1220.
