### ISSUE TITLE
Discussion - Enable selenium in Travis tests

### ISSUE THREAD

**Issue by tim-schilling** [jazzband/django-debug-toolbar#1251]
Looking for feedback on whether or not we should enable selenium tests in Travis. I think there's added value in having them run with the latest versions of python and django. From what I can tell they have never been enabled to run on Travis.

**Comment by matthiask** [comment]
If the selenium tests don't prove to be too flaky on Travis CI and if we do not enable "too many" of them I don't see a problem. 

Maybe just enable selenium for a single build job? What do you think?

**Comment by tim-schilling** [comment]
Hmm, I need to determine what the threshold of flakiness is for the selenium tests, but I'm happy if we only enable them for the latest stable version of Django.

I know there's a broken test for one of them, I'll fix/remove that and open a PR.

**Comment by matthiask** [comment]
That would be awesome, thanks in advance!

**Comment by tim-schilling** [comment]
Did you have a preference for which DB it should be enabled for out of sqlite, postgres, maria?

**Comment by matthiask** [comment]
No, what is easiest to get running. I think it might be postgres, since IIRC sqlite doesn't play well with the `LiveServerTestCase`?

**Comment by matthiask** [comment]
Btw, thanks again for your efforts. I'm sometimes doubting my [rules](https://406.ch/writing/my-rules-for-releasing-open-source-software/), especially when breaking others' code so quickly. A good testsuite is the A and O of maintenance.
