### ISSUE TITLE
<script> tags are not executed in Firefox 75

### ISSUE THREAD

**Issue by tleb** [jazzband/django-debug-toolbar#1264]
Wanting to try out [djdt-flamegraph](https://github.com/23andMe/djdt-flamegraph), I fall onto a bug.

The issue is that `<script>` tags loaded for panels are not executed (but included in the DOM). The function responsible for this is [`$$.executeScripts`](https://github.com/jazzband/django-debug-toolbar/blob/master/debug_toolbar/static/debug_toolbar/js/toolbar.js). I modified it getting inspiration from [StackOverflow](https://stackoverflow.com/questions/6432984/how-to-add-a-script-element-to-the-dom-and-execute-its-code), the following implementation works in my case:

```javascript
executeScripts: function(root) {
    root.querySelectorAll('script').forEach(function(e) {
        var clone = document.createElement('script');
        try {
            clone.appendChild(document.createTextNode(e.innerHTML));
        } catch (e) {
            clone.text = e.innerHTML;
        }
        root.appendChild(clone);
    });
},
```

I wanted other opinions before sending a pull request. I did not see another linked issue, is this recent? Does it concern other browsers? Will this solution be cross-browser?

**Comment by matthiask** [comment]
I'm not sure why this worked before and doesn't anymore.

However, the upcoming version of django-debug-toolbar contains #1282; panels are now supposed to deliver JSON, not HTML blobs. So, you should probably submit a PR to djdt-flamegraph not to django-debug-toolbar, except if it turns out that the upcoming panel API is insufficient.

**Comment by jdufresne** [comment]
The "Time" panel is a working example that execute scripts on load.

Closing as the `executeScripts` function has changed significantly since this was reported and this looks like it may be an issue in flamegraph. Please reopen if you can provide details that demonstrate otherwise. Thanks.
