### ISSUE TITLE
 时间模块不能用

### ISSUE THREAD

**Issue by lanheader** [jazzband/django-debug-toolbar#1265]
![image](https://user-images.githubusercontent.com/52522047/81471433-abad6680-9223-11ea-9c8b-f8d8a7750800.png)

**Comment by jdufresne** [comment]
I aplogize, but I'm not clear what the issue being reported is. Can you write English or do you have a colleague that could translate the request to English with more detail? Please reopen if you can provide additional information.

**Comment by lanheader** [comment]
the moudle is not working call time,because it is not a button.
