### ISSUE TITLE
django-debug-toolbar with PyCharm Professional 2020.2

### ISSUE THREAD

**Issue by pandichef** [jazzband/django-debug-toolbar#1302]
I've been using django-debug-toolbar with PyCharm's debugger recently.  Separately, they work just fine.  But when I use them together, run time is unbearably slow.  Has anyone else encountered this?  Are there any known solutions?  Thanks!

**Comment by mikekeda** [comment]
It works fine for me
Are you using "Debug"?
Are you using any external panels?

**Comment by pandichef** [comment]
What do you mean by "Debug"?   I'm not using any external panels.

**Comment by tim-schilling** [comment]
Does the web app run slowly with the toolbar enabled for these same paths?

**Comment by pandichef** [comment]
I'm not quite sure what you mean.  It seems to be a multiplicative effect.  toolbar slows startup by ~3x.  Pycharm debugger slows startup by ~3x.  Together, startup time is ~9x slower.  For now, I set up two Pycharm "configurations" and just toggle between them.  It works but it's hardly ideal.

**Comment by tim-schilling** [comment]
Can you reproduce it in a smaller project?

**Comment by tim-schilling** [comment]
I'm closing this issue in favor of #1308 as it has more details.
