### ISSUE TITLE
LICENSE file is not included in PyPI release

### ISSUE THREAD

**Issue by johnthagen** [jazzband/django-debug-toolbar#1305]
This should be addressed by:

https://github.com/jazzband/django-debug-toolbar/blob/e3a075834fa189cba1fb9ec9255704e8e977dc6b/setup.cfg#L11

But just wanted to raise the issue that currently no `LICENSE` file is included in the published `.whl` file. If the latest version of `wheel` is used when building the next `.whl` release, this issue should be resolved when that is published.

Tools such as [`pip-licenses`](https://github.com/raimon49/pip-licenses) use the LICENSE file included in uploaded Python packages to generate license reports.

**Comment by johnthagen** [comment]
I noticed there are some alpha releases (e.g. [3.0.0a2](https://pypi.org/project/django-debug-toolbar/3.0a2/#files)) was able to confirm the LICENSE file is properly included in those, so this issue should be good to be resolved once 3.0 is released.

**Comment by jdufresne** [comment]
3.0 (and more) release. The .tar.gz and the wheel both contain the license file. So I think this can be considered solved.
