### ISSUE TITLE
`debug-toolbar` for frontend development

### ISSUE THREAD

**Issue by psacawa** [jazzband/django-debug-toolbar#1313]
Hi, and thank you all for developing this fundamental django app.

I am wondering if any one has found a good way to use debug toolbar when django plays the role of the application backend, and gets accessed only via AJAX. Because the backend returns only JSON, you can't render the panels for each request. I was thinking of augmenting the middleware to store the request data in a cache, and create a separate view to display the list of recent requests to the backend in isolation.

I am interested in hearing how have people addressed this situation in the past. The documentation and other issues don't suggest anything about this. At least when I try to manually access `__debug__`, no match is found. Thank you.

**Comment by tim-schilling** [comment]
This has been added to the repository in #1250, but hasn't been released yet. 

Closing this issue in favor of #1032 and #998.
