### ISSUE TITLE
Script loading failure from djdt 3.0

### ISSUE THREAD

**Issue by tari** [jazzband/django-debug-toolbar#1336]
Using Django 3.1, I've fount that django-debug-toolbar>=3.0 fails to load scripts and the toolbar doesn't show up at all when running a local development server (`manage.py runserver`).

Firefox (81.0) has this error message in the console, and Chrome 87 seems to have the same issue:
```
Loading module from “http://localhost:8000/static/debug_toolbar/js/toolbar.js” was blocked because of a disallowed MIME type (“text/plain”).
````

I can work around it by [setting the MIME type for .js files manually](https://stackoverflow.com/a/16355034/2658436), but it seems like this should either be documented or automatically worked around.

**Comment by matthiask** [comment]
Hi @tari 

Thanks for the report. This sounds like an issue with Django or even with your development environment, and is probably not specific to django-debug-toolbar? I just checked and the runserver in my current project delivers JS with the correct `application/javascript` content type...

**Comment by tari** [comment]
Seems like it's Windows-specific, since I can't reproduce this on Linux (Python 3.8 for both).

I guess it's related to where `mimetypes` gets its data from by default.

**Comment by tari** [comment]
So Python loads MIME types from the registry (`HKEY_CLASSES_ROOT`) on Windows, and `.js` is defined as `text/plain` there. Based on the programs registered to open js files, this may have been set up by VS Code or Visual Studio.

It looks like there's no MIME type configured in Windows by default, since there isn't a `Content Type` key for .js when I load up a Windows sandbox.

---

I'm not sure what (if anything) could be done about this, since it's a deep platform issue. I also found [an old Go bug](https://github.com/golang/go/issues/32350) around the same problem. I can fix it on this machine by setting `HKEY_CLASSES_ROOT\.js\Content Type` to `text/javascript`.

**Comment by matthiask** [comment]
I think that the Django maintainers may be sympathetic towards adding some code to work around limitations when developing on Windows. I think you should open a ticket at https://code.djangoproject.com/ticket/ (I checked and didn't find an existing ticket) and propose a code change in Django itself.

My current thinking is that we shouldn't add code to django-debug-toolbar to fix this. It should be fixed, but not in django-debug-toolbar.

**Comment by tari** [comment]
Sounds reasonable. I've filed [Django ticket #32041](https://code.djangoproject.com/ticket/32041) about this so I'll close this issue and reopen if I think it warrants further discussion here later.

**Comment by matthiask** [comment]
I've seen that the Django ticket has been closed as well. 

I understand the argument raised by Mariusz, it's the same argument for not fixing it in django-debug-toolbar after all.

JavaScript not working by default on Windows when served by the Django development server is really unfriendly to beginners though, so – if you want to – you could raise the issue on the [django-developers](https://groups.google.com/g/django-developers) mailing list or [in the forum](https://forum.djangoproject.com/) if you prefer that, arguing that `runserver` should serve correct mimetypes by default on Windows too. At the very least it would be worth it adding a note to the documentation on installing Django on Windows (https://docs.djangoproject.com/en/3.1/howto/windows/).

(By the way, I'm working on Windows right now too, but inside WSL/2, so I'm sympathetic but not affected directly.)

**Comment by tari** [comment]
That's rather frustrating. I've solicited opinions on working around the problem (it's Windows at fault here!) on the mailing list. Seems like it may have been held for moderation since I don't see it on the web yet.

I appreciate the moral support. 😃

**Comment by matthiask** [comment]
Yes that may happen. Hopefully moderators will clear your message soon :)

**Comment by matthiask** [comment]
The documentation patch has landed in Django, yay :) https://github.com/django/django/commit/f87b0ecd37e64e7a019d472de37d0789a8790f1f

**Comment by AlekseiKhatkevich** [comment]
> Using Django 3.1, I've fount that django-debug-toolbar>=3.0 fails to load scripts and the toolbar doesn't show up at all when running a local development server (`manage.py runserver`).
> 
> Firefox (81.0) has this error message in the console, and Chrome 87 seems to have the same issue:
> 
> ```
> Loading module from “http://localhost:8000/static/debug_toolbar/js/toolbar.js” was blocked because of a disallowed MIME type (“text/plain”).
> ```
> 
> I can work around it by [setting the MIME type for .js files manually](https://stackoverflow.com/a/16355034/2658436), but it seems like this should either be documented or automatically worked around.



> Using Django 3.1, I've fount that django-debug-toolbar>=3.0 fails to load scripts and the toolbar doesn't show up at all when running a local development server (`manage.py runserver`).
> 
> Firefox (81.0) has this error message in the console, and Chrome 87 seems to have the same issue:
> 
> ```
> Loading module from “http://localhost:8000/static/debug_toolbar/js/toolbar.js” was blocked because of a disallowed MIME type (“text/plain”).
> ```
> 
> I can work around it by [setting the MIME type for .js files manually](https://stackoverflow.com/a/16355034/2658436), but it seems like this should either be documented or automatically worked around.

Hi.Sorry for asking. How exactly you fixed this with that stackowerflowanswer. Could you please provide a code snippet?

**Comment by tari** [comment]
I edited the registry as described [in my own answer](https://stackoverflow.com/a/64055514): set `HKEY_CLASSES_ROOT\.js\Content Type` to `text/javascript`.

**Comment by jpssantos** [comment]
> 
> 
> I edited the registry as described [in my own answer](https://stackoverflow.com/a/64055514): set `HKEY_CLASSES_ROOT\.js\Content Type` to `text/javascript`.

Thanks, works for me

**Comment by name-andy46** [comment]
> I edited the registry as described [in my own answer](https://stackoverflow.com/a/64055514): set `HKEY_CLASSES_ROOT\.js\Content Type` to `text/javascript`.

Hi, apologies for not complying with the Q&A guidelines here.
I'm just starting to learn django and I really would like to see the which queries are being executed through the toolbar.
I've already asked the [question](https://stackoverflow.com/questions/64984634/failed-to-load-module-script-the-server-responded-with-a-non-javascript-mime-ty) here.

Also edited the registry key as in the image below, but still cannot get the toolbar to show up.

![MimeType2](https://user-images.githubusercontent.com/65720058/100368654-ddecad00-3029-11eb-869c-782c827dbbb9.png)

Any possibility of solving this?
