### ISSUE TITLE
Toolbar.js error when clicking on the switch button from the History panel

### ISSUE THREAD

**Issue by KStenK** [jazzband/django-debug-toolbar#1337]
Hello,

There occurs some uncaught error in toolbar.js when I click on the "switch" button under the History panel.
Tried with Opera and Chrome.
Django debug toolbar version 3.1
Using default debug toolbar configurations.

![image](https://user-images.githubusercontent.com/53740661/94148154-ecc6b000-fe7e-11ea-83a2-6e5c4622ea5b.png)

Looks like a bug or some problem with my configuration?

**Comment by tim-schilling** [comment]
Can you get the `panelId` that's being used to create the query selector for me?

**Comment by KStenK** [comment]
I hope that is what you mean:
![image](https://user-images.githubusercontent.com/53740661/94160932-d83de400-fe8d-11ea-836f-22d4e7440fc2.png)

**Comment by tim-schilling** [comment]
Is there a Timer Panel for you in the toolbar? And can you verify that a div with the selector `.djdt-TimerPanel` exists on the page?

**Comment by tim-schilling** [comment]
Also, please include your configurations and your workflow to reproduce this issue.

**Comment by matthiask** [comment]
Ah right, I can reproduce this. b0ba22765999003428c21bbd52dc405df7c5244d this will be the problem.

Replacing `djDebug.querySelector('.djdt-'+panelId)` with `djDebug.querySelector('#djdt-'+panelId)` seems to fix it for me.

**Comment by tim-schilling** [comment]
@matthiask We should revisit #1251 as I think that would have caught this.

**Comment by KStenK** [comment]
> Ah right, I can reproduce this. [b0ba227](https://github.com/jazzband/django-debug-toolbar/commit/b0ba22765999003428c21bbd52dc405df7c5244d) this will be the problem.
> 
> Replacing `djDebug.querySelector('.djdt-'+panelId)` with `djDebug.querySelector('#djdt-'+panelId)` seems to fix it for me.

Yes, that fixed for me too.

**Comment by matthiask** [comment]
@KStenK @tim-schilling 3.1.1 contains the fix referenced above.

**Comment by KStenK** [comment]
> @KStenK @tim-schilling 3.1.1 contains the fix referenced above.

Everything is working now via 3.1.1. Thanks ;)
