### ISSUE TITLE
toolbar.js was blocked because of a dissallowed MIME type ("text/plain")

### ISSUE THREAD

**Issue by JamieSharpe** [jazzband/django-debug-toolbar#1352]
Hello,

I have followed each step from [this guide](https://django-debug-toolbar.readthedocs.io/en/latest/installation.html).

However the toolbar will not appear.

Inspecting the HTML of a webpage when the django server is running in debug mode confirms that the panels are present; although hidden.

![image](https://user-images.githubusercontent.com/1139365/94402924-95695e00-0164-11eb-93e1-ae60374cc959.png)

Modifying the CSS confirms that the base panel can be displayed as well:

![image](https://user-images.githubusercontent.com/1139365/94403042-bf228500-0164-11eb-9f62-0bd92ffb4f37.png)

Django is returning a HTTP 200 status on the files required:

![image](https://user-images.githubusercontent.com/1139365/94403662-ab2b5300-0165-11eb-925e-67d07458222d.png)

I found that the problem lies with the javascript file was not loading due to it's MIME type:

![image](https://user-images.githubusercontent.com/1139365/94403835-e9287700-0165-11eb-8c47-8199716e1bc1.png)

I am able to resolve this by importing the javascript file directly within my own templates; Note that this is without the 'type="module"' attribute:

![image](https://user-images.githubusercontent.com/1139365/94404117-5e944780-0166-11eb-85fe-763e4fbd5fa8.png)

After reloading the webpage, the toolbar works as expected. This is only a temporary fix to the real issue which was intruduced at these commits [#1](https://github.com/jazzband/django-debug-toolbar/commit/54fc973c4fe5dd3289f619d28c285200de96b856#diff-acd782edde03ccd403a2a00b80e0ed64R6) and [#2](https://github.com/jazzband/django-debug-toolbar/commit/54fc973c4fe5dd3289f619d28c285200de96b856#diff-4f4a91c0e3639b7eb74d3dc23799f72dR4).

**Comment by JamieSharpe** [comment]
I am sorry for the duplicate. I should have searched beforehand.
Reading the previous issue comments and the django official ones, I can understand why this may not be resolved at the django level.

However, what if the filetype for the Javascript modules was changed from ".js" to ".mjs"?

This id documented, and encouraged by [Mozilla](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#Aside_%E2%80%94_.mjs_versus_.js) and [V8 engine](https://v8.dev/features/modules#mjs).

Changing the filenames from ".js" to ".mjs" resolves this issue when tested on Windows; which is where the problem lies. If it also works on a UNIX OS then I propose this is a solution.

**Comment by matthiask** [comment]
Since we're discussing moving to JavaScript modules (see #1350) that may be a viable solution to this problem.

On the other hand, a documentation patch just landed in the Django repository addressing the problem with Windows and JavaScript files https://github.com/django/django/commit/f87b0ecd37e64e7a019d472de37d0789a8790f1f

My `/etc/mime.types` file contains both js and mjs for `application/javascript` files so it should work. I think we should only use `*.mjs` if the content really is a JavaScript module though.
