### ISSUE TITLE
History panel: allow more content types (e.g. Excel spreadsheet)

### ISSUE THREAD

**Issue by raphaelmerx** [jazzband/django-debug-toolbar#1400]
## Description
The Debug Toolbar history pannel is very useful for AJAZ json requests. Unfortunately, it doesn't work for non-ajax, non-json requests - for example, a "Download data" button that downloads an Excel file generated on the fly. It would be great to tweak that, potentially through a configuration option.

## Example implementation

* Add a configuration option `CAPTURED_CONTENT_TYPES`, defaults to `["application/json"]`
* Can be extended in the settings
* In `middleware.py`:
```python
            if request.is_ajax() or content_type in self.config["CAPTURED_CONTENT_TYPES"]:
                toolbar.render_toolbar()
```

**Comment by tim-schilling** [comment]
The call to `is_ajax` was removed in #1382 which allows the toolbar to instrument almost all requests. The types of responses that aren't allowed are [visible here](https://github.com/jazzband/django-debug-toolbar/blob/master/debug_toolbar/middleware.py#L77-L84).

That PR hasn't been included in a released version yet, so if you need it immediately you'll need to install from source.

**Comment by tim-schilling** [comment]
Actually, I think the toolbar instruments all requests with 1382 now.
