### ISSUE TITLE
Error: <rect> attribute width: Expected length, "NaN%".

### ISSUE THREAD

**Issue by folt** [jazzband/django-debug-toolbar#1416]
In the loadEvent line, the width NaN in the Time tab

![Screenshot_20201202_125950](https://user-images.githubusercontent.com/3757488/100857997-722d9880-349e-11eb-91dd-8b755906728f.png)
![Screenshot_20201202_125928](https://user-images.githubusercontent.com/3757488/100857999-735ec580-349e-11eb-8795-97447ae6c22a.png)

**Comment by folt** [comment]
[(100.0 * width) / (100.0 - getLeft(stat))](https://github.com/jazzband/django-debug-toolbar/blob/master/debug_toolbar/static/debug_toolbar/js/timer.js#L12)

This line is divided by 0.
I suspect this is not good.

**Comment by tim-schilling** [comment]
We should review the JS and protect against all divisors (`getLeft` and `getCSSWidth`) possibly being set to zero. They should return zero in that case.
