### ISSUE TITLE
Cookie “djdt” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute.

### ISSUE THREAD

**Issue by beasyx0** [jazzband/django-debug-toolbar#1417]
Getting lots of random errors with the toolbar. One is the title the rest are in the screenshot. It looks like this year the browsers started getting really tight with security and that may be the cause. Figured I'd post this in case there may be a workaround. I didn't find much online except for the idea that I would have to change source code. Thanks.
![Screenshot from 2020-12-02 14-11-02](https://user-images.githubusercontent.com/59843326/100919768-3ac3e980-34a8-11eb-87fd-80ff4f5e8a53.png)

**Comment by beasyx0** [comment]
Looks like it fixed itself or I was losing my mind.

**Comment by matthiask** [comment]
I'm seeing this too. Thanks for the report :) PR incoming...
