### ISSUE TITLE
Unexpected token < in JSON when trying to load a panel

### ISSUE THREAD

**Issue by jshields** [jazzband/django-debug-toolbar#1422]
Migrating from django-debug-toolbar from 2.2 to 3.1.1
Django version: 3.1.1

When clicking onto a panel, the loading indicator runs forever due to an error in a JS promise.
The issue seems to be attempting to parse an HTML document as JSON.
I have verified that the latest `mime-support` package is installed on my Ubuntu container per https://django-debug-toolbar.readthedocs.io/en/latest/installation.html#troubleshooting and the other prerequisites should be complete.

https://github.com/jazzband/django-debug-toolbar/blob/master/debug_toolbar/static/debug_toolbar/js/toolbar.js#L43
The request is to `/__debug__/render_panel/?store_id=...&panel_id=SQLPanel`

The failing JSON parse is:
https://github.com/jazzband/django-debug-toolbar/blob/master/debug_toolbar/static/debug_toolbar/js/utils.js#L42

Setting a breakpoint at `return response.json();` and manually getting the value in the console:
```
response.text().then(function (text) {
  console.log(text);
});
```
I do get an HTML document beginning like this, which appears to be a JSON document rendered in an HTML page:
```
<html><body><pre>{
  "content": "\n<ul>\n  \n    <li>\n      <strong><span class=\"djdt-color\" style=\"background-color:rgb(256, 0, 0)\"></span> default</strong>\n      0.94 ms (3 queries\n      \n        including <abbr title=\"Similar queries are queries with the same SQL, but potentially different parameters.\">2 similar</abbr>\n        \n          and <abbr title=\"Duplicate queries are identical to each other: they execute exactly the same SQL and parameters.\">2 duplicates</abbr>\n        \n      )\n    </li>\n  \n</ul>\n\n\n  <table>\n    <thead>\n      <tr>\n        <th></th>\n        <th class=\"djdt-query\" colspan=\"2\">Query</th>\n        <th class=\"djdt-timeline\">Timeline</th>\n        <th class=\"djdt-time\">Time (ms)</th>\n
```
The opening left bracket from `<html>` is what leads to the error `Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0` from what I gather.

<img width="1678" alt="Screen Shot 2020-12-08 at 5 49 29 PM" src="https://user-images.githubusercontent.com/3101751/101555198-c09ad580-397d-11eb-8acf-d78ad59a9370.png">

**Comment by tim-schilling** [comment]
Can you see what the response type is in the network panel? Seems like the toolbar's returning it as a HTML response rather than a JSON response.

**Comment by jshields** [comment]
> Can you see what the response type is in the network panel? Seems like the toolbar's returning it as a HTML response rather than a JSON response.

@tim-schilling At the line where `response.json()` is called, [`response.headers`](https://developer.mozilla.org/en-US/docs/Web/API/Response/headers) is empty (`Headers {}`). The route configuration for the `__debug__` endpoint being hit looks like:
```
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ]
```
(Changing this to `path('__debug__/',...)`as in [the docs](https://django-debug-toolbar.readthedocs.io/en/latest/installation.html#setting-up-urlconf) does not have an effect, they are equivalent.)

I would assume the `debug_toolbar` module is responsible for setting response headers on this endpoint. I don't think our admin or API layers are doing anything weird with setting response headers. Not sure if this issue is reproducible on a totally fresh Django app though.

**Comment by tim-schilling** [comment]
I was actually hoping to see what the request and response headers are in the browser's developer tools.

**Comment by jshields** [comment]
Ah, yeah the response headers (copied from Chrome using right click -> copy response headers) indeed have `Content-Type: text/html; charset=utf-8`

Response headers:
```
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 14 Dec 2020 17:23:04 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
X-Frame-Options: DENY
Vary: Cookie, Origin
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin
Content-Encoding: gzip
```

The request doesn't expect any content type, it has `Accept: */*`
Request:
URL `http://localhost:8000/__debug__/render_panel/?store_id=7220dd51d6e44b168cd979cfc7bb594b&panel_id=SQLPanel`
Headers
```
GET /__debug__/render_panel/?store_id=7220dd51d6e44b168cd979cfc7bb594b&panel_id=SQLPanel HTTP/1.1
Host: localhost:8000
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Accept: */*
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost:8000/admin/(redacted)
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: (redacted)
```

**Comment by jshields** [comment]
Apologies, we have some middleware copied from https://stackoverflow.com/a/19249559/3538313 that is causing this:
```
response = HttpResponse('<html><body><pre>{}'
                                        '</pre></body></html>'.format(content))
```

Closing the issue.

**Comment by tim-schilling** [comment]
No problem, I'm glad you were able to figure it out!
