### ISSUE TITLE
Showing duplicate queries in some situations.

### ISSUE THREAD

**Issue by tolomea** [jazzband/django-debug-toolbar#1425]
The debug toolbar seems to double report the queries done by the drop down widget.
If you:

1: checkout this code https://github.com/tolomea/django-tutorial/tree/debug_toolbar_bug
2: migrate and create a super user
4: log into admin, create a simulation and a scenario that references the simulation

Then when viewing the scenario in the admin the toolbar will report 2 queries for django_session but only one will be shown on the console logging.

**Comment by jayaddison-collabora** [comment]
I'm not completely certain @tolomea, but from investigating a similar issue locally, this may be the same as #1239 (good news if so; there has been a fix merged for that).

**Comment by tolomea** [comment]
I'll have to remember to take a look at this again. I should probably have noted originally that this was on Postgres. Actually I was just generally a bit lax normally I'd at least include Django, Python and Debug Toolbar versions
