### ISSUE TITLE
gather information from async functions

### ISSUE THREAD

**Issue by smmoosavi** [jazzband/django-debug-toolbar#1430]
If some queries are executed in async mode, these queries are missing in the panel. How can we collect these?

```python
data = asyncio.run(parallel_calc_aggregations(queryset, aggregations))
```

**note1:** I am using `django-debug-toolbar` via [`django-graphiql-debug-toolbar`][django-graphiql-debug-toolbar]
**note2:** all queries are inside function wrapped by [`sync_to_async`][sync_to_async]

The same issue exists when graphql `ThreadExecutor` is used. read more about graphql executors [graphql-314]

[django-graphiql-debug-toolbar]: https://github.com/flavors/django-graphiql-debug-toolbar
[sync_to_async]: https://docs.djangoproject.com/en/3.1/topics/async/#asgiref.sync.sync_to_async
[graphql-314]: https://github.com/graphql-python/graphene/issues/314#issuecomment-251585796

**Comment by tim-schilling** [comment]
The toolbar currently does not support async and the collection of statistics is tightly coupled to a request. If you do end up diving into how to modify the toolbar to collect this information, we'd appreciate any conclusions or findings of yours.

**Comment by smmoosavi** [comment]
Is there any decorator function we can add around these functions and collect data required by debug-toolbar?

```python
@collect_toolbar_inf
def get_data():
  # pure django

async def async_get_data():
      return await sync_to_async(get_data, thread_sensitive=False)()

async def parallel_get_data():
  return await asyncio.gather(async_get_data(), async_get_data(), async_get_data())

data = asyncio.run(parallel_get_data())
```

**Comment by tim-schilling** [comment]
Currently the only API for collecting the data is done via the middleware and the methods on the panels themselves.

**Comment by smmoosavi** [comment]
maybe it's possible to wrap [`sync_to_async`][sync_to_async]. all async function using graphql orm should use this function and without `sync_to_async` function causing error.

[sync_to_async]: https://github.com/django/asgiref/blob/5b86d9684e1f3c28956fb0dfe8d4f4a427be8f87/asgiref/sync.py#L372

**Comment by tim-schilling** [comment]
@michaelurban that's a good idea. Or at least log some type of message. Would you be able to write up a PR to introduce that feature?
