### ISSUE TITLE
Improve control over when toolbar enables/disables tracking

### ISSUE THREAD

**Issue by sbroumley** [jazzband/django-debug-toolbar#1444]
First off thanks for this amazing tool! 
One thing I'm trying to do is control when djangotoolbar is actually profiling.

eg.
I have a web page that is broken into 2 parts: 
1) An api call with db processing
2) Front end view model building with db processing.

When I have the debugtoolbar active and I load the page, once finished the djangotoolbar always contains profiling for both parts 1) and 2) combined.
Ideally I'd like to place a python call in between 1) and 2) (eg. ```djangotoolbar_reset_history()``` or something similar) so that all profiling history is cleared and the final results are just for part 2).

For ultimate control having the following 3 functions would cover all needs so we can easily profile a single section of code:
```
djangotoolbar_reset_history()
djangotoolbar_stop_profiling()
djangotoolbar_start_profiling()
```
I've looked over the docs and searched online but I can't find any info on how to do this.

Is there currently anyway to do this? Or can someone point me to the associated code so I could implement?
thanks!
-Steve.

**Comment by tim-schilling** [comment]
Hi Steve,

So you don't need to use the toolbar to gather profiling information. You could use [`cProfile`](https://docs.python.org/3/library/profile.html) by itself. You can find the docs here.

If you're intent on integrating this with the toolbar, I would subclass the ProfilePanel and override [`process_request`](https://github.com/jazzband/django-debug-toolbar/blob/master/debug_toolbar/panels/profiling.py#L154-L156) that would add a callback to the request that would effectively call `profiler.runcall`.

Maybe something like this:

    def process_request(self, request):
        self.profiler = cProfile.Profile()
        request.djdt_profiler_runcall = self.profiler.runcall
        return super().process_request(request)


Then in your views you can define a helper function that will profile a function call based on the `DEBUG` setting and the existence of the profiler on the request. I wouldn't add this to a repo beyond trying to find a bottleneck.

```
def djdt_profile(request, func, **kwargs):
    if settings.DEBUG and hasattr(request, 'djdt_profiler_runcall'):
        return request.djdt_profiler_runcall(func, **kwargs)
    else:
        return func(**kwargs)

def my_view(request):
    # do unprofiled stuff
    # Profile a function call
    data = djdt_profile(request, api_func, **api_kwargs)
    # render view
```

I haven't tested any of that, so I'm not sure how it'll work. I'd suggest looking at the ProfilePanel in the toolbar and the documentation for profiling within python. Those might spur some other ideas for you.

**Comment by sbroumley** [comment]
Thanks for the info Tim!
I'm not sure I made myself quite clear, but by "profiling" I actually meant the full suite of what djangotoolbar captures (including all database queries etc), not just the cpu profiling.

**Comment by tim-schilling** [comment]
Ah, no. The toolbar does not support that out of the box. There is support for profiling the SQL queries via `django-admin debugsqlshell`

**Comment by sbroumley** [comment]
Thanks for the info Tim.  It sounds like I'll if to step into the guts of the code to get what I'm after.
Do you know if it's spread out across multiple systems? Ideally I just need a global on/off switch that all the separate profiling systems could test against before tracking data.

**Comment by tim-schilling** [comment]
The panels have `enable_instrumentation` and `disable_instrumentation` that theoretically would do you what you want. However, I'm not sure you'll be able to use them as they exist today because they weren't designed with that flow in mind. Or maybe they were, but over time their scope has been reduced to a single call per request via the toolbar's middleware. You'll likely need to dig into the project a bit to understand how things work and which aspects need tweaking.

**Comment by tim-schilling** [comment]
@sbroumley were you able to make any progress on this?
