### ISSUE TITLE
Change the default branch for the repository to main.

### ISSUE THREAD

**Issue by tim-schilling** [jazzband/django-debug-toolbar#1452]
I'd like to change the default branch from master to main. The Django community is an open and inclusive one, so this feels like a easy win to make our segment of the community more welcoming for many.

This [commit](https://github.com/jazzband/django-debug-toolbar/commit/18db3ac03ec3cdf59ed223658e8d93f5daffed15) makes the necessary changes to the repository, but there are a few other things that need to change:

- Transifex: We need to update the name of the resource there. I've added Matthias as a maintainer for the project. Going to the [resource](https://www.transifex.com/robhudson/django-debug-toolbar/master/), clicking on settings, then changing the name should suffice.
- GitHub: Need to change the default branch to main in the [settings](https://github.com/jazzband/django-debug-toolbar/settings/branches).
- ReadTheDocs: We may need to change the [default branch advanced setting in Read The Docs](https://readthedocs.org/dashboard/django-debug-toolbar/advanced/).

**Comment by matthiask** [comment]
Thanks for moving forwards with this!

I have changed the readthedocs configuration. I do not have access to GitHub settings either, that's only available to roadies. @jezdez May I ask you to help out here? Thanks in advance and sorry for bothering you.

Thanks for the Transifex invite! If you're able to make the change @tim-schilling please go ahead.

**Comment by tim-schilling** [comment]
> Thanks for the Transifex invite! If you're able to make the change @tim-schilling please go ahead.

This part has been completed.

**Comment by jezdez** [comment]
> Thanks for moving forwards with this!
> 
> I have changed the readthedocs configuration. I do not have access to GitHub settings either, that's only available to roadies. @jezdez May I ask you to help out here? Thanks in advance and sorry for bothering you.

No bother at all, I fully support this change and had it on my mind to do next for all repos. After the GitHub Actions move.. :)

**Comment by jezdez** [comment]
There is an existing `main` branch, I can't do the rename sadly. Is okay for me to delete the branch?

<img width="468" alt="CleanShot 2021-02-11 at 15 58 47@2x" src="https://user-images.githubusercontent.com/1610/107653535-0af04980-6c82-11eb-92bd-2e6fc23b3b6d.png">

**Comment by tim-schilling** [comment]
@jezdez Yes, go ahead. I'll clean up the commit issue after.

**Comment by jezdez** [comment]
<img width="462" alt="CleanShot 2021-02-11 at 16 02 08@2x" src="https://user-images.githubusercontent.com/1610/107653988-83570a80-6c82-11eb-9a5f-d070b6bcb045.png">

**Comment by tim-schilling** [comment]
Thank you both for the quick responses on this. I've pushed the commit with the reference changes to `main`.
