### ISSUE TITLE
When serving XSLX, toolbar breaks

### ISSUE THREAD

**Issue by ByteOven** [jazzband/django-debug-toolbar#1457]
Troubling part :
```            getattr(response, "streaming", False)
            or "gzip" in content_encoding
            or content_type not in _HTML_TYPES
        ):
            return response
        # Insert the toolbar in the response.
        content = response.content.decode(response.charset) …
        insert_before = dt_settings.get_config()["INSERT_BEFORE"]
        pattern = re.escape(insert_before)
        bits = re.split(pattern, content, flags=re.IGNORECASE)
        if len(bits) > 1:
            bits[-2] += rendered
            response.content = insert_before.join(bits)
```

```Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/export-xlsx/94/

Traceback (most recent call last):
  File "/home/bl4ck/Projects/admin-live/.env3/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/bl4ck/Projects/admin-live/.env3/lib/python3.9/site-packages/debug_toolbar/middleware.py", line 87, in __call__
    content = response.content.decode(response.charset)

Exception Type: UnicodeDecodeError at /kpir/export-xlsx/94/
Exception Value: 'utf-8' codec can't decode byte 0x81 in position 18: invalid start byte```


Troubling code in (Class based view) Views.py

```
        template = Template(join(dirname(__file__),'templates', 'income.xlsx'))
        workbook = template.fill(data)
        response = HttpResponse(content=save_virtual_workbook(workbook))
        response['mimetype']='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        response['Content-Disposition'] = 'attachment; filename=export.xlsx'
        return response
```

**Comment by matthiask** [comment]
The `mimetype` thing isn't supported by Django anymore (I think), so the probable reason for this is that your code is already buggy.

You should change the code to `response = HttpResponse(content=save_virtual_workbook(workbook), content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')`.

The toolbar shouldn't crash, though. So there is still a thing or two to fix.

**Comment by ByteOven** [comment]
Hey seems like you are right, haven't really read the docs, upgraded now an old project of mine, from 1.11 to 3.x (latest).

Will resolve this as invalid.

Thanks again for noticing the bug
