### ISSUE TITLE
Profiling panel empty (get_root_func does not find root function)

### ISSUE THREAD

**Issue by Natureshadow** [jazzband/django-debug-toolbar#1459]
In the AlekSIS project, we cannot get the Profiling panel to work. I tracked the issue down to `DjangoDebugToolbarStats.get_root_func` not finding the root function — all functions except the one containing the profiler have at least one caller.

As I do not really understand the mechanism here, there is not much more I can provide.

What I discovered on the way is that the people over at django-debug-toolbar-line-profiler discover the root functio na bit differently, and seem to have some more logic to track down the view function: https://github.com/dmclain/django-debug-toolbar-line-profiler/blob/master/debug_toolbar_line_profiler/panel.py

We are currently in a situation where profiling information is much needed to find a bottleneck in a production system, so any hints on how to make this work or work around it are welcome.

**Comment by tim-schilling** [comment]
@Natureshadow I'm closing this issue. Please re-open it if you can provide us with an example case. The code you reference that doesn't work doesn't exist in our repo.
