### ISSUE TITLE
Issue a new release?

### ISSUE THREAD

**Issue by danlamanna** [jazzband/django-debug-toolbar#1462]
There are features in the documentation that aren't in the latest release. In my case this is the `PRETTIFY_SQL` configuration option.

Can a new release be pushed to PyPI?

**Comment by tim-schilling** [comment]
Hi Dan, thank you for your contribution. We are working on a new release, please be patient with us for a bit longer.

**Comment by jezdez** [comment]
We've just made a number of releases that include an important security fix: https://github.com/jazzband/django-debug-toolbar/security/advisories/GHSA-pghf-347x-c2gj
