### ISSUE TITLE
Unexpected token < in JSON at position 1

### ISSUE THREAD

**Issue by Speedy2k** [jazzband/django-debug-toolbar#1469]
I was on Django 3.1.4 and with the latest version of django-debug-toolbar 3.2.1 and every time i try to open a panel in the toolbar, i got: Unexpected token < in JSON at position 1

I have tried to move the middleware declararion at all place possible with no changes. I have update my django to 3.2 with no change either.

Is there a good way to make that work ?

Thanx a lot!

**Comment by tim-schilling** [comment]
Hi @Speedy2k,

Where are you getting this error message? If it's a full 500 error in the browser, can you share the full stack trace?

If it's in the browser console tab, can you share that full stacktrace as well as the response in the networking tab that was attempted to be parsed into JSON?

**Comment by matthiask** [comment]
Maybe a duplicate of https://github.com/jazzband/django-debug-toolbar/issues/1422 ?

**Comment by Speedy2k** [comment]
I have found my problem! it was the position of the url in my url file!

Thanx a lot!

**Comment by ay1man4** [comment]
Yes, adding it to the top of urlpatterns solved the issue
