### ISSUE TITLE
[Bug] Toolbar handle can go out of window

### ISSUE THREAD

**Issue by rafaelurben** [jazzband/django-debug-toolbar#1471]
When changing from a bigger to a smaller screen, it can happen that the toolbar is out of the screen and therefore not clickable. It can be brought back by zooming out and moving the handle, but I think this shouldn't happen.

**Comment by matthiask** [comment]
@rafaelurben Thanks for the report. This has bothered me a few times too.

Do you want to attempt fixing this? Search `toolbar.js` for `djdt.top`. Things should be fixed after reloading but handling `resize` events on the `window` object would certainly be a good idea. Here's the code which handles the positioning on page load (I think): https://github.com/jazzband/django-debug-toolbar/blob/4e3d12f8581cc269cbfc7e912124746947da1d07/debug_toolbar/static/debug_toolbar/js/toolbar.js#L221-L228 . `djdt.top` isn't updated in the local storage on page load either so I think it's fine to skip this in the resize handler too.

**Comment by rafaelurben** [comment]
I'm sorry but I don't really have the time, setup and knowledge to fix this at the moment. 😞

**Comment by matthiask** [comment]
That's fine, this report motivated me to submit a pull request myself :)
