### ISSUE TITLE
Not a bug but a warning from Django

### ISSUE THREAD

**Issue by cnobile2012** [jazzband/django-debug-toolbar#1473]
I got this warning while running running `python -Wall manage.py runserver localhost:8000`.

.virtualenvs/dcolumn/lib/python3.8/site-packages/django/apps/registry.py:91: **RemovedInDjango41Warning**: 'debug_toolbar' defines default_app_config = 'debug_toolbar.apps.DebugToolbarConfig'. Django now detects this configuration automatically. You can remove **default_app_config**.

I'm the developer of `dcolumn` and was doing updates to my code when I found this.

**Comment by tim-schilling** [comment]
Thanks for the issue Carl. This has already been fixed in #1467 and is pending a release.
