### ISSUE TITLE
Setup pre-commit for repo

### ISSUE THREAD

**Issue by tim-schilling** [jazzband/django-debug-toolbar#1485]
To help lower barriers to contributing we should integrate [pre-commit](https://pre-commit.com/) to the project. The main use for us would be to run the linter before a commit occurs to help prevent failed tests when PRs are opened. While this does change the setup time, it does conform to a larger python practice. That conformity should theoretically be more accessible when compared to knowing to run `make styles` before committing.

**Comment by matthiask** [comment]
I don't use pre-commit much (we use custom hooks) but this definitely sounds like an excellent idea. django-debug-toolbar's `make` commands always give me a headache.

**Comment by tim-schilling** [comment]
Yeah, perhaps larger python practice isn't the right phrase. Growing is more appropriate.
