### ISSUE TITLE
Release the package with Django 3.2 support

### ISSUE THREAD

**Issue by Jawayria** [jazzband/django-debug-toolbar#1487]
Hey, we are working on upgrading edX codebase to Django 3.2. This package is being used in the codebase but it isn't yet released with Django 3.2 support. Kindly consider releasing it with Django 3.2 support.
Thanks

**Comment by tim-schilling** [comment]
Hi Jawayria, Django 3.2 should be supported since v3.2.0 for the toolbar. Is there a hurdle you're encountering?

**Comment by Jawayria** [comment]
Oh okay. Actually Django 3.2 isn't yet mentioned in setup.py so I thought may be work on Django3.2 support is in progress currently.

**Comment by tim-schilling** [comment]
Not a problem. It's in the [`setup.cfg` file](https://github.com/jazzband/django-debug-toolbar/blob/main/setup.cfg#L19). I'm going to go ahead and close this issue since it doesn't sound like it's causing a problem.
