### ISSUE TITLE
Unable to display details from django toolbar

### ISSUE THREAD

**Issue by manojsitapara** [jazzband/django-debug-toolbar#1499]
I am getting following error in my console window and not able to view any detail from Django Toolbar

`Uncaught (in promise) TypeError: Cannot read property 'remove' of null at toolbar.js:89`

![image](https://user-images.githubusercontent.com/12126671/132445969-34194018-6979-4b4c-aead-0698272b03b8.png)

I have highlighted error in below screenshot. Line number: 89

![image](https://user-images.githubusercontent.com/12126671/132454265-a3ff20b2-94d0-4b1c-bc23-42f598f402aa.png)

Here is my Middleware
> MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    # 'silk.middleware.SilkyMiddleware',
]

> DEBUG_TOOLBAR_PANELS = [
       'debug_toolbar.panels.versions.VersionsPanel',
       'debug_toolbar.panels.timer.TimerPanel',
       'debug_toolbar.panels.settings.SettingsPanel',
       'debug_toolbar.panels.headers.HeadersPanel',
       'debug_toolbar.panels.request.RequestPanel',
       'debug_toolbar.panels.sql.SQLPanel',
       'debug_toolbar.panels.staticfiles.StaticFilesPanel',
       'debug_toolbar.panels.templates.TemplatesPanel',
       'debug_toolbar.panels.cache.CachePanel',
       'debug_toolbar.panels.signals.SignalsPanel',
       'debug_toolbar.panels.logging.LoggingPanel',
       'debug_toolbar.panels.redirects.RedirectsPanel',
   ]

**Comment by matthiask** [comment]
This line of code is on line 45 in my local version of django-debug-toolbar. Maybe the JS files are outdated?

**Comment by manojsitapara** [comment]
@matthiask I have uninstalled Djago debug toolbar and reinstall with latest version.

Now I am getting following error in utils.js file at line no. 42

Uncaught (in promise) TypeError: scripts is undefined

![image](https://user-images.githubusercontent.com/12126671/132461268-81f7034d-7adf-42ec-a6a8-190dbfa06af1.png)


![image](https://user-images.githubusercontent.com/12126671/132461372-af7638cc-873e-4446-9617-d07d8908ef86.png)

**Comment by tim-schilling** [comment]
@manojsitapara looking at toolbar.js, [it tries to execute any scripts that are identified in the response from the server](https://github.com/jazzband/django-debug-toolbar/blob/main/debug_toolbar/static/debug_toolbar/js/toolbar.js#L47). Please inspect the response in the developer tools when you access the static files panel and compare that with the list of known issues ([here](https://django-debug-toolbar.readthedocs.io/en/latest/installation.html#troubleshooting) and [here](https://django-debug-toolbar.readthedocs.io/en/latest/tips.html#the-toolbar-isn-t-displayed)).

**Comment by manojsitapara** [comment]
@tim-schilling Thank you for response.

Response seems okay. I have attached the screenshot.

![image](https://user-images.githubusercontent.com/12126671/132519065-481b3cf4-4451-44a3-bf34-401ebace0cbf.png)

**Comment by tim-schilling** [comment]
The response body is the part we care about. It's not being being consumed
properly by the toolbar.js script.

**Comment by manojsitapara** [comment]
response body is always empty and I am not figuring out that what is the issue?

**Comment by manojsitapara** [comment]
I have figure it out the issue
I have created blank new Django project and installed django-debug-toolbar and it was working fine, by this I came to know that there must be something wrong my project.

Following package was causing the issue, after disabling module, django-debug-toolbar is started working fine.

> django_telegrambot

**Comment by tim-schilling** [comment]
@manojsitapara You could define a custom callback function for the `SHOW_TOOLBAR_CALLBACK` config setting that excludes the telegram bot requests, or whichever requests were having the problems.

**Comment by tim-schilling** [comment]
Presuming the issue is surrounding those requests and not something else.
