### ISSUE TITLE
Unexpected token < in JSON at position 1

### ISSUE THREAD

**Issue by dtanhphuong1189** [jazzband/django-debug-toolbar#1503]
I have an issue, whenever I click on SQL (any field), it shows error "Unexpected token < in JSON at position 1"

![image](https://user-images.githubusercontent.com/87709083/133990627-b62e5d75-3c3f-4d0b-84fa-488f7bd9a5ff.png)

When I run python manage.py runserver, I got the error
WARNINGS:
?: (debug_toolbar.W004) debug_toolbar is incompatible with MIDDLEWARE_CLASSES setting.
HINT: Use MIDDLEWARE instead of MIDDLEWARE_CLASSES

This is the first time, I've use debug toolbar and django. Please help me

**Comment by matthiask** [comment]
You are using Django 3.1 which doesn't support the `MIDDLEWARE_CLASSES` setting. Django 2.0 removed support for it.

You should follow the newer installation instructions at https://django-debug-toolbar.readthedocs.io/en/latest/installation.html
