### ISSUE TITLE
DDT does not trace the internal app request time

### ISSUE THREAD

**Issue by moghadas76** [jazzband/django-debug-toolbar#1504]
Intended to tracing, we could not trace and benchmark internal request delays between subsystems

**Comment by matthiask** [comment]
I'm not sure I understand. Do you have an example for what you wanted to see?

**Comment by moghadas76** [comment]
In my code, e.g. a util function, I requested another sub-system. I want to calculate the response time of such requests separately to determine the API's bottleneck,

**Comment by matthiask** [comment]
Maybe the profiling panel answers those questions for you? 

I'm afraid django-debug-toolbar doesn't help much otherwise, currently. Maybe there's a third party panel you can use or else some other way to instrument the Python code.

**Comment by moghadas76** [comment]
I want to contribute. May you share the code documentation? Unfortunately, I did not get it well.

**Comment by tim-schilling** [comment]
@moghadas76 the only documentation for the project is available at https://django-debug-toolbar.readthedocs.io/en/latest/

Using the GitHub's blame feature can help you identify PR's and issues that caused changes to be made. If you have specific questions, feel free to ask us.

**Comment by tim-schilling** [comment]
Closing this issue. We can continue the discussion, but it's not really a concern for the DDT in general. If you want to join Jazzband to contribute to the toolbar in a more regular fashion, see [jazzband.co](https://jazzband.co).
