### ISSUE TITLE
Include urls without importing package

### ISSUE THREAD

**Issue by timoludwig** [jazzband/django-debug-toolbar#1506]
I don't want to have the `django-debug-toolbar` package installed in my production environment, so I'm looking for alternatives to a slightly "dirty" import which is not at the top of the file (see [PEP-402](https://www.python.org/dev/peps/pep-0402/)):
```
if "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns.append(url(r"^__debug__/", include(debug_toolbar.urls)))
```
But the obvious string-module-path
```
    urlpatterns.append(url(r"^__debug__/", include("debug_toolbar.urls")))
```
fails due to the error `ModuleNotFoundError: No module named 'debug_toolbar.urls'`.

However, I noticed that
```
urlpatterns.append(url(r"^__debug__/", include("debug_toolbar.toolbar")))
```
seems to work, so I wonder why this isn't documented. Are there any downsides to this approach, or might this stop to work in future versions of the django debug toolbar?

Thanks for any comments on this!

Django version: 3.2.7
Django Debug Toolbar version: 3.2.2

**Comment by matthiask** [comment]
To be honest: I have no idea why we cannot make `include("debug_toolbar.urls")` work (except for time and energy, always excellent reasons)

Maybe it has to do with old ways of declaring URLconf namespaces or maybe something to do with the magical auto-installation of the toolbar which has been removed a few years ago.

**Comment by tim-schilling** [comment]
Yarp, I agree here. This should be possible now if it wasn't in the past.
