### ISSUE TITLE
Run CI tests on dependency updates

### ISSUE THREAD

**Issue by tim-schilling** [jazzband/django-debug-toolbar#1524]
#1523 started running the CI tests on a periodic basis to identify integration problems with dependencies or other libraries. Ideally we'd only run the CI tests when one of the dependencies actually changes. Otherwise we're wasting resources. I think the best option for this is to use Dependabot.

I think it'd be possible to do by using pip-tools and creating a `requirements_ci.in` and `requirements_ci.txt` file. This file would contain all the dependencies listed within the `tox.ini` file. The goal is to have Dependabot identify the changes in that requirements file, then create a PR which will run CI, thus identifying integration problems.

If we do go this route, I think it'd be a good idea to use the auto-merge functionality such that it will automatically merge these PRs specifically when they pass.

**Comment by matthiask** [comment]
There seems to be a problem with dependabot where it's impossible to disable it on forks:
https://github.com/dependabot/dependabot-core/issues/2804
https://github.com/numpy/numpy/issues/18977

I'm not against it but one should be aware of this.

**Comment by tim-schilling** [comment]
I'm going to close this. I'm not sure it's worth the inherent problems with managing dependencies and the forking issue.
