### ISSUE TITLE
merging a 3rd party package  into django-debug-toolbar

### ISSUE THREAD

**Issue by andytwoods** [jazzband/django-debug-toolbar#1564]
Hi there,

if you felt it a good idea, I'd be happy to merge in the features of this extension into your package: https://github.com/andytwoods/mrbenn

This extension lets you click on a view or template link, and have that view/template open in your IDE. I envision there being a toggle within settings where people can specify if they want this feature.

I would just modify your Template and View tools, adding clickable links. The dedicated toolbar provided by mrbenn would then be unnecessary. 

cheers,
Andy.

**Comment by tim-schilling** [comment]
I'm on board with this addition to the `TemplatesPanel`, @matthiask? It doesn't appear to be a bunch of logic, but rather configuration. It would mean a fair amount of documentation to keep the installation straightforward and quick.

**Comment by matthiask** [comment]
I'm not sure. I don't know much about `mrbenn` but it doesn't seem to be a widely used package, see https://pypistats.org/packages/mrbenn

The package runs a few commands in the background to open files in the IDE, e.g. xdg-open on Linux. I'm slightly against adding code which uses `subprocess` into the main django-debug-toolbar package.

**Comment by andytwoods** [comment]
Just a heads up that we only released mrbenn perhaps a week ago. Maybe the best option is to wait and see how popular mrbenn becomes.

**Comment by tim-schilling** [comment]
@andytwoods have you looked into implementing extensions for VSCode and PyCharm? I have no idea what that would look like, but I wonder if we could find a different way to implement this.

**Comment by matthiask** [comment]
Thanks for the proposal, but I'm going to reject it for the moment because of limited maintainer time. Thanks, and please feel free to propose it again later if you find the time do pursue this!
