### ISSUE TITLE
 debug toolbar not showing only when you use Render or HttpResponse function 

### ISSUE THREAD

**Issue by yangislet** [jazzband/django-debug-toolbar#1596]
toolbar will show when you login admin , however it will not show  when you  use Render or HttpResponse function  in view function . like `
class Vue3API(APIView):  
    def get(self, request, **kwargs):
        """
        Return a list of all users.
        """ 
        books = Book.objects.all()
        se = BookSerializerPro(books, many=True) 
	# this code will show debug panel
        return Response(se.data) 
	# this code will not show debug panel
        #return render(request, "register.html", {"foo": "bar"})
        #return HttpResponse(content="tesing".encode())`

i use the windows 10 even i have configure the HKEY_CLASSES_ROOT\.js  in register table  !   
Django |   | 3.2.10 
Python |   | 3.9.1 
debug_toolbar | Debug Toolbar | 3.2.4

**Comment by tim-schilling** [comment]
The toolbar gets injected into the html response just before the </body> tag. If the response doesn't have that, the toolbar isn't inserted.

**Comment by tim-schilling** [comment]
Closing due to lack of response.
