### ISSUE TITLE
Move Icon

### ISSUE THREAD

**Issue by michaelschem** [jazzband/django-debug-toolbar#1600]
I'm trying to move the icon to a less intrusive location, preferably the footer.

I've added the following config:

```
"INSERT_BEFORE": "</footer>",
```
and while it does move it from a DOM perspective into the footer, it still displays on the side due to the css.  Is there a way to either override the css or an option to put it somewhere else?

**Comment by matthiask** [comment]
The toolbar doesn't offer a setting to do this, but you can of course override the CSS with your own. There's no documented (or supported) way to do this either but we won't just go ahead and change CSS classes without a good reason.

**Comment by michaelschem** [comment]
yea, I tried that but since it's loaded into the dom after page load, the css won't apply... unless I'm doing something wrong.

**Comment by matthiask** [comment]
You have to increase the specificity of the CSS somehow, e.g. by using `html #djDebugToolbarHandle` instead of only `#djDebugToolbarHandle`

**Comment by matthiask** [comment]
By the way, you know that you can drag the handle along the right hand side of the browser window and that it stays there?

**Comment by michaelschem** [comment]
I was using the wrong css file *facepalm* thanks for your help.

**Comment by matthiask** [comment]
Nice :) this happens to me all the time 😂 

Glad it works.

**Comment by tim-schilling** [comment]
I haven't looked, but I want to point out you should be able to drag it
up/down.
