### ISSUE TITLE
doe‘snt work

### ISSUE THREAD

**Issue by crackfan** [jazzband/django-debug-toolbar#1602]
![image](https://user-images.githubusercontent.com/2922399/161053497-7257ef13-1f61-4542-9850-f8791f499bdf.png)
![image](https://user-images.githubusercontent.com/2922399/161053694-1604b72f-76fe-479b-bd82-29db0b89e742.png)

**Comment by matthiask** [comment]
Hi @crackfan 

This issue has nothing to do with django-debug-toolbar. You could add `CSRF_COOKIE_SECURE = True` to your settings (see  https://docs.djangoproject.com/en/4.0/ref/settings/#csrf-cookie-secure ) but then CSRF protection would disallow sending any POST requests to the server when developing without HTTPS (the URL in the screenshot uses `http://`)

**Comment by crackfan** [comment]
![image](https://user-images.githubusercontent.com/2922399/161206885-08355b1e-22b7-49f2-944f-6d774b9abb44.png)

**Comment by matthiask** [comment]
Oh so the tool detects that, that's good. Better than saving the cookie in the browser but never sending it to the server (since you're still serving the site using HTTP, not HTTPS)

**Comment by crackfan** [comment]
```pyhone
if DEBUG:
    import mimetypes
    mimetypes.add_type("application/javascript", ".js", True)
```

it's fine！ THS

**Comment by yangislet** [comment]
> ```
> if DEBUG:
>     import mimetypes
>     mimetypes.add_type("application/javascript", ".js", True)
> ```
> 
> it's fine！ THS
你这个配置信息是放在setting.py文件中吗？Thanks

**Comment by crackfan** [comment]
add in setting.py
