### ISSUE TITLE
Backward compatability issues: BaseConnectionHandler.all() got an unexpected keyword argument 'initialized_only'

### ISSUE THREAD

**Issue by ovsds** [jazzband/django-debug-toolbar#1645]
In 3.5.0 used `BaseConnectionHandler.all(initialized_only=True)`:
https://github.com/jazzband/django-debug-toolbar/commit/4b77ec74f2d326013d715453d7a2219e574c3f6a#diff-72ecd973e54107d746eff0947206cbdbe24cbb3c42216b00615e64d49ca70d73R216-R217

Which is only added in Django 4.1b1:
https://github.com/django/django/commit/4f92cf87b013801810226928ddd20097f6e4fccf#diff-dbe1d4538efcca9f9a6157d5d3de919e0844835a7ccc698bb8c5d4a9eb06e274R75-R81

Which causes crash on any pageload if middleware `debug_toolbar.middleware.DebugToolbarMiddleware` is on.

**Comment by tim-schilling** [comment]
> If you need me to provide any additional info feel free to ask

Can you please provide the full stacktrace and error message?

**Comment by matthiask** [comment]
Thanks all! I think it's fine to depend on the latest version in the 3.2 LTS series. **Maybe** this should be documented somewhere, but since the Django developers decided that the change should be backported I'm fine with depending on this (since it reduces the work *we* have to do to nothing)
