### ISSUE TITLE
Show executed lines in a view

### ISSUE THREAD

**Issue by mkalioby** [jazzband/django-debug-toolbar#1675]
Hello,

What about having a panel that shows the executed functions with lines inside it.

I can work on implementation if you think it is a good idea.

**Comment by tim-schilling** [comment]
@mkalioby I think you may be describing the profiling panel. Have you tried enabling that?

**Comment by mkalioby** [comment]
I didn't know about that, so I gave it a go and it is similar but the problem the root doesn't make sense, I think I can work on it to have a better presentation.

Thanks for the tip.

**Comment by tim-schilling** [comment]
Can this issue be closed? Otherwise, we'll need more details on what you're looking for.

**Comment by mkalioby** [comment]
I'll try to do a protype of what I want and open another issue
