### ISSUE TITLE
Toolbar is not showing for the template rendered but perfectly works for admin and error page

### ISSUE THREAD

**Issue by Binit-Dhakal** [jazzband/django-debug-toolbar#1678]
I have followed all the tutorials all over the Internet, youtube-videos and all forums but have not been able to make Django-debug-toolbar appear for the template I rendered. It is working fine for the error page and the Django-admin page but not for the template I render. I am confused about what might have gone wrong. 
The steps I have followed for installation:
- made DEBUG=True
- have "debug_toolbar" in the INSTALLED_APPS
- have "debug_toolbar.middleware.DebugToolbarMiddleware' at the top. I followed [Link this](https://github.com/jazzband/django-debug-toolbar/blob/main/tests/settings.py#L72)
- Put "APP_DIRS":True in TEMPLATES. 
`TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "APP_DIRS": True,
        'DIRS': [BASE_DIR/"templates"],
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        
        },  
    },
]`
- Also added these configs,
`DEBUG_TOOLBAR_CONFIG = {
        "SHOW_TOOLBAR_CALLBACK" : lambda request:True,
        "RENDER_PANELS": False,
        'INTERCEPT_REDIRECTS': False,
    }`
- And IPS as INTERNAL_IPS = ["127.0.0.1"]
- And in project urls.py I have added 
`import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]`

Just for side info, I am using the AWS setting in the database, I think that might not have caused the issue.

Is this issue with my template? I am using a bare minimum template so I guess that is not a problem. I will appreciate your help.
Thank you

**Comment by tim-schilling** [comment]
Since the admin renders the toolbar, it's likely something specific to your project.

1. Does the rendered HTML have a `</body>` tag?
2. Can you inspect the rendered HTML for the toolbar?
3. Have you tried creating a basic template that's rendered with a `TemplateView`?

**Comment by Binit-Dhakal** [comment]
Hello Tim, Thanks a lot for your reply. The first one was the issue and it is fixed now. I made a base template without a body just {block content}{endblock content} and build up my other template extending that template. Now it is showing for the template I made.
As the issue is fixed, I am closing this.
Thank you,
Binit Dhakal
