### ISSUE TITLE
Overly loud tests in the development environment

### ISSUE THREAD

**Issue by interDist** [jazzband/django-debug-toolbar#1681]
We recently went through an upgrade of Django and Python, including the supporting tools, and suddenly our tests started outputting lots of extra information (that was not there before), when run in the development environment. After countless hours trying to find the source of the output, I finally discovered that DDT now adds a `lastResort` handler to the root logger. This change, implemented in #1603, is fairly recent (merged 6 months ago) and, unfortunately, is not documented in the changelog.
The difference between the development environment and the CI testing environment is, of course, that in the CI flow DDT is not installed.
How can DDT be updated so as to avoid all the verbose output being printed, when tests are run?

**Comment by tim-schilling** [comment]
I'm having difficulty reproducing this as well. @interDist could you show us how you add the toolbar into your middleware and installed apps in your settings as well as how you're including the toolbar's urls? Include any protecting if statements.

**Comment by interDist** [comment]
Sure. Here is our configuration.

`settings/base.py`
```python
MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
    'dnt.middleware.DoNotTrackMiddleware',
    'core.middleware.AccountFlagsMiddleware',
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'mail_admins_important_bits': {
            'level': 'WARNING',
            'class': 'django.utils.log.AdminEmailHandler',
        },
        'mail_admins_severe_bits': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
        },
    },
    'loggers': {
        'my_project': {
            'handlers': ['mail_admins_severe_bits'],
        },
        'my_project.auth': {
            'handlers': ['mail_admins_important_bits'],
            'propagate': False,
        },
    },
}
```

`settings/dev.py`
```python
INSTALLED_APPS += (
    'debug_toolbar',
)

MIDDLEWARE.insert(
    [i for i, mw in enumerate(MIDDLEWARE) if mw.startswith('django')][-1] + 1,
    'debug_toolbar.middleware.DebugToolbarMiddleware'
)

DEBUG_TOOLBAR_CONFIG = {
    'JQUERY_URL': '/static/js/jquery.min.js',
    'DISABLE_PANELS': {
        'debug_toolbar.panels.redirects.RedirectsPanel',
    },
    'SHOW_TOOLBAR_CALLBACK': 'my_project.debug.show_debug_toolbar',
}
```

`my_project.debug.py`
```python
def show_debug_toolbar(request):
    return bool(settings.DEBUG)
```

The tests are run using unittest. `python3 ./manage.py test`. @matthiask I don’t mind too much logging in development env, but it clutters the output of the tests when the testsuite is run in dev. particularly since the testsuite generates on purpose error conditions to verify proper handling of those.

**Comment by tim-schilling** [comment]
Do you run your tests using `settings/dev.py`? I'd recommend running them in an environment where the toolbar doesn't get enabled.

**Comment by interDist** [comment]
Well, when I am writing / updating the tests, I am doing it in the development environment. Also, when updating a piece of code I would want to first run the related tests, in dev env, to check I did not break anything, right? I suppose I could use `--settings=my_project.settings.devtest` which would be similar to the existing `settings/dev.py` but without DDT stuff.

However, nothing of it is documented in the docs (usage of the `lastResort` logger, running tests in an environment without the toolbar, implications of running tests in an environment with the toolbar enabled)...

**Comment by tim-schilling** [comment]
@interDist sorry for not responding earlier. Yes you want to run your tests on your local machine, but I believe they should be run with your production configuration, meaning `DEBUG=False`, no toolbar, etc.

If you (or you @Shriukan33) could create a minimal project that reproduces this effect that would be extremely helpful to us. There is the `example` django project in the toolbar repo that could be extended if you'd prefer to fork this to have a small head start on building a new project.

**Comment by tim-schilling** [comment]
[Django will force `DEBUG = False` when running tests.](https://docs.djangoproject.com/en/4.1/topics/testing/overview/#other-test-conditions)
