### ISSUE TITLE
"Switch" and "Refresh" button on History panel suddenly give raw JSON

### ISSUE THREAD

**Issue by HiIamJeff** [jazzband/django-debug-toolbar#1692]
Hi there, 

First of all, thanks to all the contributors for making this great tool (It is much easier to check the actual queries now).

I recently updated the django-debug-toolbar from 3.2.4 to the latest version (3.7.0). I noticed that now when I go to the history panel to switch to the other requests, I would jump to the page about raw JSON data (the URL is also changed from my original calls (e.g., `http://127.0.0.1:8000/some_endpoint_call`) to something like `http://127.0.0.1:8000/__debug__/history_sidebar/?signed=%7B%22store_id%22%3A+%22453f97773500479787f634980798f883%22%7D%3AW1Ja-DP7IEn0vqQzXkyPxWFPGCKyyDwwqIGihf0VVns`).  
![image](https://user-images.githubusercontent.com/7938689/197621578-290c02b1-e178-4b47-8c13-c40fca2de236.png)

All the other buttons from the other panels seem to be working fine, but just this one has this issue.

I always used this panel to check my POST actions (about queries), but now I can't do that anymore. I am not sure what changes I made to make this happen, but please help me with this. If you know if there is a way to call the debugger tool without actually calling any GET actions, that would also be very helpful at the moment. Thank you.

**Comment by tim-schilling** [comment]
Hi @HiIamJeff can you be more specific about your workflow and how you expect the toolbar to work within that workflow?

**Comment by HiIamJeff** [comment]
Sure. This is for local testing. When I test the new endpoint, I would runserver locally, call the endpoint on Chrome, and goes to the Browsable API for Django REST framework (The toolbar would appear). On that page, I usually go to the SQL panel to check the queries and stuff and I will switch between the different endpoint calls to check the info (The workflow will be going to the History panel, switching to the previous endpoint call, and going to the SQL panel...). 

Now here is the issue, when I make different endpoint calls (and I can see those records on the History panel), clicking Switch button now brings the page to the screenshot I shared above. This was not the case before I updated the package (When it worked before, it would still stay on the Browsable API page with the toolbar).

**Comment by tim-schilling** [comment]
To confirm, when you click switch the browser changes to a url like `http://127.0.0.1:8000/__debug__/history_sidebar/?signed=`?

Is there anything in the Console tab for the browser developer tools? Are you using custom settings for the toolbar?

**Comment by HiIamJeff** [comment]
@tim-schilling That's right. The browser goes to that URL (raw JSON page).

About the Console tab for the browser developer tools, there are some messages. Below is when I first get to the Browsable API by calling endpoints.
![image](https://user-images.githubusercontent.com/7938689/197630155-02f37c67-7c8c-416e-942e-9d75338c1251.png)

If I clicked to the the History panel, there is a new error (`Uncaught SyntaxError: The requested module './utils.js' does not provide an export named 'replaceToolbarState' (at history.js:1:24)`).
![image](https://user-images.githubusercontent.com/7938689/197630399-47f70357-6b79-4262-9ed4-9628f668e4e6.png)

If I clicked the switch button (going to the raw JSON page), there is another error 
![image](https://user-images.githubusercontent.com/7938689/197630610-4272be19-6754-4f0a-aa55-dbb21dfd8346.png)


I am not sure about the custom settings part. I haven't tweaked anything about the toolbar settings before I made the updates, so I guess not.  

By the way, I tested downgrading back to 3.2.4, but the issue persists.
This is the system message from my Django console (the second one is clicking on the History panel. The third one is clicking the switch button). Hope this helps the investigation.

> [24/Oct/2022 17:16:30] "GET /some_endpoint_call/1 HTTP/1.1" 200 50384
> [24/Oct/2022 17:16:33] "GET /__debug__/render_panel/?store_id=4d57dd08984a4a1c984738f1933314cb&panel_id=HistoryPanel HTTP/1.1" 200 2285
> [24/Oct/2022 17:16:37] "GET /__debug__/history_sidebar/?signed=%7B%22store_id%22%3A+%224d57dd08984a4a1c984738f1933314cb%22%7D%3ABMYe-qzHrwfQ9cKku7fH9Vb_ML3lqrP0j0sJmov-04U HTTP/1.1" 200 9198

**Comment by tim-schilling** [comment]
I suspect your JS is being cached. That error about "The requested module './utils.js' does not provide an export named 'replaceToolbarState' at (history.js:1:24)" shouldn't be happening. Try loading the utils.js file. Whatever the URL is for history.js, change history -> utils for that URL.

**Comment by HiIamJeff** [comment]
I am not sure how to reload the utils.js file or what the URL is for history.js. Do you know where I should do this? Is it on the browser developer tools?

**Comment by tim-schilling** [comment]
You should be able to find it in the network panel of the browser developer tools.

**Comment by HiIamJeff** [comment]
Interesting. I found that history.js on the network tab and did "Clear browser cookies". Then the problem is fixed (I can switch to different records without jumping to the raw JSON page now). 

Thanks for your swift help! I wonder what causes this to happen (I have been using this toolbar for 3 months and never had this before).

**Comment by tim-schilling** [comment]
It's the browser caching your static files. If you use "Disable Cache" on the networking panel, you'll be less likely to run into these issues developing locally.
