### ISSUE TITLE
Not working for function based views

### ISSUE THREAD

**Issue by muthumanickamP** [jazzband/django-debug-toolbar#1706]
This debug toolbar setup is not working for function-based views. is there any option for accessing the function based?

when accessing class-based model viewset API
![class](https://user-images.githubusercontent.com/71870578/201610887-470d082a-ba77-423a-98a0-62d4242a840d.png)

when accessing function based API
![func](https://user-images.githubusercontent.com/71870578/201611046-cb2cd980-ac56-4d74-b597-f0a39e65b1e3.png)

**Comment by muthumanickamP** [comment]
I tried i am able to see the logs but i would like to get the sql logs like how many times the api hit the database and which query is executing how much time so that i can enhance the performance kindly do let me know how can i achieve that it would be a great help
<img width="990" alt="MicrosoftTeams-image (8)" src="https://user-images.githubusercontent.com/71870578/202854620-1f7a1eec-7c34-4a45-bd4e-77479a344067.png">

**Comment by tim-schilling** [comment]
Open a page to the admin, make the API request, then on the Admin page open the toolbar, go to the history panel and click refresh.

**Comment by muthumanickamP** [comment]
![Screenshot from 2022-11-19 19-53-01](https://user-images.githubusercontent.com/71870578/202855535-6269f8e7-2382-498b-b4ba-199ef6952fef.png)

Thanks for the response I am not able to see the history panel  here can you please guide me where I can see the history page

**Comment by tim-schilling** [comment]
What version of django and the django debug toolbar are you using?

**Comment by muthumanickamP** [comment]
Django - 3.1.4
django_debug_toolbar - 3.2.2

In settings.py
```
DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    'debug_toolbar.panels.settings.SettingsPanel',
    'debug_toolbar.panels.headers.HeadersPanel',
    'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    'debug_toolbar.panels.templates.TemplatesPanel',
    'debug_toolbar.panels.cache.CachePanel',
    'debug_toolbar.panels.signals.SignalsPanel',
    'debug_toolbar.panels.logging.LoggingPanel',
    'debug_toolbar.panels.redirects.RedirectsPanel',
]
```
middleware
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'drf_api_logger.middleware.api_logger_middleware.APILoggerMiddleware',
]

this is what I am integrating into settings.py

**Comment by muthumanickamP** [comment]
Found the issue 
debug_toolbar.panels.history.HistoryPanel is missing in the settings.py file
thanks for your help

**Comment by tim-schilling** [comment]
I'm glad you were able to resolve this.
