### ISSUE TITLE
Is the documentation updated?

### ISSUE THREAD

**Issue by vyach-vasiliev** [jazzband/django-debug-toolbar#1724]
Hello everyone and thanks for your contribute, you made an amazing product!

I noticed that the latest version of the documentation does not match the features that were added earlier.
Can I ask you to update the documentation on the [site](https://django-debug-toolbar.readthedocs.io/en/latest/)?

For example, in this [thread](https://github.com/jazzband/django-debug-toolbar/pull/1703), a setting was added to the documentation files, but it is not displayed on the [site](https://django-debug-toolbar.readthedocs.io/en/latest/configuration.html#panel-options) itself.
This feature already works in version [3.8.1](https://github.com/jazzband/django-debug-toolbar/blob/3.8.1/docs/configuration.rst).

**Comment by matthiask** [comment]
Hi, thanks for the report!

Since switching packaging to hatch the package installation step of the RTD build failed. 

Fixed in b543e67d87b50f85460219d39e454e093a069812 by adding RTD configuration.
