### ISSUE TITLE
Use on sitemap.xml

### ISSUE THREAD

**Issue by shawnngtq** [jazzband/django-debug-toolbar#1728]
> The Debug Toolbar will only display when DEBUG = True in your project’s settings (see [Show Toolbar Callback](https://django-debug-toolbar.readthedocs.io/en/latest/configuration.html#show-toolbar-callback)) and your IP address must also match an entry in your project’s INTERNAL_IPS setting (see [6. Configure Internal IPs](https://django-debug-toolbar.readthedocs.io/en/latest/installation.html#internal-ips)). It will also only display if the MIME type of the response is either text/html or application/xhtml+xml and contains a closing </body> tag.

This isn't display on `example.com/sitemap.xml`, which is xml and doesn't have body tag, anyway we can do it?

I am trying to analyze my sitemap performance.

Thanks 🙏

**Comment by matthiask** [comment]
@shawnngtq I don't think browsers will be able to interpret the HTML in a sitemap XML file. What you want is already possible though: Visit the sitemap.xml URL and then visit any URL where the toolbar is embedded; open the History panel and switch to the sitemap.xml request:
![image](https://user-images.githubusercontent.com/2627/211188320-aeda0825-7b78-41fb-80b4-7a5ed3c05932.png)

**Comment by shawnngtq** [comment]
@matthiask thanks! learn something new 👍
