### ISSUE TITLE
404 - Page not found

### ISSUE THREAD

**Issue by xavierbaez** [jazzband/django-debug-toolbar#1729]
I tried with Pycharm
Visual Studio Code

venv
pipenv

I read all the instructions and repeated the installation 4-5 times, all day today
`

Using the URLconf defined in django_debug_toolbar.urls, Django tried these URL patterns, in this order:

    admin/
    __debug__/

The empty path didn’t match any of these.
`

I tried with Django 4, 3, 2

**Comment by matthiask** [comment]
Hi @xavierbaez 

A screenshot would be helpful. 

Maybe you have to visit /admin/ or some other route which actually returns a valid response?

**Comment by tim-schilling** [comment]
I'm closing this for now. If you're still encountering an error, please include the full error and stacktrace.
