### ISSUE TITLE
Add Support for psycopg3 

### ISSUE THREAD

**Issue by nofalx** [jazzband/django-debug-toolbar#1736]
With the release of django 4.2a we can use psycopg3. However [django-debug-toolbar](https://github.com/jazzband/django-debug-toolbar) is not compatible with it.

**Comment by jnns** [comment]
For folks searching the web why Django isn't working after upgrading to psycopg3:

> 'Connection' object has no attribute 'status'

**Comment by officialgabzz** [comment]
ran into same

**Comment by matthiask** [comment]
@officialgabzz With the current version of the toolbar or with an old version?

**Comment by matthiask** [comment]
Thanks for the confirmation. Only the latest version is supported so problems with older versions are to be expected.
