### ISSUE TITLE
Toolbar not generating proper SQL but django orm querying proper data !

### ISSUE THREAD

**Issue by jiaulislam** [jazzband/django-debug-toolbar#1742]
I have form as below. But When I'm trying to loading in frontend data is fetching correctly but debug toolbar showing wrong SQL. It should generate `AND "WP_LOV_PLANS"."PLAN_STATUS" = "A"` but generating wrong SQL as given below.

```
# Premium Calculation Form
class PremiumCalcForm(forms.Form):
    def __init__(self, age=None, *args, **kwargs):
        super(PremiumCalcForm, self).__init__(*args, **kwargs)
        if age:
            self.fields["plan"] = forms.ModelChoiceField(
                queryset=InsurancePlan.objects.filter(
                    plan_status="A",
                    max_age__gte=age,
                    min_age__lte=age,
                )
            )

    plan = forms.ModelChoiceField(
        queryset=InsurancePlan.objects.filter(
            plan_status="A",
        ),
        required=True,
        label="Plan",
    )
    hi_plan = forms.CharField(max_length=30)
```

Django-Debug-Toolbar SQL Log:
`
 SELECT "WP_LOV_PLANS"."PLAN",        "WP_LOV_PLANS"."PLANNAME",        "WP_LOV_PLANS"."POLICY_TYPE",        "WP_LOV_PLANS"."NEW_PLAN",        "WP_LOV_PLANS"."PLAN_TYPE",        "WP_LOV_PLANS"."BONUS",        "WP_LOV_PLANS"."BUSINESS_TYPE",        "WP_LOV_PLANS"."PLAN_TYPE_NAME",        "WP_LOV_PLANS"."MIN_AGE",        "WP_LOV_PLANS"."MAX_AGE",        "WP_LOV_PLANS"."NAME",        "WP_LOV_PLANS"."PROD_CODE",        "WP_LOV_PLANS"."PLAN_STATUS",        "WP_LOV_PLANS"."STATUS_DATE"   FROM "WP_LOV_PLANS"  WHERE ("WP_LOV_PLANS"."MAX_AGE" >= 28 AND "WP_LOV_PLANS"."MIN_AGE" <= 28 AND "WP_LOV_PLANS"."PLAN_STATUS" = 28)  ORDER BY "WP_LOV_PLANS"."PLAN" DESC
`

**Comment by tim-schilling** [comment]
@jiaulislam unless `plan_status` is a relationship field, I think you may have a bug in your queryset. I think it's very unlikely for the toolbar to change the value of a queryset filter from an `"A"` to `28`. Especially considering your query contains that value 28 for other filtering options. I could be wrong and if you feel strongly that this is a bug in the toolbar can you please create a reproducible example for us?

**Comment by jiaulislam** [comment]
@tim-schilling thanks for your reply, I thought the issue was with toolbar but after 6 hours of tracing 😓😭, I found out it's a issue with Django's Oracle backend which is solved in [this](https://github.com/django/django/commit/64b3c413da011f55469165256261f406a277e822) commit. Any way I learned a lot in this 6 hours lol as a begineer.

Thanks again 😁

**Comment by tim-schilling** [comment]
As long as you learned, things are going well!
