### ISSUE TITLE
False postive for debug_toolbar.W006 when manually declaring cached template loader. 

### ISSUE THREAD

**Issue by carltongibson** [jazzband/django-debug-toolbar#1780]
Hi. 

Manually declare template loaders, using the cached loader: 

```
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        # "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "loaders": [
                (
                    "django.template.loaders.cached.Loader",
                    [
                        "django.template.loaders.filesystem.Loader",
                        "django.template.loaders.app_directories.Loader",
                    ]
                ),
            ],
        },
    },
]
```

The DDT `APP_DIRS` check then gives a false positive: 

```
?: (debug_toolbar.W006) At least one DjangoTemplates TEMPLATES configuration needs to use django.template.loaders.app_directories.Loader or have APP_DIRS set to True.
        HINT: Include django.template.loaders.app_directories.Loader in ["OPTIONS"]["loaders"]. Alternatively use APP_DIRS=True for at least one django.template.backends.django.DjangoTemplates backend configuration.
```

In: 

https://github.com/jazzband/django-debug-toolbar/blob/de7e19c5ef08445ca592c75dfa3dad22c04992a1/debug_toolbar/apps.py#L26

It looks like checking for and walking `loader.loaders` would resolve this. 🤔

**Comment by matthiask** [comment]
Hey

This came up once already; if `OPTIONS["debug"]` defaults to `DEBUG`; and if `debug` is `False` the cached loader is used automagically. 

See https://docs.djangoproject.com/en/4.2/releases/1.11/#miscellaneous

> The [cached template loader](https://docs.djangoproject.com/en/4.2/ref/templates/api/#django.template.loaders.cached.Loader) is now enabled if [OPTIONS['loaders']](https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-TEMPLATES-OPTIONS) isn’t specified and [OPTIONS['debug']](https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-TEMPLATES-OPTIONS) is False (the latter option defaults to the value of [DEBUG](https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-DEBUG)). This could be backwards-incompatible if you have some [template tags that aren’t thread safe](https://docs.djangoproject.com/en/4.2/howto/custom-template-tags/#template-tag-thread-safety).

See #1550 and #1704 too.

We probably should still fix this but it has been declared as low priority in the past.

**Comment by carltongibson** [comment]
Yep, agreed. I don't think it's a biggie. (It's pretty niche.) 

Current work around is: 

```
SILENCED_SYSTEM_CHECKS = [
    "debug_toolbar.W006",  # See jazzband/django-debug-toolbar#1780
]
```

(I may be able to swing to it at some point.)

**Comment by matthiask** [comment]
Yes, or you (or any readers of this issue) could remove the `loaders` entry in the `TEMPLATES` configuration if you're fine with not using the cached loader when debugging. 

This would be sufficient:

```python
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]
```

(It's what I use these days.)

**Comment by carltongibson** [comment]
Yep 👍. 

Since the autoreloader support for templates was added in Django 4.1, the cached loader is used in development too. As such, there's almost no need to declare loaders for the majority case. 

(I'm only doing it myself because I'm tweaking...)
