### ISSUE TITLE
panels get suddenly disabled (cookie)

### ISSUE THREAD

**Issue by jacopsd** [jazzband/django-debug-toolbar#1789]
When using Django debug toolbar, I noticed that from time to time some panels get disabled. In that case a cookie is stored in the client e.g. djdtHistoryPanel=off
There is no clear reason why this suddenly gets disabled. Same thing happens with the SQL panel from time to time.

Versions:
django-debug-toolbar==4.1.0. (also 4.0.0 has the same issue)
django==3.2.x

**Comment by tim-schilling** [comment]
Are you using ASGI and/or async views? How are you running the application?

**Comment by jacopsd** [comment]
This is running on local dev server: 

`python manage.py runserver`

**Comment by tim-schilling** [comment]
Does the page have any ajax on them that would load a page periodically?

**Comment by tim-schilling** [comment]
Closing until we have a reproducible example.
