### ISSUE TITLE
SameSite

### ISSUE THREAD

**Issue by robslotboom** [jazzband/django-debug-toolbar#1792]
See this code in debug_toolbar/static/debug_toolbar/js/toolbar.js:

```
 "sameSite" in options
            ? "; sameSite=" + options.samesite
            : "; sameSite=Lax",

```
Shouldn’t this be?

```
 "sameSite" in options
            ? "; sameSite=" + options.sameSite <<< Capital S
            : "; sameSite=Lax",

```

**Comment by matthiask** [comment]
Good find, that's correct.

I wonder if we shouldn't lowercase all keys though, according to https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie all standard keys use kebab-case names. That would probably be more consistent.

**Comment by robslotboom** [comment]
kebab-case :-DDD

|| That would probably be more consistent.

Yes I think so.
