### ISSUE TITLE
Deadlock when using concurrency in async views

### ISSUE THREAD

**Issue by salomvary** [jazzband/django-debug-toolbar#1828]
Hi folks,

First of all thanks for maintaining this amazing project! I've recently started migrating an existing project to asynchronous views and noticed that the view gets deadlocked when tasks are executed concurrently **and** the Debug Toolbar is installed.

If no tasks run concurrently (ie. using a sequence of `await`s) or the Debug Toolbar is removed, everything seems fine.

Below is an example that hangs forever on `await asyncio.gather`:

```python
async def get(request):
    (one_thing, another_thing) = await asyncio.gather(
        Thing.objects.filter(pk=1).afirst(),
        Thing.objects.filter(pk=2).afirst()
    )

    return HttpResponse(content=f"Hello {one_thing.pk} {another_thing.pk}")
```

I'm relatively new to Python `asyncio` and have therefore no idea what's going on. I see the ongoing async issues in this issue tracker but I am not sure what's the state of Django async support (or lack of it) is here. (Something that might be worth documenting on the Readme.)

These are the dependencies in use:
```
$ poetry show -T   
daphne               4.0.0   Django ASGI (HTTP/WebSocket) server
django               4.2.4   A high-level Python web framework that encourages rapid development and clean, pragmatic design.
django-debug-toolbar 4.2.0   A configurable set of panels that display various debug information about the current request/response.
psycopg2-binary      2.9.7   psycopg2 - Python-PostgreSQL Database Adapter
```

I can share a minimal test project if someone wants to have a look.

**Comment by tim-schilling** [comment]
The toolbar is sync only at this time. If you'd like to open a PR to call that out explicitly in the Readme and installation docs, that would be helpful. There was another idea to log a message or not fail too. If you can help, it'd be appreciated.

**Comment by salomvary** [comment]
> The toolbar is sync only at this time. If you'd like to open a PR to call that out explicitly in the Readme and installation docs, that would be helpful. There was another idea to log a message or not fail too. If you can help, it'd be appreciated.

@tim-schilling Something like this? https://github.com/jazzband/django-debug-toolbar/pull/1829

How big of an undertaking would be to add async support? (Full or partial). Looking at these issues, I have no idea: https://github.com/jazzband/django-debug-toolbar/issues?q=is%3Aissue+project%3Ajazzband%2F9+is%3Aopen

I'd be motivated to help, even with small contributions but am not familiar with the Toobar's internals (moderately familiar with Django internals, noob at Python async). Let me know if there are low hanging fruits to tackle.

**Comment by tim-schilling** [comment]
@salomvary Thank you for that PR and the offer to help.

The project for async compatibility is here: https://github.com/orgs/jazzband/projects/9

The main thing that you can help with that doesn't require much effort on my part is implementing tests that the toolbar would need to pass to be considered "working". This is issue https://github.com/jazzband/django-debug-toolbar/issues/1819

**Comment by salomvary** [comment]
I guess it does not make sense to keep this issue open then.

**Comment by salomvary** [comment]
[As I recently discovered,](https://forum.djangoproject.com/t/are-concurrent-database-queries-in-asgi-a-thing/24136) async or not, concurrent ORM queries are not yet a thing in Django, therefore this issue is even less of an issue in practice.
