### ISSUE TITLE
Template panel can trigger a SQL query

### ISSUE THREAD

**Issue by nijel** [jazzband/django-debug-toolbar#1834]
I've noticed this while working on https://github.com/jazzband/django-debug-toolbar/pull/1833

When the template panel gets an object implementing `__repr__`, it might lead to triggering a SQL query:

https://github.com/jazzband/django-debug-toolbar/blob/199c2b3c6bc916d371bcfb11b0fcbbb690ee5e36/debug_toolbar/panels/templates/panel.py#L120-L132

The problem is that `saferepr(value)` is used for testing, while `value` is used for the actual assignment. 

For example, with `SimpleLazyObject`, the `__repr__` returns `<SimpleLazyObject: <function <lambda> at 0x7fe8ccb9dca0>>`, but later `temp_layer[key] = value` causes the query to be executed. This particular case will be addressed by https://github.com/jazzband/django-debug-toolbar/pull/1833.

Using `saferepr` was introduced in https://github.com/jazzband/django-debug-toolbar/commit/06bafadf4cb12686215f0eae6857c3678710d2f4 via https://github.com/jazzband/django-debug-toolbar/pull/1076 to address other side effects of evaluating.

To make this code consistent, it should evaluate the value just once and use that later in the assignment.

**Comment by denisSurkov** [comment]
As far as I understand the code should be something like this?


```python3
 try: 
     value_safe_repr = saferepr(value)  # this MAY trigger a db query 

 ... 

 else: 
     temp_layer[key] = value_safe_repr
```

But I'm afraid of missing out details.

**Comment by nijel** [comment]
In that case, you can directly assign it without the `else` block:

```python
try: 
    temp_layer[key] = saferepr(value)
... 
```

I didn't submit a PR with such a change because I have no clue whether using `saferepr(value)` instead of `value` can break something.
