### ISSUE TITLE
Profiler not correctly filtering files on Windows

### ISSUE THREAD

**Issue by Oisota** [jazzband/django-debug-toolbar#1836]
The profiler is not filtering out non-project code when running on Windows. The culprit seems to be [these lines](https://github.com/jazzband/django-debug-toolbar/blob/199c2b3c6bc916d371bcfb11b0fcbbb690ee5e36/debug_toolbar/panels/profiling.py#L47-L48) in the `is_project_func` method. The forward slashes in the paths will never be in the path when on windows and all non project code gets included in the profile.

I was able to fix the issue locally by simply removing the forward slashes from the two paths. If this is an acceptable fix, I'd be happy to submit a PR.

**Comment by tim-schilling** [comment]
Hmm, there's probably a better way to inspect the filepath. I think we'd want to check that these are directories in the filepath and not simply check for the directory name in the filepath. A PR is definitely welcome!

**Comment by DraKen0009** [comment]
This is my first pull request , any advises would be greatly appreciated.
