### ISSUE TITLE
Injections cannot be made into the theme.

### ISSUE THREAD

**Issue by cnr91** [jazzband/django-debug-toolbar#1844]
I bought a bootstrap theme and the toolbar does not appear where this theme is. 
It looks like it cannot be injected into the page. 
What could be the reason for this?

The toolbar appears in the admin panel and in places where the theme is not.

**Comment by matthiask** [comment]
The toolbar is inserted before the `</body>` string by default, see `INSERT_BEFORE` here: https://django-debug-toolbar.readthedocs.io/en/latest/configuration.html#debug-toolbar-config

Maybe the theme doesn't have the expected closing body tag?

**Comment by cnr91** [comment]
Yes, I did not add `</body>`,  but when I rendered the page, the automatic body was added. 
The problem was solved when I added it now.

Thank you so much
