### ISSUE TITLE
The djdt handle shouldn't be stuck at the top of the browser window initially

### ISSUE THREAD

**Issue by matthiask** [jazzband/django-debug-toolbar#1853]
The handle can always be dragged around. But I'd prefer it if the handle wouldn't be at the top, but rather somewhere in the upper half of the browser window by default. (Hardcoding a better value is fine I think.)

The area at the top right is often used for other interactive elements, if I wouldn't have to move the toolbar handle in all user agents again that would be great.

**Comment by VeldaKiara** [comment]
Hi @tim-schilling and @matthiask  I would be happy to work on this issue.

**Comment by matthiask** [comment]
@VeldaKiara Yes, please!

**Comment by VeldaKiara** [comment]
On it.

**Comment by VeldaKiara** [comment]
Is this okay, or should I lower it?
<img width="1680" alt="Screenshot 2024-01-23 at 13 40 49" src="https://github.com/jazzband/django-debug-toolbar/assets/32552296/ede6facc-84ab-4542-ac6c-cf37c7651446">

**Comment by matthiask** [comment]
I think somewhere in the upper half is fine (as you've done it)

**Comment by VeldaKiara** [comment]
Done

**Comment by matthiask** [comment]
Closed by #1871
