### ISSUE TITLE
Exception while resolving variable 'toolbar' in template

### ISSUE THREAD

**Issue by foundkey** [jazzband/django-debug-toolbar#1905]
When sending a request using ajax, toolbar.js will send a request at the same time:
`GET /__debug__/history_sidebar/?store_id=<id> HTTP/1.1`

This request will throw the following exception when rendering the template：
> Traceback (most recent call last):
  File "/Users/.venv/lib/python3.10/site-packages/django/template/base.py", line 898, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [toolbar] in [{'True': True, 'False': False, 'None': None}, {'panel': <debug_toolbar.panels.cache.CachePanel object at 0x11f936590>}]
[DEBUG] 12/Apr/2024 10:31:22 - Exception while resolving variable 'toolbar' in template 'debug_toolbar/includes/panel_content.html'.
Traceback (most recent call last):
  File "/Users/.venv/lib/python3.10/site-packages/django/template/base.py", line 875, in _resolve_lookup
    current = current[bit]
  File "/Users/.venv/lib/python3.10/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'toolbar'

This request is handled by this method: [history_sidebar(request)](https://github.com/jazzband/django-debug-toolbar/blob/main/debug_toolbar/panels/history/views.py#L11)
It seems because `toolbar` is not passed in `panel_context`.

**Comment by foundkey** [comment]
After turning on Debug level logging, VariableDoesNotExist errors appear frequently during use. But it does not affect the use.

**Comment by tim-schilling** [comment]
Hmm. I'm softening on my earlier stance on the PR.

**Comment by Riskcomplexx** [comment]
I'm currently seeing the same thing but oddly only in firefox and not chrome.

**Comment by JasonSanDiego** [comment]
I see the issue on Chrome also

**Comment by tim-schilling** [comment]
@Riskcomplexx @JasonSanDiego I appreciate your seconding of the issue, but what will help get this resolve a reproducible example. Would you be able to provide one?
