### ISSUE TITLE
Checkboxes not all right-aligned

### ISSUE THREAD

**Issue by trey** [jazzband/django-debug-toolbar#1919]
I just upgraded to version 4.4.1 and noticed (in Firefox, Safari, and Vivaldi) that not all the checkboxes are right-aligned.

<img width="217" alt="Django Debug toolbar screenshot showing some staggered checkboxes on the right side of the panel" src="https://github.com/jazzband/django-debug-toolbar/assets/435/979381e3-57d5-4ea1-ac4d-d079fce86782">

**Comment by matthiask** [comment]
I cannot reproduce this. The right alignment of checkboxes is handled by this:
![image](https://github.com/jazzband/django-debug-toolbar/assets/2627/754187b1-07b9-493d-bc64-fb98c912376a)

Do you see anything strange in the inspector, maybe a global style overriding the toolbar CSS?

**Comment by trey** [comment]
Yep, that was the issue. Something with https://picocss.com seems to be messing with it.

**Comment by trey** [comment]
If anybody runs into a similar problem, this makes things look reasonable:

```postCss
#djDebug {
  input[type='checkbox'] {
    height: 0.75rem;
    width: 0.75rem;
    border-radius: 0.125rem;
  }

  svg.djdt-hidden {
    width: 0.8rem;
    height: 0.8rem;
  }
}
```
