### ISSUE TITLE
Version 4.4.1 changes the look of DRF browsable API

### ISSUE THREAD

**Issue by jeroenbrouwer** [jazzband/django-debug-toolbar#1922]
After upgrading to version 4.4.1 the browsable API suddenly becomes partly dark:
![image](https://github.com/jazzband/django-debug-toolbar/assets/13677331/f91f65e2-2e9b-4ac0-8d77-673177101523)

Whereas on version 4.3 it looks like this:
![image](https://github.com/jazzband/django-debug-toolbar/assets/13677331/90df066a-5cc5-4b46-aaa0-7031016b9542)

**Comment by matthiask** [comment]
I don't have a project ready with DRF; can you tell which CSS rule does this? Thanks in advance!

**Comment by matthiask** [comment]
Maybe those lines are the problem:
https://github.com/jazzband/django-debug-toolbar/blob/97b49d178b3c2d30cc92ff4fd4f0ecbdcb8bc137/debug_toolbar/static/debug_toolbar/css/toolbar.css#L14
https://github.com/jazzband/django-debug-toolbar/blob/97b49d178b3c2d30cc92ff4fd4f0ecbdcb8bc137/debug_toolbar/static/debug_toolbar/css/toolbar.css#L38

**Comment by matthiask** [comment]
@jeroenbrouwer It would be great if you could test #1923 !

**Comment by jeroenbrouwer** [comment]
Disabling this CSS property in Chrome dev-tools fixes it:
![image](https://github.com/jazzband/django-debug-toolbar/assets/13677331/0b2990ca-f2e4-4f5c-a8d0-83f6bdf1cf7f)

**Comment by matthiask** [comment]
Thanks. Yes, I thought that this was the case. TBH I was unsure if this property was even needed when merging the PR.

**Comment by matthiask** [comment]
Thanks for confirming!

**Comment by jeroenbrouwer** [comment]
> Thanks for confirming!

No worries, thanks for the very fast fixing of this issue!
