### ISSUE TITLE
There is a delay in response to requests.

### ISSUE THREAD

**Issue by YoussufShakweh** [jazzband/django-debug-toolbar#1937]
Maybe the problem is caused by the middleware.

**Comment by tim-schilling** [comment]
When reporting an issue you should try to provide a way to reproduce the issue, an explanation of what you expect to happen and what actually happens.

I suspect this is from the docker hostname check which is known to slow things down, but it's impossible to know for sure.

The SQL panel can also slows things down when you have many or large queries.

If you can start pinpointing the issue or provide a reproducible environment, please reopen the issue.
