### ISSUE TITLE
Dark mode text needs higher contrast

### ISSUE THREAD

**Issue by tim-schilling** [jazzband/django-debug-toolbar#1943]
The table, non-highlighted, text needs greater contrast with the background in dark mode:

It's currently at 1.73 according to https://coolors.co/contrast-checker/acc8e5-ffffff

<img width="1440" alt="Screenshot 2024-07-04 at 11 24 22 AM" src="https://github.com/jazzband/django-debug-toolbar/assets/1281215/e7745f1a-dca4-4b76-b151-a0ae694dee3b">

**Comment by myou1985** [comment]
In a Windows11 environment, this was reproduced when the OS mode was "Light" and the app mode was "Dark".
Contrast is important, but wouldn't it be better for the app's style to follow the OS mode?

OS mode:Lignt , App mode:Lignt:
![OSLight-AppLight](https://github.com/user-attachments/assets/51ea15a4-89e7-4bc5-992d-f8751fd50e38)

OS mode:Light , App mode:Dark:
![OSLight-AppDark](https://github.com/user-attachments/assets/87ac9c78-499a-4e01-8cb0-7c46f9fd7d45)

OS mode:Dark , App mode:Light:
![OSDark-AppLight](https://github.com/user-attachments/assets/eca8fda5-6362-48d2-a526-eca63d80b696)

OS mode:Dark , App mode:Dark:
![OSDark-AppDark](https://github.com/user-attachments/assets/a9fbc046-9ea1-4eeb-900b-22d362901c77)

**Comment by myou1985** [comment]
I hope that the information at the following URL will be helpful regarding contrast.
https://w3c.github.io/wcag/techniques/general/G18

**Comment by tim-schilling** [comment]
@tokibito @myou1985 thank you for bringing up reflecting the OS mode. That'd be a reasonable default.

Do either of you have the availability to make these changes? I'd love to see these changes included in the toolbar.

**Comment by myou1985** [comment]
@tim-schilling
Thank you for your response. I will find some time to address this issue on my end.

**Comment by myou1985** [comment]
@tim-schilling
I have submitted my first pull request to this project, 
and I would really appreciate it if you could take a look when you have the time.

This is my first contribution to an open-source project, 
so any feedback or suggestions for improvement would be incredibly valuable to me.
