### ISSUE TITLE
Recast sentence

### ISSUE THREAD

**Issue by Dr-Bernard** [jazzband/django-debug-toolbar#1966]
Under the "Django Channels & Async" subsection of the "Troubleshooting" section of the INSTALLATION page, the sentence "If you are using Django channels are having issues getting panels to load, please review the documentation for the configuration...." seems incomplete.

For a better understanding of the instruction, kindly consider recasting the sentence, as follows: "If you are using Django channels '_**and you**_' are having issues getting panels to load, please review the documentation for the configuration..."

I added the two words 'and you' to the sentence as shown above.

Thank you.

**Comment by tim-schilling** [comment]
Thanks for identifying the issue, would you like to open a PR with the fix?

**Comment by Dr-Bernard** [comment]
> Under the "Django Channels & Async" subsection of the "Troubleshooting" section of the INSTALLATION page, the sentence "If you are using Django channels are having issues getting panels to load, please review the documentation for the configuration...." seems incomplete.

@tim-schilling I have opened a PR and it has been successfully merged. Thank you

**Comment by Dr-Bernard** [comment]
This issue is now fixed as the sentence under the "Django Channels & Async" subsection of the "Troubleshooting" section of the INSTALLATION page, is now complete. 

Good job team.
