### ISSUE TITLE
Update information in toolbar after htmx request

### ISSUE THREAD

**Issue by thacoon** [jazzband/django-debug-toolbar#1997]
I have a django application that uses htmx. So when I load a page I see the debug toolbar and e.g. all SQL queries that were executed. When I now click on a button that triggers a htmx request and some view response with a htmx response that replaces or add somethings to the DOM like a modal/sidebar/.... In the view some SQL queries where executed as well, but the debug toolbar does not update any of the information, it is still the same as were shown after I loaded the initial page.

I would have expected it to update the information. Is this something that does not work at the moment?

I added all my configuration regarding debug toolbar below:

In my _django.py_ settings file:
```py
# Debug Toolbar
IS_RUNNING_TESTS = 'test' in sys.argv

if DEBUG and not IS_RUNNING_TESTS:
    INSTALLED_APPS += ['debug_toolbar',]
    MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware',]


def show_toolbar(request: HttpRequest) -> bool:
    if DEBUG and not IS_RUNNING_TESTS:
        if request.META['REMOTE_ADDR'] not in INTERNAL_IPS:
            logger.error(
                'Local remote address not found in internal IPs',
                error={'remote_addr': request.META['REMOTE_ADDR'], 'internal_ips': INTERNAL_IPS},
            )
        return True


DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': show_toolbar,
    'INSERT_BEFORE': '<head>',
    'ROOT_TAG_EXTRA_ATTRS': 'hx-preserve',
}

INTERNAL_IPS = [
    '127.0.0.1',
    'localhost',
    '192.168.176.1',  # Internal docker ip
]
```

In my _urls.py_:
```py
if DEBUG and not IS_RUNNING_TESTS:
    urlpatterns += debug_toolbar_urls()
```

In my __base.html_ template:

In the header:
```html
    {% if debug %}
      <script>
          document.addEventListener('htmx:afterSettle', (event) => {
              if ('djdt' in window) {
                  window.djdt.init();
              }
          })
      </script>
    {% endif %}
```

At the end:
```html
  {% if debug %}
    <script>
        if (typeof window.htmx !== 'undefined') {
            htmx.on('htmx:afterSettle', function(detail) {
                if (
                    typeof window.djdt !== 'undefined' &&
                    detail.target instanceof HTMLBodyElement
                ) {
                    djdt.show_toolbar();
                }
            });
        }
    </script>
  {% endif %}
```

**Comment by tim-schilling** [comment]
A few other questions:
- Does the history panel show the requests?
- What versions of django, the toolbar are you using?
- Are you using async views or channels?
- The line `'INSERT_BEFORE': '<head>',` seems incompatible. The toolbar should be inside of the `body` tag at least.

**Comment by thacoon** [comment]
@tim-schilling thanks for the quick reply, my answers:

_Does the history panel show the requests?_
Yes, the request are shown in the history panel

_What versions of django, the toolbar are you using?_
toolbar: version = "4.4.6"
django: version = "5.1"

_Are you using async views or channels?_
No,  I don't use any async views or channels.

_The line 'INSERT_BEFORE': '<head>', seems incompatible. The toolbar should be inside of the body tag at least._
I also had `</head>` and did not setting 'INSERT_BEFORE' at all. But having it like this it is not flickering anymore for me when a new page is loaded. All different variants seem to behave the same for me, except that the toolbar is flickering when I don't set it like this.

I also noticed that after I opened a modal the toolbar does not react to any input, but when I open it a second time it reacts to input again. But I guess this is not related, maybe something with my CSS, idk yet? Also for this changing _INSERT_BEFORE_  to `</head>` or don't set it all does not change anything.

**Comment by tim-schilling** [comment]
I'm having a tough time fully understanding what's happening and what you'd like to change. If the toolbar has the history panel and the htmx requests show up in there after clicking refresh (or enabling `UPDATE_ON_FETCH`), to me that means the toolbar is working as expected.

If you're replacing the entire DOM and want the toolbar to be supported, you may need to tell htmx to not swap that part.

**Comment by thacoon** [comment]
Oh, I was not aware about `'UPDATE_ON_FETCH': True`, that does exactly what I wanted. Thanks for your time :)

I still have a bug that when I every other htmx request, the toolbar becomes frozen (clicking does not do anything) and after doing another htmx request it works again (clicking on e.g the SQL button opens the sql view). But for that I guess I need to make some small reproducible example.

**Comment by thacoon** [comment]
Oh, I was not aware about 'UPDATE_ON_FETCH': True, that does exactly what I wanted. Thanks for your time :)

I still have a bug that when I every other htmx request, the toolbar becomes frozen (clicking does not do anything) and after doing another htmx request it works again (clicking on e.g the SQL button opens the sql view). But for that I guess I need to make some small reproducible example.

**Comment by thacoon** [comment]
For anyone who comes across this, having `'INSERT_BEFORE': '<head>', is not good, mixes up the whole html structure. I had importmaps that stopped working and all my <head> content was moved into the <body> content. Only use </head> or </body>, but it now flickers again for me when I load a new page.

**Comment by mecampbellsoup** [comment]
So, is `UPDATE_ON_FETCH: True` the "fix" for flickering observed with DDT when paired w/ HTMX? If so, do the docs need to be updated? https://django-debug-toolbar.readthedocs.io/en/latest/installation.html#htmx

**Comment by tim-schilling** [comment]
@mecampbellsoup yeah, there's an improvement to be made somewhere there. Any chance you can create a PR to help out?
