### ISSUE TITLE
Installation docs don't include how to edit the '__debug__' prefix

### ISSUE THREAD

**Issue by tankorsmash** [jazzband/django-debug-toolbar#2010]
Thanks for making a wonderful tool!

https://django-debug-toolbar.readthedocs.io/en/latest/installation.html

> ```python
> urlpatterns = [
>     # ... the rest of your URLconf goes here ...
> ] + debug_toolbar_urls()
> ```

> By default this uses the `"__debug__"` prefix for the paths, but you can use any prefix that doesn’t clash with your application’s URLs.

In older versions of the docs, eg [v3.8](https://github.com/jazzband/django-debug-toolbar/blob/3.8/docs/installation.rst), the example code included the url path literally:

```python
urlpatterns = [
    # ...
    path('__debug__/', include('debug_toolbar.urls')),
]
```

Not sure what the correct way of doing changing the prefix is now, and the current text is a little confusing.

**Comment by tim-schilling** [comment]
I don't disagree the current text is a bit confusing. We should probably remove it, but I'm not in favor of adjusting the install page to cover that case.

Specifically, you can look at the `debug_toolbar_urls` function definition to understand what you can replace it with.

**Comment by tankorsmash** [comment]
Thanks, I'll close the issue
