### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by mikoumed** [jazzband/django-debug-toolbar#2011]
I am getting this issue when trying to display sql queries 
`s1 = 0 if stats[3] == 0 else s * (stats[3] / self.stats[3])`
looks like the self.stats[3] can be equal to 0

**Comment by tim-schilling** [comment]
Can you share how this is happening and what stats is set to? This may help us write a test.

**Comment by matthiask** [comment]
We're dividing by `self.stats[3]` and checking `stats[3]` for zero. This is definitely broken.

@mikoumed Feedback on #2015 would be appreciated.
