### ISSUE TITLE
Filtering by requested URL

### ISSUE THREAD

**Issue by gw0** [jazzband/django-debug-toolbar#284]
I know that with the callback function one can implement his own complex mechanism of deciding when to display the Django Debug Toolbar and when not, but common filtering use cases (like checking users IP) should be made as simple as possible.

Therefore I suggest an configuration option to _filter out (not show) the toolbar on pages whose URLs match a specific pattern_ (or regular expression). E.g. if you are using the Django admin panel, but not developing enything in it, you do not need the debug toolbar there, so it would be nice to filter out the toolbar on all requests under `'^admin/'`. Same need appears if you have a page with many small iframes and you just want to debug the outside Django app and templates, not the ones in the small iframes - here it would be nice to hide the toolbar on all requests to the iframed app.

Suggestion is therefore to have one or more regular expressions for filtering where the toolbar should be shown based on the requested URL. E.g. either as a complex regex or as a list of simpler regexes:

```
DEBUG_TOOLBAR_CONFIG = ( ... 'HIDE_FILTER_URL': '^admin/|^myapp/someview', ... )
or
DEBUG_TOOLBAR_FILTER_URL = ('^admin/', '^myapp/someview')
```

**Comment by craiga** [comment]
For anyone else landing here, it seems that the `from debug_toolbar.middleware import show_toolbar` line triggers an early evaluation of Django Debug Toolbars' settings, meaning that any subsequent changes to settings won't be read. I needed to do the import inside the function in order to have my settings take effect.

```python
def custom_show_toolbar(request):
    from debug_toolbar.middleware import show_toolbar

    return show_toolbar(request) and not request.path.startswith("/graphql")

DEBUG_TOOLBAR_CONFIG = {"SHOW_TOOLBAR_CALLBACK": custom_show_toolbar}
```
