### ISSUE TITLE
Problem with database routers in recent versions

### ISSUE THREAD

**Issue by dnmellen** [jazzband/django-debug-toolbar#457]
Hi, I noticed that django-debug-toolbar crashes when you have a django project that uses database routers. I made a test repo that reproduces the error:

https://github.com/dnmellen/issue-dbrouter-django-debug-toolbar

I checked that the last working commit was https://github.com/django-debug-toolbar/django-debug-toolbar/commit/6a8526a93b60ebae214dbe0d4cbf172c311802b9, but newer commits will fail.

**Comment by jedie** [comment]
It seems that i have a related problem.
I get **OperationalError: no such table: django_site** if **'debug_toolbar'** is in **INSTALLED_APPS** and run **migrate** (on a empty database)

If i remove **'debug_toolbar'** the **migrate** runs fine.

Maybe related to: https://github.com/divio/django-cms/issues/2561 ?

**Comment by aaugustin** [comment]
Your issue seems unrelated. Are you using the explicit setup described in the documentation?

**Comment by jedie** [comment]
Do you mean to better use the http://django-debug-toolbar.readthedocs.org/en/1.2.2/installation.html#explicit-setup ?

Currently i only add 'debug_toolbar' to **INSTALLED_APPS**
