### ISSUE TITLE
Improve the CSS

### ISSUE THREAD

**Issue by aaugustin** [jazzband/django-debug-toolbar#476]
We're mostly backend people, but I'm pretty sure we can do better...

**Comment by ngzhian** [comment]
I chanced upon rack-mini-profiler [0] while listening to a podcast [1], and checked out a video [2] about how it works. I thought it looked really simple and clean, and would like to suggest updates to the style for debug toolbar in the direction of that project.
Would the maintainers like to take a quick look? Will be happy to work on this if the core team is interested, thanks!

[0] https://github.com/MiniProfiler/rack-mini-profiler
[1] http://bikeshed.fm/17
[2] http://railscasts.com/episodes/368-miniprofiler

**Comment by tim-schilling** [comment]
What did you have in mind for style changes? The toolbar currently expects that panels remain exclusive of each other. The rack-mini-profiler shows a general overview that contains data that exists across a few of the toolbars panels.

**Comment by bionikspoon** [comment]
Suggestion:

![screen shot 2015-09-18 at 13 52 27](https://cloud.githubusercontent.com/assets/5052422/9968235/ebb012b4-5e0c-11e5-95db-0a0dac4fc09d.png)

This button is the "go back" button.  But it's on the right side, pointing right.  In almost every context, that's the convention to go forward, not back.  I hope I'm not the only one that ends up clicking "back" on my browser.

The suggestion is that nav could be an ounce more intuitive and conventional.

**Comment by aaugustin** [comment]
Regarding namespacing, we try to prefix everything with `djdt-`.

**Comment by j127** [comment]
I think that the toolbar CSS might get overridden by Bootstrap too. I'm trying it with Bootstrap 4, which contains this:

```
[hidden],
template {
  display: none;
}
```

...which causes the Debug Toolbar to disappear, because it contains: `<div id="djDebug" hidden="hidden"...`

**Comment by jdufresne** [comment]
I think the of improving the UI/UX through better CSS is very welcome, but the goals of this issue are a bit nebulous with no clear end in sight. So closing.

To any reading or participating, please feel free to open PRs improving the UI. Also please feel free to open new issues that identify specific UI issues that can be acted on.

> which causes the Debug Toolbar to disappear, because it contains: <div id="djDebug" hidden="hidden"...

This was fixed in 4111d930327f10a47c8bcc6b46f21d5aa62d4460.
