### ISSUE TITLE
SHOW_TOOLBAR_CALLBACK no longer supports lambda

### ISSUE THREAD

**Issue by ross** [jazzband/django-debug-toolbar#523]
in my setup i always have seperate dev settings and in those settings i enable debug toolbar for all requests. i've always done that with the following config

```
DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': lambda request: True,
}
```

after updating my virtualenv this morning i started getting errors that i've tracked down to trying to run rsplit on func_path

line 45 of debu_toolbar/middleware.py:

```
    mod_path, func_name = func_path.rsplit('.', 1)
```

it looks like the meaning of SHOW_TOOLBAR_CALLBACK may have changed to require a string and not support a callable. if that's the case i'm not sure what the solution would be. i'd rather not have to define a function somewhere and point this at it just to return true. i'd prefer if SHOW_TOOLBAR_CALLBACK supported being presented a callable.

**Comment by Simanas** [comment]
Spend more than an hour on this until I finally got it working on my dev server. This is so frustrating! It is impossible to save idiots from making stupid mistakes. They will still find many workaround and do stupid security shit. Default security measures just makes this wonderful tool so complicated and frustrating to work with. I just want to plug and play with it. Will take over security stuff my self as I am a developer and that's my job. 

All of this is completely out of the scope of The Zen of Python: https://www.python.org/dev/peps/pep-0020/

There should be no additional options at all for displaying toolbar or not. If you have it in your installed apps it's displayed if not, it's not displayed. That's it. Leave everything else for developers to decide.

Anyway, thanks for running this amazing tool! I am a huge fan of it, except for these stupid security measures.

**Comment by chris-martin** [comment]
:+1: for simplicity. A dict with a string that resolves to a function that evaluates to a boolean that determines whether to expose potentially sensitive information doesn't seem to respect "economy of mechanism" as a security principle.

**Comment by Rabia23** [comment]
I couldn't get a clear picture of not supporting lambda.
This is what I am trying to achieve but unable to do so.

```
DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': lambda request: DEBUG,
}
```
It's not picking up the DEBUG value.

However, the below code is working fine.

```
DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': lambda request: True/False,
}
```

Any help would be highly appreciated.

Thanks.

**Comment by tim-schilling** [comment]
@Rabia23 you could define a function rather than a lambda:

```
def show_toolbar(request):
    from django.conf import settings
    return settings.DEBUG

DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': show_toolbar,
}
```

Alternatively since DEBUG should change, you could use a ternary operation.

```
DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': (lambda request: True) if DEBUG else (lambda request: False),
}
```
