### ISSUE TITLE
404 Error when clicking on toolbar

### ISSUE THREAD

**Issue by lfigueira** [jazzband/django-debug-toolbar#568]
Hi, 

I've installed DDT using the explicit setup described in the documentation. The toolbar appears correctly, but when I click on any of the panels, I always get 404 Not Found errors:

```
[25/Mar/2014 23:31:44] "GET /__debug__/render_panel/?store_id=0020c69907dd48d9b76ff11d9ff46d0c&panel_id=TimerPanel HTTP/1.1" 404 1673
[25/Mar/2014 23:31:53] "GET /__debug__/render_panel/?store_id=0020c69907dd48d9b76ff11d9ff46d0c&panel_id=LoggingPanel HTTP/1.1" 404 1675
```

I'm running Python 2.7.6, and also using Mezzanine - these are their versions:

```
Django==1.6.1
Mezzanine==3.0.7
django-debug-toolbar==1.0.1
```

I've already searched for this issue for quite a while, but can't seem to find a solution. Many thanks for your help!

Luis

**Comment by SalahAdDin** [comment]
I don't understand you, how did you solve?

**Comment by aaugustin** [comment]
By putting the debug toolbar's URLs before the CMS' "catch all" URL pattern, so they're handled by the debug toolbar and not the CMS.

**Comment by SalahAdDin** [comment]
I have the same problem with Wagtail but i don't know how solve it.

**Comment by aaugustin** [comment]
Use the explicit setup (see the debug toolbar's documentation for details) and put 
```python
url(r'^__debug__/', include(debug_toolbar.urls)),
```
before
```
url(r'', include(wagtail_urls)),
```
in your `urlpatterns`.

**Comment by SalahAdDin** [comment]
Without `if debug`???

**Comment by aaugustin** [comment]
I'm sorry but I don't know how I can help you further. At some point you need to understand how these things work.

**Comment by SalahAdDin** [comment]
```
from django.conf import settings
from django.conf.urls import include, url

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
```

Have i put it before `Wagtail` urls.

**Comment by aaugustin** [comment]
Do this:
```
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
```

**Comment by SalahAdDin** [comment]
Oh, this could be works, than you, i'll test it and then i say you guys.

**Comment by bubakanov** [comment]
For me works with re_path:
```
from django.urls import include, path, re_path


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
```
