### ISSUE TITLE
[django-subdomains] u'djdt' is not a registered namespace

### ISSUE THREAD

**Issue by fangsterr** [jazzband/django-debug-toolbar#592]
Alas, I was really looking forward to upgrading from the beta version to 1.x, but when I visit my website at api.website.com, I get `NoReverseMatch: u'djdt' is not a registered namespace` . I'm using the popular django-subdomains project to support wildcard domains.

Line 14 on `debug_toolbar/templates/debug_toolbar/base.html` . Related to #529 . Unlike the issue, my site does load on the regular website.com endpoint, just not on any wildcard subdomains.

**Comment by mrben** [comment]
Just wanted to add for people coming via Google that the [explicit setup](http://django-debug-toolbar.readthedocs.org/en/1.3/installation.html#explicit-setup) works for me when using wildcard subdomains. Just remember to add the debug-toolbar URL patterns to all your root URL configs.
