### ISSUE TITLE
No sql stacktrace

### ISSUE THREAD

**Issue by chokosabe** [jazzband/django-debug-toolbar#654]
I've installed django debug toolbar and all the panels apart from the sql panel seem to work.

On opening the sql panel I get the messages:

SQL queries from 0 connections
No SQL queries were recorded during this request.

My settings.py:

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'silk.middleware.SilkyMiddleware',
    'pagination.middleware.PaginationMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
)
# Add the debug toolbar

if DEBUG:
    DEBUG_TOOLBAR_PATCH_SETTINGS = True
    ENABLE_STACKTRACES = True
    INSTALLED_APPS += (
        'debug_toolbar',
    )
    INTERNAL_IPS = ('10.0.2.2', '127.0.0.1', '0.0.0.0',)

Any ideas or any steps I can take to further debug this? Thanks. The only thing that is affected is the SQL stacktrace...

**Comment by miraculixx** [comment]
Just found that if you have 'debug_toolbar.middleware.DebugToolbarMiddleware', twice in MIDDLEWARE_CLASSES for whatever reason, the same thing happens (always No SQL queries were recorded during this request.)

**Comment by cjensen2k** [comment]
Having the middleware twice exactly the problem for me.

**Comment by Mikebarson** [comment]
None of what was mentioned here worked for me. I'm still getting the 0 SQL queries in the panel.

I have this in my INSTALLED_APPS

`INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'debug_panel',
    'rest_framework',
    'yahshua_intelex',
    'corsheaders',
    'apis.apps.ApisConfig',
    'rest_framework.authtoken',
   'my_app'
]`

And this in my middleware 

`MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_panel.middleware.DebugPanelMiddleware',   
    'my_app.middleware.middleware.RequestProcessor',
]`

**Comment by matthiask** [comment]
@Mikebarson The `debug_toolbar` middleware is missing from your `MIDDLEWARE_CLASSES`, resp. you only have `debug_panel` there which is a different thing, and I'm not sure whether it works the same way.

**Comment by smsa1995** [comment]
you should select 'history' of panel, then select your endpoint (e.g. /persons/)  with clicking on 'switch' button 
and  finally select 'SQL' of panel and see generated sql.
