### ISSUE TITLE
Expand built-in features

### ISSUE THREAD

**Issue by dcramer** [jazzband/django-debug-toolbar#658]
I have a need to expand the panels available to include a bunch of services that Sentry uses.

As part of this I'm likely going to be adding some utilities that I've written for newer-versions of my patching/tracing code. If someones interested this could be the early stages of a rewrite of of the toolbar, into something thats much easier to extend.

A lot of this is inspired by something I prototyped recently:

https://github.com/dropbox/pytest-call-tracer

Specifically it should be dead simple to add a new collector (which is what 90% of debug toolbar's usefulness comes from):

```
    self.add_context(PatchContext(
        'MySQLdb.connections.Connection.query', 
        FunctionWrapper(self._calls, 'mysql')
    ))
```

For now I'm just going to work on getting some of the helpers in, but not replacing any of the code, but ideally we could have a CallRecorderPanel that just gives you a record method and makes it super easy to patch things.

**Comment by jdufresne** [comment]
Improvements to the API to allow for custom extensions are very welcome, but this issue is quite nebulous in goals. So closing for that reason.

In the meantime, please feel free to put up PRs that explain their goal for third party extensions.
