### ISSUE TITLE
Enabling debug_toolbar seems to break logging from management commands

### ISSUE THREAD

**Issue by cancan101** [jazzband/django-debug-toolbar#695]
When I add `debug_toolbar` to my `INSTALLED_APPS`, calls to `logging` `logger` seems no longer work from within a management command.

**Comment by tim-schilling** [comment]
Can you please provide us with a test case?

**Comment by cancan101** [comment]
https://www.dropbox.com/s/oifjoqqxsrizzew/debug_toolbar_issue.zip?dl=0
the command is `check_log`. You can see that toggling the `debug_toolbar` app in the settings.py file changes the log behavior.

**Comment by aaugustin** [comment]
This may be related to 7d29b40c70dbc1f0996b9342254f32705eba1b67.

**Comment by gfairchild** [comment]
I'm not sure if this is related to this issue (I suspect it is), but logging seems completely broken for me with DDT 1.3.0. I have numerous `logging.debug` calls scattered throughout my code, and DDT is no longer picking them up. I reverted to 1.2.2, and logging resumes working.

I'm using Python 3.4.x and Django 1.7.7.

If you want me to create a new issue, let me know.

**Comment by tim-schilling** [comment]
@gfairchild Do you know what your `root.logging.level` is set to?

**Comment by gfairchild** [comment]
@tim-schilling, I'm sorry, but I googled around and can't find any references to `root.logging.level`. What is that, and how do I report my value to you?

**Comment by gfairchild** [comment]
Actually, it looks like `logging.getLogger().getEffectiveLevel()` gets that value. I missed a SO thread on it. That function returns 0, which tells me my logger's root logging level is `NOTSET`.

**Comment by tim-schilling** [comment]
Sorry about that. I meant ```logging.root.level```. I typed it out wrong. I'll try to recreate your scenario.

**Comment by gfairchild** [comment]
I just updated to Django 1.8, and logging still isn't working, so I'm guessing this is a DDT bug.

**Comment by dkrnl** [comment]
Yes, i catch similar bug: "No messages logged" in logging panel.
After update from Django 1.7 (logging working well) to 1.8 version.

**Comment by tim-schilling** [comment]
@gfairchild @dkrnl Can you try adding the following code to your settings file?

```
import logging
logging.root.setLevel(logging.NOTSET)
```

**Comment by gfairchild** [comment]
That seems to have fixed the issue!

**Comment by tim-schilling** [comment]
Glad it worked for you! That problem is actually different than the
original issue which I'm still looking into.

**Comment by tim-schilling** [comment]
@cancan101 Were you using ```BasicConfig``` in your actual code? If so, then I don't think this is a bug with the toolbar. The reason being is that ```BasicConfig``` will only add a ```StreamHandler``` if there are no other handlers on root. The toolbar adds a handler, thus it doesn't create the ```StreamHandler``` and you don't see the output in the console. [Here are the docs on it](https://docs.python.org/2/library/logging.html#logging.basicConfig).

You can get the logging to work for your example if you add a django handler for that command. The code is:

```
import sys
LOGGING = {
    ...
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
        }
    },
    'loggers': {
        'app.management.commands.check_log': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    }
}
```

**Comment by cancan101** [comment]
Interesting. 

I wonder though why I don't see this same issue with other third party apps or even with Django itself. Perhaps the call that django-debug-toolbar makes to add Handers needs to be deferred?

It appears that the handler is added so early that I no matter where I put the call to `logging.basicConfig` in my code, it I am have included the `django-debug-toolbar`, I am always too late.

**Comment by tim-schilling** [comment]
Yes, that would be the only way to solve your particular problem within the toolbar.

**Comment by gfairchild** [comment]
I know my issue above turned out not to be related to this issue, but I figured out why I needed to add this:

```
import logging
logging.root.setLevel(logging.NOTSET)
```

to my settings file. The reason is because I was logging using the logging module directly; I wasn't getting the appropriate logger. In other words, I was doing this:

```
import logging
logging.debug('message')
```

when I should have been doing this:

```
import logging
logger = logging.getLogger(__name__)
logger.debug('message')
```

If I use the logging module appropriately by calling `getLogger`, I don't need those 2 lines of code in the settings file. Just wanted to throw this out there in case anyone else encounters this issue.

**Comment by bluisier** [comment]
Hi Everybody,
I'm having the same issue but can't make it that the logs appear in the logging panel.

When DjDT is not activated, my logs shows perfectly in the terminal and are written to my log file. But as soon as I activate DjDT, my app logs are not showing in the terminal anymore and nothing appears in the logging panel of DjDT... all the logs are still written to the file though

I've tried to add a handler for the command mentionned by @tim-schilling without success. Any help/hints would be greatly appreciated (if I can make logging works, DjDT would really be the ultimate debugging tool for Django)

Here are my settings for logging:
```python
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format' : "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt' : "%d/%b/%Y %H:%M:%S"
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'mysite.log',
            'formatter': 'verbose'
        },
    },
    'loggers': {
        'django': {
            'handlers':['file'],
            'propagate': True,
            'level':'INFO',
        },
        'fullText_extraction': {
            'handlers': ['file'],
            'level': 'INFO',
        },
    }
}
```

**Comment by tim-schilling** [comment]
Can you try specifying the full path to your management command for the loggers key?

**Comment by bluisier** [comment]
I'm not sure to understand what you mean @tim-schilling ... you want me to run manage.py with full path? or smth else? sorry about that...

**Comment by tim-schilling** [comment]
I mean run it with:
```
LOGGING = {
    ...
    'loggers': {
        ...
        'python.path.to.fullText_extraction': {
            'handlers': ['file'],
            'level': 'INFO',
        },
    }
}
```
But replacing the ```python.path.to.``` with the path that's relevant for your project.

**Comment by bluisier** [comment]
If I do that @tim-schilling , nothing happens anymore --> no logs in the terminal, nothing in the logging panel of DjDT and logs are not written in my log file anymore.

**Comment by tripples** [comment]
Hi,

I am facing same issue. I tried to repro with minimal app. Issue occurs  when I add debug toolbar to installed apps.
https://github.com/tripples/logissue_with_debug_toolbar
