### ISSUE TITLE
Error with MySQL/Postgres database using % in direct SQL

### ISSUE THREAD

**Issue by vaal-** [jazzband/django-debug-toolbar#705]
TypeError: not enough arguments for format string

I am using SQL formatting dates in view.
DATE_FORMAT(payment_date, '%Y-%m-%d') as date
There are no parameters.

This is probably connected with this
https://code.djangoproject.com/ticket/9055
https://github.com/django/django/commit/76aecfbc4b49f5ab0613cccff1df6fab03253fab

https://github.com/django-debug-toolbar/django-debug-toolbar/blob/master/debug_toolbar/panels/sql/tracking.py#L158

**Comment by tim-schilling** [comment]
Have you tried using ```DATE_FORMAT(payment_date, '%%Y-%%m-%%d') as date```?

**Comment by vaal-** [comment]
This variant is work only with debug panel.

If disable panel sql request remains in the same form - DATE_FORMAT(payment_date, '%%Y-%%m-%%d') as date . Which leads to a wrong response from database.

**Comment by tim-schilling** [comment]
I'm having difficulty reproducing your problem. What version of Django are you using? What's the query you're using? How exactly is it breaking?

**Comment by vaal-** [comment]
https://www.dropbox.com/s/t6gsoe63y0xox5z/django_debug_toolbar_bug.zip?dl=0
Here is an example project with reproduction problems

I used: Django 1.8, Python 2.7, MySQL-python 1.2.4, django-debug-toolbar 1.3.0
need to run manage.py syncdb and create 1 user

then open URLs
http://127.0.0.1:8000/bug1/
http://127.0.0.1:8000/bug2/
with enabled debug_toolbar
and then without debug_toolbar

Sorry for the long answer, there was no time.

**Comment by tim-schilling** [comment]
I'm having difficulty building the environment for your test example. Before I invest more time in it, can you please try upgrading MySQL-python to 1.2.5?

**Comment by vaal-** [comment]
I've updated, the problem still exist.
Describe your typical environment - I check it.

**Comment by IlianIliev** [comment]
I can confirm that the issue exists only if Debug toolbar is ON. Otherwise it works fine.

**Comment by tim-schilling** [comment]
This is a problem with postgres as well as per #745

**Comment by tim-schilling** [comment]
This was fixed in #735
