### ISSUE TITLE
Deprecation Warning in Django 1.9

### ISSUE THREAD

**Issue by jannh** [jazzband/django-debug-toolbar#764]
> RemovedInDjango20Warning: Passing a 3-tuple to django.conf.urls.include() is deprecated. Pass a 2-tuple containing the list of patterns and app_name, and provide the namespace argument to include() instead.
>   url(r'^**debug**/', include(debug_toolbar.urls)),

Is from line 220 in the settings.py and from the new urlconf in django 1.9

**Comment by aaugustin** [comment]
Indeed we should update the implicit setup code and the explicit setup docs, while preserving support for Django 1.7.

**Comment by aaugustin** [comment]
That didn't work well... reverting.

**Comment by merwok** [comment]
Any progress?  Can I help?

**Comment by matthiask** [comment]
This has been fixed in 1.7.
