### ISSUE TITLE
ReadTheDocs output for the "API for third-party panels" no longer contains the API

### ISSUE THREAD

**Issue by kezabelle** [jazzband/django-debug-toolbar#811]
See screenshot below, the whole Python API is gone. I'm guessing autodoc is no longer working?

![screen shot 2016-02-26 at 15 14 27](https://cloud.githubusercontent.com/assets/118377/13356106/a6986704-dc9b-11e5-975f-10f7be556b6b.png)

**Comment by aaugustin** [comment]
Oops, definitely a regression. Not sure what happened. Thanks for reporting it!

As a stopgap measure, you can look at the documentation source in this repository.

**Comment by matthiask** [comment]
I'll take a look if someone can give me access on the RTFD project? My profile is here: https://readthedocs.org/profiles/mk/

cc: @aaugustin @jezdez

**Comment by jezdez** [comment]
Ah, seems like installing https://github.com/jazzband/django-debug-toolbar/blob/master/requirements_dev.txt was missing. This should be fixed now but I can't see the results on the site yet, probably due to HTTP caching the doc pages. Let's revisit this later again..

**Comment by jezdez** [comment]
@matthiask I've added you anyways :)

**Comment by matthiask** [comment]
Thanks! Looks good now.
