### ISSUE TITLE
Compatible with Django 1.9

### ISSUE THREAD

**Issue by Jzarecta** [jazzband/django-debug-toolbar#838]
Is this project updated for 1.9?

**Comment by aaugustin** [comment]
Try it?

**Comment by galuszkak** [comment]
Hello @aaugustin! Thanks for awesome work on django-debug-toolbar.

Unfortunately this doesn't work for me with Django 1.9.7. I'm using Python 3.5 and Django 1.9.7.

What is strange when I include into `INSTALLED_APPS = Base.INSTALLED_APPS + ('debug_toolbar',)`

I've got hanging app. Django just freeze forever. When I cancel (Ctrl+C) the django process I got this stacktrace:

```  File "/usr/local/lib/python3.5/site-packages/configurations/__init__.py", line 38, in setup
    _setup()
  File "/usr/local/lib/python3.5/site-packages/configurations/__init__.py", line 17, in _setup
    django.setup()
  File "/usr/local/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.5/site-packages/django/apps/registry.py", line 71, in populate
    with self._lock:
```

It's maybe problem related to django-configurations. Feel free to ask whatever you need to find root cause of this problem. But without debug_toolbar it works fine, so probably this is combination of this issue.

**Comment by aaugustin** [comment]
Uh, annoying. Are you using the "explicit setup" described in the installation instructions?

**Comment by galuszkak** [comment]
No, I'm not using that.

**Comment by aaugustin** [comment]
There's a good chance the explicit setup will resolve the problem that causes this traceback, regardless of the version of Django being use.

Apps such as django-configurations are incompatible with the magic setup.

**Comment by valentjedi** [comment]
Hi, I currently use debug-toolbar with django 1.9.7 and Python 3.5 without any issues and manual configurations so it might be collisions with another addons.

**Comment by emorozov** [comment]
Django debug toolbar is incompatible with Django 1.9 in the automatic mode, because it hangs here:
```
def patch_root_urlconf():
    from django.conf.urls import include, url
    from django.core.urlresolvers import clear_url_caches, reverse, NoReverseMatch
    import debug_toolbar
    try:
        reverse('djdt:render_panel')
    except NoReverseMatch:
        urlconf_module = import_module(settings.ROOT_URLCONF)
        urlconf_module.urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlconf_module.urlpatterns
        clear_url_caches()
```

On the line `reverse('djdt:render_panel')`.
I'm reverting back to manual setup, but this problem requires attention.

**Comment by aaugustin** [comment]
I think the debug toolbar should drop the automagic setup.

**Comment by jdufresne** [comment]
> I think the debug toolbar should drop the automagic setup.

If this suggestion is serious, I have created PR to do so.

**Comment by aaugustin** [comment]
Well... Let's say 80% serious.

I actually believe that the automagic setup isn't a tractable concept.

But I'm not eager to take responsibility for removing it and deal with frustrated users.

**Comment by jdufresne** [comment]
What about using a deprecation path, similar to Django's strategy? We could deprecate the automatic setup for the next release with a loud warning, and remove in the following (or later) release.

**Comment by valentjedi** [comment]
I personally agree. Because with Django 1.10 automatic setup definitely doesn't work. I suppose because of new style middleware?

**Comment by rfj001** [comment]
The toolbar is not working for me in Django 1.9, even with the explicit setup. There are no errors in my application, but the toolbar does not show up.

**Comment by SalahAdDin** [comment]
Have problems with automatic setup, but doesn't crash with it.
