### ISSUE TITLE
Enable requires.io for @jazzband

### ISSUE THREAD

**Issue by webknjaz** [jazzband/django-debug-toolbar#863]
In my PR #858 I've added a badge locked to django-debug-toolbar organization, but I cannot enable requires.io for current one.

@jezdez || @topotropic could you plz do this and maybe enable automatic notifications about outdated requirements?

**Comment by jezdez** [comment]
@webknjaz Could you please file an issue on https://github.com/jazzband/roadies/issues as mentioned on https://jazzband.co/roadies so we have a track record why the service was enabled? Thanks!
