### ISSUE TITLE
sqlparse compatibility with Django Debug Toolbar 1.4

### ISSUE THREAD

**Issue by seroy** [jazzband/django-debug-toolbar#866]
In install requirements sqlparse must be less than 0.2

**Comment by aaugustin** [comment]
There's no way to re-release version 1.4 with different requirements. It will remain forever what it was when it was released. Version 1.5 fixes the incompatibility.

**Comment by seroy** [comment]
You can release version 1.4.1 that fixes requirements. It will be nice for users that uses Django<1.8.

**Comment by aaugustin** [comment]
I cannot condone the use of obsolete version of Django with unpatched security vulnerabilities. As far as I am concerned, I'd rather discourage it than facilitate it.

You can just pin the version of sqlparse in your requirements, like you pin the version of the toolbar.
