### ISSUE TITLE
Installation of Django Debug Toolbar: TypeError: __init__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by wigust** [jazzband/django-debug-toolbar#869]
If I do explicit setup, I have error like this guy.
https://stackoverflow.com/questions/38792686/installation-of-django-debug-toolbar-typeerror-init-takes-1-positional-a

With automatic installation, it only throws a warning, but toolbar doesn't show.
`?: (1_10.W001) The MIDDLEWARE_CLASSES setting is deprecated in Django 1.10 and the MIDDLEWARE setting takes precedence. Since you've set MIDDLEWARE, the value of MIDDLEWARE_CLASSES is ignored.`

**Comment by DFilipeS** [comment]
Having the same issue, 1.5 states in the changelog that it is compatible with Django 1.10 but fails even with a fresh install of Django 1.10.

**Comment by grillazz** [comment]
fi you replace `MIDDLEWARE`with `MIDDLEWARE_CLASSES` you will be fien with Django 1.10

**Comment by grillazz** [comment]
https://github.com/jazzband/django-debug-toolbar/issues/853

**Comment by matthiask** [comment]
Thanks, that's the same issue as #853, and there's also a pull request here: #864.
