### ISSUE TITLE
IE8 Support

### ISSUE THREAD

**Issue by hypoxia** [jazzband/django-debug-toolbar#87]
The toolbar does not work with the most recent version of IE8 running on Win7Pro. 

The issue seems to be css-related. Everything loads fine in FireFox, but when I try to run it in IE8, everything is just displayed plaintext at the bottom of the page (instead of being part of a nice sidebar).

**Comment by yuri1992** [comment]
IE8 don't support jQuery 2.1,
when i debugging on IE8 i just turn off the toolbar

**Comment by aaugustin** [comment]
This bug dates back to two years ago. At the time the toolbar used jQuery 1.x.
