### ISSUE TITLE
Fix Django 1.10 deprecation of MIDDLEWARE_CLASSES

### ISSUE THREAD

**Issue by pydolan** [jazzband/django-debug-toolbar#872]
MIDDLEWARE_CLASSES is deprecated in Django 1.10 and instead MIDDLEWARE will replace it at some point.

**Comment by aaugustin** [comment]
This was fixed in 388e177eb19a2b51f7663003a1aa509ee56bbb7a a month ago, unless you have something else in mind?

I think it's best to wait until all versions < 1.10 are no longer supported to change the documentation.

**Comment by pydolan** [comment]
I'm running toolbar v1.5, and I'm getting a warning from `manage.py runserver`: 

> ?: (1_10.W001) The MIDDLEWARE_CLASSES setting is deprecated in Django 1.10 and the MIDDLEWARE setting takes precedence. Since you've set MIDDLEWARE, the value of MIDDLEWARE_CLASSES is ignored.

If I remove debug_toolbar from installed apps, the warning goes away.  Here's the [django code that triggers the warning](https://github.com/django/django/blob/354acd04af524ad82002b903df1189581c51cabe/django/core/checks/compatibility/django_1_10.py). After grepping the toolbar code, I don't see what is triggering the error. Thoughts?

**Comment by aaugustin** [comment]
Ah that's because you're using the implicit setup. Use the explicit setup intsead, as recommended in the documentation.

**Comment by pydolan** [comment]
Ah great, that should fix it, although it looks like I'll have to wait till #864 gets merged into a release (currently getting the already-fixed error described in #869)
