### ISSUE TITLE
Django 1.10 functional middleware compatibility

### ISSUE THREAD

**Issue by ryankask** [jazzband/django-debug-toolbar#878]
``debug_toolbar.apps.is_middlware_class()`` is used in a check for middleware ordering issues.

It assumes that all middleware in ``MIDDLEWARE`` are classes and doesn't account for Django 1.10's functional middleware. 

If a functional middleware factory is present, it fails when it hits ``issubclass()`` since the first argument isn't a class.

I will try to submit a patch this weekend because I need to clone the project and get the test suite running but a simple solution would be tweak it:

```py
def is_middleware_class(middleware_class, middleware_path):
    try:
        middleware_cls = import_string(middleware_path)
    except ImportError:
        return
    try:
        return issubclass(middleware_cls, middleware_class)
    except TypeError:
        return False
```

Perhaps there is a more elegant check using the ``types`` module but I would need to read about Py2/3 compatibility.

**Comment by ryankask** [comment]
Submitted PR #879

**Comment by Benoss** [comment]
I think this is already covered in this
https://github.com/jazzband/django-debug-toolbar/issues/853
The pull request is already merged but no releases since

**Comment by matthiask** [comment]
Thanks!

@Benoss The check for middleware ordering is still there, and should be fixed if it fails now.

I'll test it in a project of mine and merge if I don't hit any additional problems.

**Comment by matthiask** [comment]
That's the same issue as #874 by the way. Closing this issue as duplicate.

**Comment by jhancia** [comment]
Any chance we could have a new PyPi release to incorporate these changes? Thank you so much!
