### ISSUE TITLE
DebugToolbarMiddleware.__init__ does not accept get_response required argument

### ISSUE THREAD

**Issue by DylanYoung** [jazzband/django-debug-toolbar#886]
This means that it doesn't work on Django1.10, unless I'm misunderstanding something.

**Comment by DylanYoung** [comment]
Looks like this is fixed in master, but not updated on PyPi

**Comment by alexington** [comment]
Would love a updated PyPi release for this package!

**Comment by DylanYoung** [comment]
In mean time: `pip install -e git+git:https://github.com/jazzband/django-debug-toolbar.git#egg=django-debug-toolbar`

**Comment by aaugustin** [comment]
I just released version 1.6.
