### ISSUE TITLE
Django debug toolbar 1.4 does not support django 1.7

### ISSUE THREAD

**Issue by pyghassen** [jazzband/django-debug-toolbar#887]
Can please drop backwards compatibility for django 1.7 on django debug toolbar 1.4, because the test did not really covered that django version because on travis logs it was installing django 1.8 instead
![screenshot from 2016-10-11 11-18-47](https://cloud.githubusercontent.com/assets/607725/19265259/b705129c-8fa4-11e6-9fa3-d0e0de825c9b.png)

So these tests should be fail instead of succeeding.

**Comment by aaugustin** [comment]
Unfortunately there's no way we can change the 1.4 release retroactively. This problem has been solved in subsequent releases.

If I missed something, please clarify what changes you would like to make.

**Comment by matthiask** [comment]
The current, maintained version of django-debug-toolbar is 1.6, the probability that anything will happen on 1.4.x is really small (except if someone does the work of actually fixing issues and convincing me that the fixes are worth it).

Or as Aymeric said maybe I misunderstood something. Feel free to reopen the issue in this case.

Thanks!

**Comment by aaugustin** [comment]
There are no maintenance releases for the Debug Toolbar. Releases are made in linear order, always from master.
