### ISSUE TITLE
whitenoise

### ISSUE THREAD

**Issue by oppianmatt** [jazzband/django-debug-toolbar#891]
Using django debug toolbar and whitenoise can lead to poor performance as the django toolbar processes each static media request.

What would be a good way to run both of them?

Asked whitenoise but it might be better in here
https://github.com/evansd/whitenoise/issues/109

**Comment by matthiask** [comment]
The issue you reference mentions adding the whitenoise middleware before DDT's middleware. Does that work? And if not, what are the problems?

Media file serving in development is always slow. Or, are you running DDT on your production servers?

**Comment by oppianmatt** [comment]
Note that debug toolbar middleware recommends going first, but it works better if it's after whitenoise which should be first. Ala:

```
if DJANGO_TOOLBAR:
    # splice debug middleware after whitenoise
    MIDDLEWARE_CLASSES[:1] = [
        'debug_toolbar.middleware.DebugToolbarMiddleware',
    ]
```


Serving media files isn't slow, what was slow was all the profiling and stuff being run on all the static content requests.

Note from whitenoise project:

> Worried that serving static files with Python is horribly inefficient? Still think you should be using Amazon S3? Have a look at the [Infrequently Asked Questions](http://whitenoise.evans.io/en/stable/#infrequently-asked-questions).

I run my development using gunicorn and most of the static requests tend to be 304 responses. Machine was getting bogged down trying to profile requests that weren't needed. It's actually usable now. Not running DDT on prod.
