### ISSUE TITLE
Allow to reload rendered panel separately

### ISSUE THREAD

**Issue by blueyed** [jazzband/django-debug-toolbar#894]
In a multiprocess environment (e.g. a staging system being a load balancer) you will run into "Data for this panel isn't available anymore. Please reload the page and retry." (#750).

However, reloading just the rendered panel (e.g. `/__debug__/render_panel/?store_id=X&panel_id=SQLPanel`) will eventually work.

There was some discussion about using different stores (#819), which might not be possible in the end.

However, a workaround for now would be allowing to reload a panel's content alone, without reloading the whole page.

(While the toolbar's data might not be pickleable, there could still be information stored using Django's cache to know if there should be information for a given `store_id`.)

**Comment by ajostergaard** [comment]
You can reload panels by switching between them until you get results... Terrible solution but no worse than clicking a button until something works.

**Comment by jdufresne** [comment]
With the release of the new history panel, is this still an issue?

**Comment by tim-schilling** [comment]
Closing in favor of #1432
