### ISSUE TITLE
ImportError: No module named debug_toolbar.urls

### ISSUE THREAD

**Issue by tylerecouture** [jazzband/django-debug-toolbar#908]
```
from django.conf import settings
#...
if settings.DEBUG:
    urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls)), #`NameError: name 'debug_toolbar' is not defined`
```

My settings are divided between production and local, which I think is the problem: 

```
from .base import *

try:
    # this file will only exists on the production server
    from .production_settings import *
except:
    from .local import *
```

And in local.py:
```
INSTALLED_APPS += (
    # https://django-debug-toolbar.readthedocs.io/en/1.4/
    'debug_toolbar',
)
```

How can I get this to work?  Thanks!

**Comment by tylerecouture** [comment]
ugh... `import debug_toolbar` =)

**Comment by lordadamson** [comment]
documentation here: https://django-debug-toolbar.readthedocs.io/en/latest/installation.html

says nothing about `import debug_toolbar`

so where exactly do I import debug_toolbar?

**Comment by tim-schilling** [comment]
The docs say to use a string. If you want to use the actual module you
should import it at the top near your other imports.

**Comment by sourabhsinha396** [comment]
You might be using django_debug_toolbar version 3.2.2 or below.

I went through the changelog: of version 3.2.3 https://django-debug-toolbar.readthedocs.io/en/latest/changes.html#id4.
It says in 3.2.3 they have created urls module.

So, use pip install **django-debug-toolbar>=3.2.3**
