### ISSUE TITLE
Missing sqlparse version on setup.py for older versions(<=1.4) of django-debug-toolbar

### ISSUE THREAD

**Issue by sidneijp** [jazzband/django-debug-toolbar#912]
Hi,

I'do like to point for the fact that sqlparse's version is missing on the requirements part of the setup.py of older versions of django-debug-toolbar(<=1.4) and it's causing trouble since the lastest versions of sqlparse(>=0.2) aren't compatible with it. Just think you should know.

**Comment by matthiask** [comment]
Thanks for the report!

We know, and decided against fixing it in older releases. As Aymeric wrote, you can just pin sqlparse's version in your own requirements file if you really want to use unsupported versions of Django.)

Duplicate of https://github.com/jazzband/django-debug-toolbar/issues/866

**Comment by aaugustin** [comment]
The bigger problem is there's no way we can re-release an existing release with changes. This isn't how releases work.
