### ISSUE TITLE
RemovedInDjango20Warning - import of urls

### ISSUE THREAD

**Issue by marc-gist** [jazzband/django-debug-toolbar#917]
Need to update how url imports are called, etc.
Thought I would put this up now so its "on the radar" as 2.0 will be here soon, and I'd love to be able to switch smoothly from 1.11 to 2.0 on my latest project.

Thanks!

**Comment by matthiask** [comment]
This should work with 1.7. Please test and reopen if you encounter any problems. Thanks!
