### ISSUE TITLE
Global settings for access mixins

### ISSUE THREAD

**Issue by Nicals** [jazzband/django-debug-toolbar#919]
In a project, we usually have a global way of handling accesses in views.
The problem with access current access mixins, we need to configure *raise_exception*, *redirect_unanthenticated_users* and other mixins settings in the view class.
If I'm not wrong, their is two way of having the same settings on all views:

  + create our own AccessMixins with those attribute set to our required values.
  + set those settings in each views.

In one of my project, I had a huge number of views I needed to re-configure access for.

I think we need to have some globals settings that should be set to configure access mixins default attribute values. For exemple:

```python
# file: settings.py

BRACES = {
    'access_raise_exception': True,
    'redirect_unauthenticated_users': True,
}
```

**Comment by matthiask** [comment]
This issue seems misplaced in this project. Shouldn't you post this to https://github.com/brack3t/django-braces/ ?
