### ISSUE TITLE
Versions panel: Assume less about the signature of apps' `get_version()` (was: Running with wagtailmenus)

### ISSUE THREAD

**Issue by frague59** [jazzband/django-debug-toolbar#922]
Hi, 

I'm having an issue using django-debug-toolbar with wagtailmenus : a menu app for wagtail.

https://github.com/rkhleics/wagtailmenus/issues/115

Any idea ?

**Comment by auvipy** [comment]
give detail of your problem

**Comment by matthiask** [comment]
Yeah, the code might be made more defensive in this area, and not crash and burn just because the signature of `get_version` differs between apps.

This should be an easy fix for a first time contributor.
