### ISSUE TITLE
Is it possible to debug drf api request/response?

### ISSUE THREAD

**Issue by amankumarjain** [jazzband/django-debug-toolbar#930]
These apis are application api, whose response is application/json.
I am able to debug admin panel but how to enable debug for api, also for authenticated apis

**Comment by aaugustin** [comment]
You can reproduce the request in DRF's HTML interface and use the debug toolbar there.

You can also look for third-party "ajax panels" (I don't have more specific recommendations there).

**Comment by ashwoods** [comment]
You could also roll out your own middleware, and output the debug information in JSON.
Can we close this issue?
