### ISSUE TITLE
CSS problem - SQL panel does not fit on the screen in width in case of long lines

### ISSUE THREAD

**Issue by ygwain** [jazzband/django-debug-toolbar#939]
![image](https://cloud.githubusercontent.com/assets/1922086/25653206/91216d78-2ff4-11e7-8f33-53c3c2b229c9.png)
Adding `word-break: break-all;` on `#SQLPanel` element helps as workaround.
![image](https://cloud.githubusercontent.com/assets/1922086/25653351/2afd14a6-2ff5-11e7-9abc-6c5af813f4f4.png)

**Comment by matthiask** [comment]
Do you want to send a pull request? I'd appreciate it!

**Comment by ygwain** [comment]
I will this week
