### ISSUE TITLE
DjangoUnicodeDecodeError: 'utf8' codec can't decode byte 0xdd in position 10

### ISSUE THREAD

**Issue by bw2** [jazzband/django-debug-toolbar#959]
I just added the toolbar to my project and am seeing this error:
```
Internal Server Error: /resources/icons/font-awesome/fonts/fontawesome-webfont.woff2
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/utils/deprecation.py", line 142, in __call__
    response = self.process_response(request, response)
  File "/usr/local/lib/python2.7/site-packages/debug_toolbar/middleware.py", line 125, in process_response
    content = force_text(response.content, encoding=response.charset)
  File "/usr/local/lib/python2.7/site-packages/django/utils/encoding.py", line 88, in force_text
    raise DjangoUnicodeDecodeError(s, *e.args)
DjangoUnicodeDecodeError: 'utf8' codec can't decode byte 0xdd in position 10: invalid continuation byte. You passed in 'wOFF\x00\x01\x00\x00\x00\x01\x17T\x00... ...  (<type 'str'>)
```

**Comment by bw2** [comment]
I wouldn't mind just disabling debug-toolbar for this view. Is there a way to only enable debug-toolbar for a few specific views?

**Comment by matthiask** [comment]
Debug Toolbar should only be active for responses with a content type of `text/html` (and `application/xhtml+xml`, if anyone remembers that one :-)

I'm wondering why the webfont is processed as well. The Django static file serving falls back to `application/octet-stream` if it cannot determine a better content type. Are you using a different static file serving strategy by chance?

**Comment by bw2** [comment]
Yes, in this case I'm using the Django view to proxy http requests to another server - though the code forwards (almost) all request and response headers without modification. 

My current workaround, which might be even better in retrospect, is to just disable debug-toolbar in settings except when I'm debugging.
