### ISSUE TITLE
Spam from Travis CI

### ISSUE THREAD

**Issue by aaugustin** [jazzband/django-debug-toolbar#975]
Not sure what changed, but I'm drowning under emails from Travis CI (which still doesn't provide any way to unsubscribe that I can figure out; I never want Travis CI to email me for any reason whatsoever).

<img width="368" alt="screen shot 2017-07-02 at 21 07 25" src="https://user-images.githubusercontent.com/788910/27772850-b0b0e948-5f6a-11e7-8f9d-240c96e2ab78.png">

**Comment by matthiask** [comment]
https://github.com/etianen/django-s3-storage/blob/master/.travis.yml#L28

This should work. It would be even better if pyup wouldn't spam our repositories...

**Comment by jayfk** [comment]
Quoting my reply here (I work on pyup.io).

> Hi Matthias,
>
>The bot was added to the repository by one of your collaborators, I’ve deactivated it for now.
>
>That’s unfortunately one of the side effects of jazzband. Since the group is open to anyone to be a >collaborator, someone found the bot useful and added the repo to pyup.io. 
>
>I’m going to work on something to make it more clear who initially added the repo.
>
>Thanks for your work on open source software.
>
>Best,
>
>Jannis

**Comment by aaugustin** [comment]
Thank you for taking care of this!
