### ISSUE TITLE
no module named apps

### ISSUE THREAD

**Issue by peterchen16** [jazzband/django-debug-toolbar#978]
I get this error when I try to run my app with django debug toolbar:

File "/home/peter/.virtualenvs/decker/local/lib/python2.7/site-packages/debug_toolbar/toolbar.py", line 10, in <module>
    from django.apps import apps
ImportError: No module named apps

Any thoughts?

**Comment by peterchen16** [comment]
django version is

Django==1.6.4

**Comment by rehamFatima** [comment]
did any one find any solutions to this ?

**Comment by matthiask** [comment]
I don't know which version of django-debug-toolbar you use, but certainly one which does not work together with the old and unmaintained Django 1.6 line.

You should upgrade to a supported version of Django (at least 1.11 these days), or if you really have to, install an older version of django-debug-toolbar.
