### ISSUE TITLE
[Question] Is there away to redirect the info to a separate window or tab? Preferably streaming

### ISSUE THREAD

**Issue by japrogramer** [jazzband/django-debug-toolbar#985]
Hello world, I develop many async endpoints that are only meant to be used from js possibly with an ajax call. I want to get the info that i get from django debug toolbar for full httpresponse objects.
It seems that the simplest solution, to me, is if i could either have a page that streams all the metadata that is generated by DDT for each request?

**Comment by merwok** [comment]
Idea to support this: #999

**Comment by matthiask** [comment]
The debug toolbar has a history panel since 3.0 which allows switching to old requests and viewing their data. So therefore I'm going to close this as completed.
