### ISSUE TITLE
SQL panel in django 1.11

### ISSUE THREAD

**Issue by ad-m** [jazzband/django-debug-toolbar#986]
Hello,

SQL panel doesn't show any queries on Django 1.11+.  It works after downgrade to ``django <1.11``.

Greetings,

**Comment by tclancy** [comment]
I'm seeing this as well. Are you on Postgres? If so, it appears the new use of [cursors in Postgres in Django 1.11](https://docs.djangoproject.com/en/1.11/ref/databases/#transaction-pooling-server-side-cursors) is the culprit. You will need to add [`'DISABLE_SERVER_SIDE_CURSORS': True`](https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-DATABASE-DISABLE_SERVER_SIDE_CURSORS) to each entry in your `DATABASES` setting to get the queries working again.

**Comment by ad-m** [comment]
@tclancy:

One application:
``django==1.11.4`` + ``django-debug-toolbar==1.8`` + MySQL => 0 queries
``django==1.10.7`` + ``django-debug-toolbar==1.8`` + MySQL => 0 queries
``django==1.9.13`` + ``django-debug-toolbar==1.8`` + MySQL => 0 queries

Second application:
``Django==1.11.4`` + ``django-debug-toolbar==1.8`` + PostgreSQL (default) = 1 query
``django==1.10.7`` + ``django-debug-toolbar==1.8`` + PostgreSQL (default) => 1 query

Third application:
``django==1.11.4`` + ``django-debug-toolbar==1.8`` + MySQL => 0 queries
``django==1.10.7`` + ``django-debug-toolbar==1.8`` + MySQL => 0 queries
``django==1.9.13`` + ``django-debug-toolbar==1.8`` + MySQL => 0 queries

It's look that I have common misconfiguration in my application using MySQL or MySQL support is broken.

**Comment by ad-m** [comment]
It's due duplicate ```debug_toolbar.middleware.DebugToolbarMiddleware``` middleware.

**Comment by blueyed** [comment]
See https://github.com/jazzband/django-debug-toolbar/pull/1106 for handling duplicate entries (which can be a valid use case).
