### ISSUE TITLE
Error when recording SQL queries that are byte-strings

### ISSUE THREAD

**Issue by ahardjasa** [jazzband/django-debug-toolbar#987]
When a byte-string SQL query is run, e.g. those produced by `psycopg2.execute_values`, I get the error `TypeError: startswith first arg must be bytes or a tuple of bytes, not str`. 

This seems to be a result of line 142 in `django-debug-toolbar/debug_toolbar/panels/sql/tracking.py`: `'is_select': sql.lower().strip().startswith('select')`
since 'select' is unicode. 

Flask-debugtoolbar [addressed this](https://github.com/mgood/flask-debugtoolbar/commit/70488fc14a387cfcae6c48811ea4b6ce68564fef) with `prefix = b'select' if isinstance(statement, bytes) else 'select'` - would that work in this case?

**Comment by matthiask** [comment]
The DB API 2.0 PEP (https://www.python.org/dev/peps/pep-0249/) does not mandate a type for the SQL operation -- whether it's bytes or str isn't defined (which isn't surprising at all since the PEP was added at [least 17 years ago](https://github.com/python/peps/commit/8f8671dac38b1ed8950d0318a32618881eff1982)). 

Still, I'm a bit reluctant because I fear breakage throughout; is this really all that's required to support byte string queries? Should we even support byte string queries at all?

**Comment by aaugustin** [comment]
I'm OK with that change.

**Comment by matthiask** [comment]
Great. @ahardjasa do you want to submit a pull request?

**Comment by thaxy** [comment]
Same problem for raw SQL such as:

```
with connection.cursor() as cursor:
            cursor.execute(
                sql.SQL(
                    '''
                    SELECT json_build_object(
                        'data', array_agg(r)
                    )
                    FROM (
                        SELECT
                        a,
                        {}
                        FROM b
                        WHERE c=%s
                        ORDER BY a DESC
                        LIMIT %s
                    ) r
                    '''
                ).format(var),
                [x, 5]
            )
            result = cursor.fetchall()
```

**Comment by bschollnick** [comment]
This appears to be a problem for me as well.  I'm not sure if this should be broken off into a different issue ticket?

I'm storing binary image thumbnails, and it works fine when I am not running django debug toolbar, but as soon as I enable DDT, a bit of chaos occurs.

With it enabled, Django can not store, read, or manipulate the binary fields.  Everything else works fine, but the binary fields do not work.

**Comment by Caiofcas** [comment]
Is this still a problem? Looking around I found this test (in `tests/panels/test_sql.py`) and it seems to catch this use case:

```python
def test_non_ascii_query(self):
        ...
        # non-ASCII bytes parameters
        list(Binary.objects.filter(field__in=["café".encode()]))
        self.assertEqual(len(self.panel._queries), 3)
        ...
```

**Comment by matthiask** [comment]
@Caiofcas Thank you! If I'm reading this issue correctly it is about the whole SQL string being bytes which is different from the test where (only) a parameter is bytes.

**Comment by matthiask** [comment]
@Lucidiot It seems nobody is actively working on this right now. Does the proposed fix in the initial report make everything work as it should? It would be very helpful if you could check this and maybe submit a pull request with a small test case. Thanks in advance!

**Comment by living180** [comment]
@Lucidiot I could also potentially take a look in the next couple of days if you don't have time to get a PR together.

**Comment by Lucidiot** [comment]
I found that I was hitting an error in another place, before the code originally mentioned in this issue could even be called, so I fixed that instead and now the query seems to always be a string by the time it reaches the `is_select` of the initial report.
