### ISSUE TITLE
Toolbar language selection

### ISSUE THREAD

**Issue by WhyNotHugo** [jazzband/django-debug-toolbar#991]
django-debug-toolbar picks up the main apps locale to determine it's language. I'd really like to override this via a setting.

The app I'm working on is in Spanish, but it doesn't really make sense to have the toolbar in spanish; even as a native spanish speaker living in a spanish-speaking country, all the words are weird to me because we use the english words in our day to day work (even when talking between ourselves), and we always use development software in english.

(TBH, I've never seen a developer work with tools configured to use spanish, since all online docs, etc are in english, so all the entire developer subculture has kinda adopted english terms).

**Comment by trekkerghost** [comment]
I've arrived at this issue looking for a way to change the language of the toolbar as well.

**Comment by leandrodesouzadev** [comment]
Is there anyone working on this now?
I see that this is stale for quite some time and willing to help.

**Comment by WhyNotHugo** [comment]
@leandrodesouzadev Thanks a lot for addressing this one!
