### ISSUE TITLE
Redirection

### ISSUE THREAD

**Issue by Olamyy** [jazzband/django-debug-toolbar#996]
Why does the `Django Debug Toolbar` intercept redirects?

I've been through it's documentation over 3 times now and I can't seem to find any reference as to why it does that.

**Comment by matthiask** [comment]
https://github.com/jazzband/django-debug-toolbar/blob/bb9bce5985af589f653ed4aa2e9c632f03eb6445/debug_toolbar/settings.py#L18

`INTERCEPT_REDIRECTS` is deprecated respectively the `RedirectsPanel` is disabled by default. Did you enable it by chance by overriding `DISABLE_PANELS`?
